include: package:lints/recommended.yaml

analyzer:
  exclude:
    - tool/**

linter:
  rules:
    prefer_single_quotes: false
    constant_identifier_names: false
    library_private_types_in_public_api: false
