// GENERATED by tool/generate_models.mjs — do not edit.
part of '../models.dart';

/// The API key's details.
class AdminCreateApiKey {
  AdminCreateApiKey({
    this.title,
    this.type,
  });

  /// The API key's title.
  final String? title;
  /// The API key's type. Use `secret` for a user's API key; Use `publishable` for Publishable API keys.
  final String? type;

  factory AdminCreateApiKey.fromJson(Map<String, dynamic> json) => AdminCreateApiKey(
    title: json["title"] as String?,
    type: json["type"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (type != null) "type": type!,
  };
}

/// The calculated shipping option's details.
class AdminCreateCalculatedShippingOption {
  AdminCreateCalculatedShippingOption({
    this.priceType,
    this.name,
    this.serviceZoneId,
    this.shippingProfileId,
    this.data,
    this.providerId,
    this.type,
    this.typeId,
    this.rules,
    this.metadata,
  });

  /// The calculated shipping option's price type.
  final String? priceType;
  /// The calculated shipping option's name.
  final String? name;
  /// The ID of the associated service zone.
  final String? serviceZoneId;
  /// The ID of the associated shipping profile.
  final String? shippingProfileId;
  /// The calculated shipping option's data.
  final Map<String, dynamic>? data;
  /// The ID of the fulfillment provider handling this calculated shipping option.
  final String? providerId;
  final AdminCreateShippingOptionType? type;
  /// The ID of the shipping option type that this shipping option belongs to.
  final String? typeId;
  /// The calculated shipping option's rules.
  final List<AdminCreateShippingOptionRule>? rules;
  /// The shipping option's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateCalculatedShippingOption.fromJson(Map<String, dynamic> json) => AdminCreateCalculatedShippingOption(
    priceType: json["price_type"] as String?,
    name: json["name"] as String?,
    serviceZoneId: json["service_zone_id"] as String?,
    shippingProfileId: json["shipping_profile_id"] as String?,
    data: json["data"] as Map<String, dynamic>?,
    providerId: json["provider_id"] as String?,
    type: json["type"] == null ? null : AdminCreateShippingOptionType.fromJson(json["type"] as Map<String, dynamic>),
    typeId: json["type_id"] as String?,
    rules: (json["rules"] as List?)?.map((e) => e == null ? null : AdminCreateShippingOptionRule.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateShippingOptionRule>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (priceType != null) "price_type": priceType!,
    if (name != null) "name": name!,
    if (serviceZoneId != null) "service_zone_id": serviceZoneId!,
    if (shippingProfileId != null) "shipping_profile_id": shippingProfileId!,
    if (data != null) "data": data!,
    if (providerId != null) "provider_id": providerId!,
    if (type != null) "type": type!.toJson(),
    if (typeId != null) "type_id": typeId!,
    if (rules != null) "rules": rules!.map((e) => e.toJson()).toList(),
    if (metadata != null) "metadata": metadata!,
  };
}

/// The claim's details.
class AdminCreateClaim {
  AdminCreateClaim({
    this.type,
    this.orderId,
    this.description,
    this.internalNote,
    this.reasonId,
    this.metadata,
  });

  /// The claim's type.
  final String? type;
  /// The ID of the order the claim is created for.
  final String? orderId;
  /// The claim's description.
  final String? description;
  /// A note viewed only by admin users.
  final String? internalNote;
  /// The ID of the associated return reason.
  final String? reasonId;
  /// The claim's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateClaim.fromJson(Map<String, dynamic> json) => AdminCreateClaim(
    type: json["type"] as String?,
    orderId: json["order_id"] as String?,
    description: json["description"] as String?,
    internalNote: json["internal_note"] as String?,
    reasonId: json["reason_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (type != null) "type": type!,
    if (orderId != null) "order_id": orderId!,
    if (description != null) "description": description!,
    if (internalNote != null) "internal_note": internalNote!,
    if (reasonId != null) "reason_id": reasonId!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The customer group's details.
class AdminCreateCustomerGroup {
  AdminCreateCustomerGroup({
    this.name,
    this.metadata,
  });

  /// The customer group's name.
  final String? name;
  /// The customer group's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateCustomerGroup.fromJson(Map<String, dynamic> json) => AdminCreateCustomerGroup(
    name: json["name"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The exchange's details.
class AdminCreateExchange {
  AdminCreateExchange({
    this.orderId,
    this.description,
    this.internalNote,
    this.metadata,
  });

  /// The ID of the order this exchange is created for.
  final String? orderId;
  /// The exchange's description.
  final String? description;
  /// A note viewed only by admin users.
  final String? internalNote;
  /// The exchange's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateExchange.fromJson(Map<String, dynamic> json) => AdminCreateExchange(
    orderId: json["order_id"] as String?,
    description: json["description"] as String?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (orderId != null) "order_id": orderId!,
    if (description != null) "description": description!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The flat rate shipping option's details.
class AdminCreateFlatRateShippingOption {
  AdminCreateFlatRateShippingOption({
    this.name,
    this.serviceZoneId,
    this.shippingProfileId,
    this.data,
    this.priceType,
    this.providerId,
    this.type,
    this.prices,
    this.typeId,
    this.rules,
    this.metadata,
  });

  /// The flat-rate shipping option's name.
  final String? name;
  /// The ID of the associated service zone.
  final String? serviceZoneId;
  /// The ID of the associated shipping profile.
  final String? shippingProfileId;
  /// The flat-rate shipping option's data, useful for the fulfillment provider handling its processing.
  final Map<String, dynamic>? data;
  /// The shipping option's price type. If `flat`, the shipping option has a fixed price set in `prices`. Otherwise, the shipping option's price is calculated by the 
  final String? priceType;
  /// The ID of the fulfillment provider handling this shipping option.
  final String? providerId;
  final AdminCreateShippingOptionType? type;
  /// The shipping option's prices.
  final List<dynamic>? prices;
  /// The ID of the shipping option type that this shipping option belongs to.
  final String? typeId;
  /// The shipping option's rules.
  final List<AdminCreateShippingOptionRule>? rules;
  /// The shipping option's metadata.
  final Map<String, dynamic>? metadata;

  factory AdminCreateFlatRateShippingOption.fromJson(Map<String, dynamic> json) => AdminCreateFlatRateShippingOption(
    name: json["name"] as String?,
    serviceZoneId: json["service_zone_id"] as String?,
    shippingProfileId: json["shipping_profile_id"] as String?,
    data: json["data"] as Map<String, dynamic>?,
    priceType: json["price_type"] as String?,
    providerId: json["provider_id"] as String?,
    type: json["type"] == null ? null : AdminCreateShippingOptionType.fromJson(json["type"] as Map<String, dynamic>),
    prices: (json["prices"] as List?)?.map((e) => e).toList().cast<dynamic>(),
    typeId: json["type_id"] as String?,
    rules: (json["rules"] as List?)?.map((e) => e == null ? null : AdminCreateShippingOptionRule.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateShippingOptionRule>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (serviceZoneId != null) "service_zone_id": serviceZoneId!,
    if (shippingProfileId != null) "shipping_profile_id": shippingProfileId!,
    if (data != null) "data": data!,
    if (priceType != null) "price_type": priceType!,
    if (providerId != null) "provider_id": providerId!,
    if (type != null) "type": type!.toJson(),
    if (prices != null) "prices": prices!.map((e) => e).toList(),
    if (typeId != null) "type_id": typeId!,
    if (rules != null) "rules": rules!.map((e) => e.toJson()).toList(),
    if (metadata != null) "metadata": metadata!,
  };
}

/// The filfillment's details.
class AdminCreateFulfillment {
  AdminCreateFulfillment({
    this.locationId,
    this.providerId,
    this.deliveryAddress,
    this.items,
    this.labels,
    this.orderId,
    this.shippingOptionId,
    this.data,
    this.packedAt,
    this.shippedAt,
    this.deliveredAt,
    this.canceledAt,
    this.metadata,
  });

  /// The ID of the location the items are fulfilled from.
  final String? locationId;
  /// The ID of the provider handling this fulfillment.
  final String? providerId;
  final AdminFulfillmentDeliveryAddress? deliveryAddress;
  /// The items to fulfill.
  final List<AdminCreateFulfillmentItem>? items;
  /// The labels for the fulfillment's shipments.
  final List<AdminCreateFulfillmentLabel>? labels;
  /// The ID of the order this fulfillment is created for.
  final String? orderId;
  /// The ID of the shipping option used in the order.
  final String? shippingOptionId;
  /// Any data useful for the fulfillment provider to handle the fulfillment.
  final Map<String, dynamic>? data;
  /// The date and time the fulfillment was packed.
  final DateTime? packedAt;
  /// The date and time the fulfillment was shipped.
  final DateTime? shippedAt;
  /// The date and time the fulfillment was delivered.
  final DateTime? deliveredAt;
  /// The date and time the fulfillment was canceled.
  final DateTime? canceledAt;
  /// The fulfillment's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateFulfillment.fromJson(Map<String, dynamic> json) => AdminCreateFulfillment(
    locationId: json["location_id"] as String?,
    providerId: json["provider_id"] as String?,
    deliveryAddress: json["delivery_address"] == null ? null : AdminFulfillmentDeliveryAddress.fromJson(json["delivery_address"] as Map<String, dynamic>),
    items: (json["items"] as List?)?.map((e) => e == null ? null : AdminCreateFulfillmentItem.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateFulfillmentItem>(),
    labels: (json["labels"] as List?)?.map((e) => e == null ? null : AdminCreateFulfillmentLabel.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateFulfillmentLabel>(),
    orderId: json["order_id"] as String?,
    shippingOptionId: json["shipping_option_id"] as String?,
    data: json["data"] as Map<String, dynamic>?,
    packedAt: json["packed_at"] == null ? null : DateTime.parse(json["packed_at"] as String),
    shippedAt: json["shipped_at"] == null ? null : DateTime.parse(json["shipped_at"] as String),
    deliveredAt: json["delivered_at"] == null ? null : DateTime.parse(json["delivered_at"] as String),
    canceledAt: json["canceled_at"] == null ? null : DateTime.parse(json["canceled_at"] as String),
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (locationId != null) "location_id": locationId!,
    if (providerId != null) "provider_id": providerId!,
    if (deliveryAddress != null) "delivery_address": deliveryAddress!.toJson(),
    if (items != null) "items": items!.map((e) => e.toJson()).toList(),
    if (labels != null) "labels": labels!.map((e) => e.toJson()).toList(),
    if (orderId != null) "order_id": orderId!,
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (data != null) "data": data!,
    if (packedAt != null) "packed_at": packedAt!.toIso8601String(),
    if (shippedAt != null) "shipped_at": shippedAt!.toIso8601String(),
    if (deliveredAt != null) "delivered_at": deliveredAt!.toIso8601String(),
    if (canceledAt != null) "canceled_at": canceledAt!.toIso8601String(),
    if (metadata != null) "metadata": metadata!,
  };
}

/// An item to fulfill.
class AdminCreateFulfillmentItem {
  AdminCreateFulfillmentItem({
    this.title,
    this.sku,
    this.quantity,
    this.barcode,
    this.lineItemId,
    this.inventoryItemId,
  });

  /// The item's title.
  final String? title;
  /// The item's SKU.
  final String? sku;
  /// The quantity to fulfill of the item.
  final num? quantity;
  /// The item's barcode.
  final String? barcode;
  /// The ID of the associated line item.
  final String? lineItemId;
  /// The ID of the inventory item associated with the underlying variant.
  final String? inventoryItemId;

  factory AdminCreateFulfillmentItem.fromJson(Map<String, dynamic> json) => AdminCreateFulfillmentItem(
    title: json["title"] as String?,
    sku: json["sku"] as String?,
    quantity: json["quantity"] as num?,
    barcode: json["barcode"] as String?,
    lineItemId: json["line_item_id"] as String?,
    inventoryItemId: json["inventory_item_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (sku != null) "sku": sku!,
    if (quantity != null) "quantity": quantity!,
    if (barcode != null) "barcode": barcode!,
    if (lineItemId != null) "line_item_id": lineItemId!,
    if (inventoryItemId != null) "inventory_item_id": inventoryItemId!,
  };
}

/// Details of the fulfillment label to create.
class AdminCreateFulfillmentLabel {
  AdminCreateFulfillmentLabel({
    this.trackingNumber,
    this.trackingUrl,
    this.labelUrl,
  });

  /// The label's tracking number.
  final String? trackingNumber;
  /// The label's tracking URL.
  final String? trackingUrl;
  /// The label's URL.
  final String? labelUrl;

  factory AdminCreateFulfillmentLabel.fromJson(Map<String, dynamic> json) => AdminCreateFulfillmentLabel(
    trackingNumber: json["tracking_number"] as String?,
    trackingUrl: json["tracking_url"] as String?,
    labelUrl: json["label_url"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (trackingNumber != null) "tracking_number": trackingNumber!,
    if (trackingUrl != null) "tracking_url": trackingUrl!,
    if (labelUrl != null) "label_url": labelUrl!,
  };
}

/// Details of the service zone to create for the fulfillment set.
class AdminCreateFulfillmentSetServiceZone {
  AdminCreateFulfillmentSetServiceZone({
    this.name,
    this.geoZones,
  });

  /// The service zone's name.
  final String? name;
  /// The service zone's geo zones.
  final List<dynamic>? geoZones;

  factory AdminCreateFulfillmentSetServiceZone.fromJson(Map<String, dynamic> json) => AdminCreateFulfillmentSetServiceZone(
    name: json["name"] as String?,
    geoZones: (json["geo_zones"] as List?)?.map((e) => e).toList().cast<dynamic>(),
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (geoZones != null) "geo_zones": geoZones!.map((e) => e).toList(),
  };
}

/// Details of the shipment to create for a fulfillment.
class AdminCreateFulfillmentShipment {
  AdminCreateFulfillmentShipment({
    this.labels,
  });

  /// The shipment's labels.
  final List<AdminCreateFulfillmentLabel>? labels;

  factory AdminCreateFulfillmentShipment.fromJson(Map<String, dynamic> json) => AdminCreateFulfillmentShipment(
    labels: (json["labels"] as List?)?.map((e) => e == null ? null : AdminCreateFulfillmentLabel.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateFulfillmentLabel>(),
  );

  Map<String, dynamic> toJson() => {
    if (labels != null) "labels": labels!.map((e) => e.toJson()).toList(),
  };
}

/// The details of the gift card to create.
class AdminCreateGiftCardParams {
  AdminCreateGiftCardParams({
    this.code,
    this.value,
    this.currencyCode,
    this.expiresAt,
    this.referenceId,
    this.reference,
    this.lineItemId,
    this.customerId,
    this.metadata,
  });

  /// The gift card's code.
  final String? code;
  /// The gift card's amount.
  final num? value;
  /// The gift card's currency code.
  final String? currencyCode;
  /// The date the gift card expires at.
  final String? expiresAt;
  /// The gift card's reference ID.
  final String? referenceId;
  /// The gift card's reference.
  final String? reference;
  /// The ID of the line item associated with the gift card.
  final String? lineItemId;
  /// The ID of the customer associated with the gift card.
  final String? customerId;
  /// The gift card's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateGiftCardParams.fromJson(Map<String, dynamic> json) => AdminCreateGiftCardParams(
    code: json["code"] as String?,
    value: json["value"] as num?,
    currencyCode: json["currency_code"] as String?,
    expiresAt: json["expires_at"] as String?,
    referenceId: json["reference_id"] as String?,
    reference: json["reference"] as String?,
    lineItemId: json["line_item_id"] as String?,
    customerId: json["customer_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (code != null) "code": code!,
    if (value != null) "value": value!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (expiresAt != null) "expires_at": expiresAt!,
    if (referenceId != null) "reference_id": referenceId!,
    if (reference != null) "reference": reference!,
    if (lineItemId != null) "line_item_id": lineItemId!,
    if (customerId != null) "customer_id": customerId!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The inventory item's details.
class AdminCreateInventoryItem {
  AdminCreateInventoryItem({
    this.sku,
    this.hsCode,
    this.weight,
    this.length,
    this.height,
    this.width,
    this.originCountry,
    this.midCode,
    this.material,
    this.title,
    this.description,
    this.requiresShipping,
    this.thumbnail,
    this.metadata,
    this.locationLevels,
  });

  /// The inventory item's SKU.
  final String? sku;
  /// The inventory item's HS code.
  final String? hsCode;
  /// The inventory item's weight.
  final num? weight;
  /// The inventory item's length.
  final num? length;
  /// The inventory item's height.
  final num? height;
  /// The inventory item's width.
  final num? width;
  /// The inventory item's origin country.
  final String? originCountry;
  /// The inventory item's mid code.
  final String? midCode;
  /// The inventory item's material.
  final String? material;
  /// The inventory item's title.
  final String? title;
  /// The description of the variant associated with the inventory item.
  final String? description;
  /// Whether the item requires shipping.
  final bool? requiresShipping;
  /// The inventory item's thumbnail.
  final String? thumbnail;
  /// The inventory item's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The inventory item's location levels.
  final List<AdminBatchCreateInventoryItemLocationLevels>? locationLevels;

  factory AdminCreateInventoryItem.fromJson(Map<String, dynamic> json) => AdminCreateInventoryItem(
    sku: json["sku"] as String?,
    hsCode: json["hs_code"] as String?,
    weight: json["weight"] as num?,
    length: json["length"] as num?,
    height: json["height"] as num?,
    width: json["width"] as num?,
    originCountry: json["origin_country"] as String?,
    midCode: json["mid_code"] as String?,
    material: json["material"] as String?,
    title: json["title"] as String?,
    description: json["description"] as String?,
    requiresShipping: json["requires_shipping"] as bool?,
    thumbnail: json["thumbnail"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    locationLevels: (json["location_levels"] as List?)?.map((e) => e == null ? null : AdminBatchCreateInventoryItemLocationLevels.fromJson(e as Map<String, dynamic>)).toList().cast<AdminBatchCreateInventoryItemLocationLevels>(),
  );

  Map<String, dynamic> toJson() => {
    if (sku != null) "sku": sku!,
    if (hsCode != null) "hs_code": hsCode!,
    if (weight != null) "weight": weight!,
    if (length != null) "length": length!,
    if (height != null) "height": height!,
    if (width != null) "width": width!,
    if (originCountry != null) "origin_country": originCountry!,
    if (midCode != null) "mid_code": midCode!,
    if (material != null) "material": material!,
    if (title != null) "title": title!,
    if (description != null) "description": description!,
    if (requiresShipping != null) "requires_shipping": requiresShipping!,
    if (thumbnail != null) "thumbnail": thumbnail!,
    if (metadata != null) "metadata": metadata!,
    if (locationLevels != null) "location_levels": locationLevels!.map((e) => e.toJson()).toList(),
  };
}

/// The details of a credit line to add to an order.
class AdminCreateOrderCreditLine {
  AdminCreateOrderCreditLine({
    this.amount,
    this.reference,
    this.referenceId,
    this.metadata,
  });

  /// The amount of the credit line.
  final num? amount;
  /// The name of the table that the credit line is referencing.
  final String? reference;
  /// The ID of a record in the table that the credit line is referencing.
  final String? referenceId;
  /// The credit line's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateOrderCreditLine.fromJson(Map<String, dynamic> json) => AdminCreateOrderCreditLine(
    amount: json["amount"] as num?,
    reference: json["reference"] as String?,
    referenceId: json["reference_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (amount != null) "amount": amount!,
    if (reference != null) "reference": reference!,
    if (referenceId != null) "reference_id": referenceId!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The payment collection's details.
class AdminCreatePaymentCollection {
  AdminCreatePaymentCollection({
    this.orderId,
    this.amount,
  });

  /// The ID of the associated order.
  final String? orderId;
  /// The amount to be paid.
  final num? amount;

  factory AdminCreatePaymentCollection.fromJson(Map<String, dynamic> json) => AdminCreatePaymentCollection(
    orderId: json["order_id"] as String?,
    amount: json["amount"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (orderId != null) "order_id": orderId!,
    if (amount != null) "amount": amount!,
  };
}

/// The price list's details.
class AdminCreatePriceList {
  AdminCreatePriceList({
    this.title,
    this.description,
    this.startsAt,
    this.endsAt,
    this.status,
    this.type,
    this.rules,
    this.prices,
    this.metadata,
  });

  /// The price list's title.
  final String? title;
  /// The price list's description.
  final String? description;
  /// The date and time the price list starts at.
  final DateTime? startsAt;
  /// The date and time the price list ends at.
  final DateTime? endsAt;
  /// The price list's status.
  final String? status;
  /// The price list's type.
  final String? type;
  /// The price list's rules.
  final Map<String, dynamic>? rules;
  /// The price list's prices.
  final List<AdminCreatePriceListPrice>? prices;
  /// Key-value pairs of custom data.
  final Map<String, dynamic>? metadata;

  factory AdminCreatePriceList.fromJson(Map<String, dynamic> json) => AdminCreatePriceList(
    title: json["title"] as String?,
    description: json["description"] as String?,
    startsAt: json["starts_at"] == null ? null : DateTime.parse(json["starts_at"] as String),
    endsAt: json["ends_at"] == null ? null : DateTime.parse(json["ends_at"] as String),
    status: json["status"] as String?,
    type: json["type"] as String?,
    rules: json["rules"] as Map<String, dynamic>?,
    prices: (json["prices"] as List?)?.map((e) => e == null ? null : AdminCreatePriceListPrice.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreatePriceListPrice>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (description != null) "description": description!,
    if (startsAt != null) "starts_at": startsAt!.toIso8601String(),
    if (endsAt != null) "ends_at": endsAt!.toIso8601String(),
    if (status != null) "status": status!,
    if (type != null) "type": type!,
    if (rules != null) "rules": rules!,
    if (prices != null) "prices": prices!.map((e) => e.toJson()).toList(),
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of a price to be created within a price list.
class AdminCreatePriceListPrice {
  AdminCreatePriceListPrice({
    this.currencyCode,
    this.amount,
    this.variantId,
    this.minQuantity,
    this.maxQuantity,
    this.rules,
  });

  /// The price's currency code.
  final String? currencyCode;
  /// The price's amount.
  final num? amount;
  /// The ID of the product variant this price is for.
  final String? variantId;
  /// The minimum quantity required in the cart for this price to be applied.
  final num? minQuantity;
  /// The maximum quantity in the cart that shouldn't be crossed for this price to be applied.
  final num? maxQuantity;
  /// The price's rules.
  final Map<String, dynamic>? rules;

  factory AdminCreatePriceListPrice.fromJson(Map<String, dynamic> json) => AdminCreatePriceListPrice(
    currencyCode: json["currency_code"] as String?,
    amount: json["amount"] as num?,
    variantId: json["variant_id"] as String?,
    minQuantity: json["min_quantity"] as num?,
    maxQuantity: json["max_quantity"] as num?,
    rules: json["rules"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (currencyCode != null) "currency_code": currencyCode!,
    if (amount != null) "amount": amount!,
    if (variantId != null) "variant_id": variantId!,
    if (minQuantity != null) "min_quantity": minQuantity!,
    if (maxQuantity != null) "max_quantity": maxQuantity!,
    if (rules != null) "rules": rules!,
  };
}

/// The price preference's details.
class AdminCreatePricePreference {
  AdminCreatePricePreference({
    this.attribute,
    this.value,
    this.isTaxInclusive,
  });

  /// The name of the attribute the price preference applies on.
  final String? attribute;
  /// The attribute's value.
  final String? value;
  /// Whether the price is tax inclusive if the value of the specified attribute matches the specified value.
  final bool? isTaxInclusive;

  factory AdminCreatePricePreference.fromJson(Map<String, dynamic> json) => AdminCreatePricePreference(
    attribute: json["attribute"] as String?,
    value: json["value"] as String?,
    isTaxInclusive: json["is_tax_inclusive"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (attribute != null) "attribute": attribute!,
    if (value != null) "value": value!,
    if (isTaxInclusive != null) "is_tax_inclusive": isTaxInclusive!,
  };
}

/// The product's details.
class AdminCreateProduct {
  AdminCreateProduct({
    this.title,
    this.subtitle,
    this.description,
    this.isGiftcard,
    this.discountable,
    this.images,
    this.thumbnail,
    this.handle,
    this.status,
    this.typeId,
    this.collectionId,
    this.categories,
    this.tags,
    this.options,
    this.variants,
    this.salesChannels,
    this.weight,
    this.length,
    this.height,
    this.width,
    this.hsCode,
    this.midCode,
    this.originCountry,
    this.material,
    this.metadata,
    this.externalId,
    this.shippingProfileId,
  });

  /// The product's title.
  final String? title;
  /// The product's subtitle.
  final String? subtitle;
  /// The product's description.
  final String? description;
  /// Whether the product is a gift card.
  final bool? isGiftcard;
  /// Whether the product is discountable.
  final bool? discountable;
  /// The product's images.
  final List<Map<String, dynamic>>? images;
  /// The URL of the product's thumbnail.
  final String? thumbnail;
  /// The product's handle.
  final String? handle;
  /// The product's status.
  final String? status;
  /// The ID of the type the product belongs to.
  final String? typeId;
  /// The ID of the collection the product belongs to.
  final String? collectionId;
  /// The categories the product belongs to.
  final List<Map<String, dynamic>>? categories;
  /// The product's tags.
  final List<Map<String, dynamic>>? tags;
  /// The product's options.
  final List<AdminCreateProductOption>? options;
  /// The product's variants.
  final List<AdminCreateProductVariant>? variants;
  /// The sales channels the product is available in.
  final List<Map<String, dynamic>>? salesChannels;
  /// The product's weight.
  final num? weight;
  /// The product's length.
  final num? length;
  /// The product's height.
  final num? height;
  /// The product's width.
  final num? width;
  /// The product's HS code.
  final String? hsCode;
  /// The product's MID code.
  final String? midCode;
  /// The product's origin country.
  final String? originCountry;
  /// The product's material.
  final String? material;
  /// The product's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the product in an external or third-party system.
  final String? externalId;
  /// The ID of the product's shipping profile.
  final String? shippingProfileId;

  factory AdminCreateProduct.fromJson(Map<String, dynamic> json) => AdminCreateProduct(
    title: json["title"] as String?,
    subtitle: json["subtitle"] as String?,
    description: json["description"] as String?,
    isGiftcard: json["is_giftcard"] as bool?,
    discountable: json["discountable"] as bool?,
    images: (json["images"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    thumbnail: json["thumbnail"] as String?,
    handle: json["handle"] as String?,
    status: json["status"] as String?,
    typeId: json["type_id"] as String?,
    collectionId: json["collection_id"] as String?,
    categories: (json["categories"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    tags: (json["tags"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    options: (json["options"] as List?)?.map((e) => e == null ? null : AdminCreateProductOption.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateProductOption>(),
    variants: (json["variants"] as List?)?.map((e) => e == null ? null : AdminCreateProductVariant.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateProductVariant>(),
    salesChannels: (json["sales_channels"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    weight: json["weight"] as num?,
    length: json["length"] as num?,
    height: json["height"] as num?,
    width: json["width"] as num?,
    hsCode: json["hs_code"] as String?,
    midCode: json["mid_code"] as String?,
    originCountry: json["origin_country"] as String?,
    material: json["material"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    externalId: json["external_id"] as String?,
    shippingProfileId: json["shipping_profile_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (subtitle != null) "subtitle": subtitle!,
    if (description != null) "description": description!,
    if (isGiftcard != null) "is_giftcard": isGiftcard!,
    if (discountable != null) "discountable": discountable!,
    if (images != null) "images": images!.map((e) => e).toList(),
    if (thumbnail != null) "thumbnail": thumbnail!,
    if (handle != null) "handle": handle!,
    if (status != null) "status": status!,
    if (typeId != null) "type_id": typeId!,
    if (collectionId != null) "collection_id": collectionId!,
    if (categories != null) "categories": categories!.map((e) => e).toList(),
    if (tags != null) "tags": tags!.map((e) => e).toList(),
    if (options != null) "options": options!.map((e) => e.toJson()).toList(),
    if (variants != null) "variants": variants!.map((e) => e.toJson()).toList(),
    if (salesChannels != null) "sales_channels": salesChannels!.map((e) => e).toList(),
    if (weight != null) "weight": weight!,
    if (length != null) "length": length!,
    if (height != null) "height": height!,
    if (width != null) "width": width!,
    if (hsCode != null) "hs_code": hsCode!,
    if (midCode != null) "mid_code": midCode!,
    if (originCountry != null) "origin_country": originCountry!,
    if (material != null) "material": material!,
    if (metadata != null) "metadata": metadata!,
    if (externalId != null) "external_id": externalId!,
    if (shippingProfileId != null) "shipping_profile_id": shippingProfileId!,
  };
}

/// The product category's details.
class AdminCreateProductCategory {
  AdminCreateProductCategory({
    this.name,
    this.description,
    this.handle,
    this.isInternal,
    this.isActive,
    this.parentCategoryId,
    this.rank,
    this.metadata,
    this.externalId,
  });

  /// The product category's name.
  final String? name;
  /// The product category's description.
  final String? description;
  /// The product category's handle.
  final String? handle;
  /// Whether the product category is only used and seen by admin users.
  final bool? isInternal;
  /// Whether the product category is active.
  final bool? isActive;
  /// The ID of a category that's the parent of this one.
  final String? parentCategoryId;
  /// The sorting order of the product category among sibling categories.
  final num? rank;
  /// The product category's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the product category in an external or third-party system.
  final String? externalId;

  factory AdminCreateProductCategory.fromJson(Map<String, dynamic> json) => AdminCreateProductCategory(
    name: json["name"] as String?,
    description: json["description"] as String?,
    handle: json["handle"] as String?,
    isInternal: json["is_internal"] as bool?,
    isActive: json["is_active"] as bool?,
    parentCategoryId: json["parent_category_id"] as String?,
    rank: json["rank"] as num?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (description != null) "description": description!,
    if (handle != null) "handle": handle!,
    if (isInternal != null) "is_internal": isInternal!,
    if (isActive != null) "is_active": isActive!,
    if (parentCategoryId != null) "parent_category_id": parentCategoryId!,
    if (rank != null) "rank": rank!,
    if (metadata != null) "metadata": metadata!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The product option's details.
class AdminCreateProductOption {
  AdminCreateProductOption({
    this.title,
    this.values,
  });

  /// The product option's title.
  final String? title;
  /// The product option's values.
  final List<String>? values;

  factory AdminCreateProductOption.fromJson(Map<String, dynamic> json) => AdminCreateProductOption(
    title: json["title"] as String?,
    values: (json["values"] as List?)?.map((e) => e as String?).toList().cast<String>(),
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (values != null) "values": values!.map((e) => e).toList(),
  };
}

/// The product tag's details.
class AdminCreateProductTag {
  AdminCreateProductTag({
    this.value,
    this.metadata,
    this.externalId,
  });

  /// The product tag's value.
  final String? value;
  /// The product tag's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the product tag in an external or third-party system.
  final String? externalId;

  factory AdminCreateProductTag.fromJson(Map<String, dynamic> json) => AdminCreateProductTag(
    value: json["value"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (value != null) "value": value!,
    if (metadata != null) "metadata": metadata!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The details of the product type to create.
class AdminCreateProductType {
  AdminCreateProductType({
    this.metadata,
    this.value,
    this.externalId,
  });

  /// The product's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The product type's value.
  final String? value;
  /// The ID of the product type in an external or third-party system.
  final String? externalId;

  factory AdminCreateProductType.fromJson(Map<String, dynamic> json) => AdminCreateProductType(
    metadata: json["metadata"] as Map<String, dynamic>?,
    value: json["value"] as String?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (metadata != null) "metadata": metadata!,
    if (value != null) "value": value!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The product variant's details.
class AdminCreateProductVariant {
  AdminCreateProductVariant({
    this.title,
    this.sku,
    this.ean,
    this.upc,
    this.barcode,
    this.hsCode,
    this.midCode,
    this.allowBackorder,
    this.manageInventory,
    this.variantRank,
    this.weight,
    this.length,
    this.height,
    this.width,
    this.originCountry,
    this.material,
    this.metadata,
    this.prices,
    this.options,
    this.inventoryItems,
  });

  /// The variant's title.
  final String? title;
  /// The variant's SKU.
  final String? sku;
  /// The variant's EAN.
  final String? ean;
  /// The variant's UPC.
  final String? upc;
  /// The variant's barcode.
  final String? barcode;
  /// The variant's HS code.
  final String? hsCode;
  /// The variant's MID code.
  final String? midCode;
  /// Whether it's allowed to order this variant when it's out of stock.
  final bool? allowBackorder;
  /// Whether Medusa manages the variant's inventory quantity. If disabled, the product variant is always considered in stock.
  final bool? manageInventory;
  /// The sorting order of the variant among other variants in the product.
  final num? variantRank;
  /// The variant's weight.
  final num? weight;
  /// The variant's length.
  final num? length;
  /// The variant's height.
  final num? height;
  /// The variant's width.
  final num? width;
  /// The variant's origin country.
  final String? originCountry;
  /// The variant's material.
  final String? material;
  /// The variant's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The variant's prices.
  final List<AdminCreateProductVariantPrice>? prices;
  /// The variant's options, where the key is an option's name, and the value is the option's value.
  final Map<String, dynamic>? options;
  /// The variant's inventory items to create.
  final List<AdminCreateProductVariantInventoryKit>? inventoryItems;

  factory AdminCreateProductVariant.fromJson(Map<String, dynamic> json) => AdminCreateProductVariant(
    title: json["title"] as String?,
    sku: json["sku"] as String?,
    ean: json["ean"] as String?,
    upc: json["upc"] as String?,
    barcode: json["barcode"] as String?,
    hsCode: json["hs_code"] as String?,
    midCode: json["mid_code"] as String?,
    allowBackorder: json["allow_backorder"] as bool?,
    manageInventory: json["manage_inventory"] as bool?,
    variantRank: json["variant_rank"] as num?,
    weight: json["weight"] as num?,
    length: json["length"] as num?,
    height: json["height"] as num?,
    width: json["width"] as num?,
    originCountry: json["origin_country"] as String?,
    material: json["material"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    prices: (json["prices"] as List?)?.map((e) => e == null ? null : AdminCreateProductVariantPrice.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateProductVariantPrice>(),
    options: json["options"] as Map<String, dynamic>?,
    inventoryItems: (json["inventory_items"] as List?)?.map((e) => e == null ? null : AdminCreateProductVariantInventoryKit.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateProductVariantInventoryKit>(),
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (sku != null) "sku": sku!,
    if (ean != null) "ean": ean!,
    if (upc != null) "upc": upc!,
    if (barcode != null) "barcode": barcode!,
    if (hsCode != null) "hs_code": hsCode!,
    if (midCode != null) "mid_code": midCode!,
    if (allowBackorder != null) "allow_backorder": allowBackorder!,
    if (manageInventory != null) "manage_inventory": manageInventory!,
    if (variantRank != null) "variant_rank": variantRank!,
    if (weight != null) "weight": weight!,
    if (length != null) "length": length!,
    if (height != null) "height": height!,
    if (width != null) "width": width!,
    if (originCountry != null) "origin_country": originCountry!,
    if (material != null) "material": material!,
    if (metadata != null) "metadata": metadata!,
    if (prices != null) "prices": prices!.map((e) => e.toJson()).toList(),
    if (options != null) "options": options!,
    if (inventoryItems != null) "inventory_items": inventoryItems!.map((e) => e.toJson()).toList(),
  };
}

/// The details of a variant's inventory item.
class AdminCreateProductVariantInventoryKit {
  AdminCreateProductVariantInventoryKit({
    this.inventoryItemId,
    this.requiredQuantity,
  });

  /// The inventory item's ID.
  final String? inventoryItemId;
  /// The number of units a single quantity is equivalent to. For example, if a customer orders one quantity of the variant, Medusa checks the availability of the qua
  final num? requiredQuantity;

  factory AdminCreateProductVariantInventoryKit.fromJson(Map<String, dynamic> json) => AdminCreateProductVariantInventoryKit(
    inventoryItemId: json["inventory_item_id"] as String?,
    requiredQuantity: json["required_quantity"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (inventoryItemId != null) "inventory_item_id": inventoryItemId!,
    if (requiredQuantity != null) "required_quantity": requiredQuantity!,
  };
}

/// The details of a variant's price.
class AdminCreateProductVariantPrice {
  AdminCreateProductVariantPrice({
    this.currencyCode,
    this.amount,
    this.minQuantity,
    this.maxQuantity,
    this.rules,
  });

  /// The price's currency code.
  final String? currencyCode;
  /// The price's amount.
  final num? amount;
  /// The minimum quantity that must be available in the cart for this price to apply.
  final num? minQuantity;
  /// The maximum quantity that must not be surpassed in the cart for this price to apply.
  final num? maxQuantity;
  /// The price's rules.
  final Map<String, dynamic>? rules;

  factory AdminCreateProductVariantPrice.fromJson(Map<String, dynamic> json) => AdminCreateProductVariantPrice(
    currencyCode: json["currency_code"] as String?,
    amount: json["amount"] as num?,
    minQuantity: json["min_quantity"] as num?,
    maxQuantity: json["max_quantity"] as num?,
    rules: json["rules"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (currencyCode != null) "currency_code": currencyCode!,
    if (amount != null) "amount": amount!,
    if (minQuantity != null) "min_quantity": minQuantity!,
    if (maxQuantity != null) "max_quantity": maxQuantity!,
    if (rules != null) "rules": rules!,
  };
}

/// The promotion rule's details.
class AdminCreatePromotionRule {
  AdminCreatePromotionRule({
    this.operator,
    this.description,
    this.attribute,
    this.values,
  });

  /// The operator used to check whether the buy rule applies on a cart. For example, `eq` means that the cart's value for the specified attribute must match the spec
  final String? operator;
  /// The rule's description.
  final String? description;
  /// The attribute to compare against when checking whether a promotion can be applied on a cart.
  final String? attribute;
  final dynamic values;

  factory AdminCreatePromotionRule.fromJson(Map<String, dynamic> json) => AdminCreatePromotionRule(
    operator: json["operator"] as String?,
    description: json["description"] as String?,
    attribute: json["attribute"] as String?,
    values: json["values"],
  );

  Map<String, dynamic> toJson() => {
    if (operator != null) "operator": operator!,
    if (description != null) "description": description!,
    if (attribute != null) "attribute": attribute!,
    if (values != null) "values": values!,
  };
}

/// The details of a property label to create.
class AdminCreatePropertyLabel {
  AdminCreatePropertyLabel({
    this.entity,
    this.property,
    this.label,
    this.description,
  });

  /// The name of the entity the property label belongs to.
  final String? entity;
  /// The property the label is for.
  final String? property;
  /// The label to use for the property.
  final String? label;
  /// The description of the property label.
  final String? description;

  factory AdminCreatePropertyLabel.fromJson(Map<String, dynamic> json) => AdminCreatePropertyLabel(
    entity: json["entity"] as String?,
    property: json["property"] as String?,
    label: json["label"] as String?,
    description: json["description"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (entity != null) "entity": entity!,
    if (property != null) "property": property!,
    if (label != null) "label": label!,
    if (description != null) "description": description!,
  };
}

/// The refund reason's details.
class AdminCreateRefundReason {
  AdminCreateRefundReason({
    this.label,
    this.description,
    this.code,
  });

  /// The refund reason's label.
  final String? label;
  /// The refund reason's description.
  final String? description;
  /// The refund reason's code.
  final String? code;

  factory AdminCreateRefundReason.fromJson(Map<String, dynamic> json) => AdminCreateRefundReason(
    label: json["label"] as String?,
    description: json["description"] as String?,
    code: json["code"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (label != null) "label": label!,
    if (description != null) "description": description!,
    if (code != null) "code": code!,
  };
}

/// The region's details.
class AdminCreateRegion {
  AdminCreateRegion({
    this.name,
    this.currencyCode,
    this.countries,
    this.automaticTaxes,
    this.isTaxInclusive,
    this.paymentProviders,
    this.metadata,
  });

  /// The region's name.
  final String? name;
  /// The region's currency code.
  final String? currencyCode;
  /// The region's countries.
  final List<String>? countries;
  /// Whether taxes are calculated automatically during checkout in this region.
  final bool? automaticTaxes;
  /// Whether prices in this region are tax inclusive.
  final bool? isTaxInclusive;
  /// The payment providers enabled in this region.
  final List<String>? paymentProviders;
  /// The region's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateRegion.fromJson(Map<String, dynamic> json) => AdminCreateRegion(
    name: json["name"] as String?,
    currencyCode: json["currency_code"] as String?,
    countries: (json["countries"] as List?)?.map((e) => e as String?).toList().cast<String>(),
    automaticTaxes: json["automatic_taxes"] as bool?,
    isTaxInclusive: json["is_tax_inclusive"] as bool?,
    paymentProviders: (json["payment_providers"] as List?)?.map((e) => e as String?).toList().cast<String>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (countries != null) "countries": countries!.map((e) => e).toList(),
    if (automaticTaxes != null) "automatic_taxes": automaticTaxes!,
    if (isTaxInclusive != null) "is_tax_inclusive": isTaxInclusive!,
    if (paymentProviders != null) "payment_providers": paymentProviders!.map((e) => e).toList(),
    if (metadata != null) "metadata": metadata!,
  };
}

/// The reservation's details.
class AdminCreateReservation {
  AdminCreateReservation({
    this.lineItemId,
    this.locationId,
    this.inventoryItemId,
    this.quantity,
    this.description,
    this.metadata,
  });

  /// The ID of the line item this reservation is created for.
  final String? lineItemId;
  /// The ID of the location the quantity is reserved from.
  final String? locationId;
  /// The ID of the inventory item associated with the line item's variant.
  final String? inventoryItemId;
  /// The reserved quantity.
  final num? quantity;
  /// The reservation's description.
  final String? description;
  /// The reservation's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateReservation.fromJson(Map<String, dynamic> json) => AdminCreateReservation(
    lineItemId: json["line_item_id"] as String?,
    locationId: json["location_id"] as String?,
    inventoryItemId: json["inventory_item_id"] as String?,
    quantity: json["quantity"] as num?,
    description: json["description"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (lineItemId != null) "line_item_id": lineItemId!,
    if (locationId != null) "location_id": locationId!,
    if (inventoryItemId != null) "inventory_item_id": inventoryItemId!,
    if (quantity != null) "quantity": quantity!,
    if (description != null) "description": description!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of the return reason to create.
class AdminCreateReturnReason {
  AdminCreateReturnReason({
    this.value,
    this.label,
    this.description,
    this.parentReturnReasonId,
    this.metadata,
  });

  /// The return reason's value.
  final String? value;
  /// The return reason's label.
  final String? label;
  /// The return reason's description.
  final String? description;
  /// The ID of the parent return reason.
  final String? parentReturnReasonId;
  /// The return reason's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateReturnReason.fromJson(Map<String, dynamic> json) => AdminCreateReturnReason(
    value: json["value"] as String?,
    label: json["label"] as String?,
    description: json["description"] as String?,
    parentReturnReasonId: json["parent_return_reason_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (value != null) "value": value!,
    if (label != null) "label": label!,
    if (description != null) "description": description!,
    if (parentReturnReasonId != null) "parent_return_reason_id": parentReturnReasonId!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The sales channel's details.
class AdminCreateSalesChannel {
  AdminCreateSalesChannel({
    this.name,
    this.description,
    this.isDisabled,
    this.metadata,
  });

  /// The sales channel's name.
  final String? name;
  /// The sales channel's description.
  final String? description;
  /// Whether the sales channel is disabled.
  final bool? isDisabled;
  /// The sales channel's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateSalesChannel.fromJson(Map<String, dynamic> json) => AdminCreateSalesChannel(
    name: json["name"] as String?,
    description: json["description"] as String?,
    isDisabled: json["is_disabled"] as bool?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (description != null) "description": description!,
    if (isDisabled != null) "is_disabled": isDisabled!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of the shipping option rule.
class AdminCreateShippingOptionRule {
  AdminCreateShippingOptionRule({
    this.operator,
    this.attribute,
    this.value,
  });

  /// The operator used to check whether a rule applies.
  final String? operator;
  /// The name of a property or table that the rule applies to.
  final String? attribute;
  final dynamic value;

  factory AdminCreateShippingOptionRule.fromJson(Map<String, dynamic> json) => AdminCreateShippingOptionRule(
    operator: json["operator"] as String?,
    attribute: json["attribute"] as String?,
    value: json["value"],
  );

  Map<String, dynamic> toJson() => {
    if (operator != null) "operator": operator!,
    if (attribute != null) "attribute": attribute!,
    if (value != null) "value": value!,
  };
}

/// The shipping option type's details.
class AdminCreateShippingOptionType {
  AdminCreateShippingOptionType({
    this.label,
    this.description,
    this.code,
  });

  /// The type's label.
  final String? label;
  /// The type's description.
  final String? description;
  /// The type's code.
  final String? code;

  factory AdminCreateShippingOptionType.fromJson(Map<String, dynamic> json) => AdminCreateShippingOptionType(
    label: json["label"] as String?,
    description: json["description"] as String?,
    code: json["code"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (label != null) "label": label!,
    if (description != null) "description": description!,
    if (code != null) "code": code!,
  };
}

/// The shipping profile's details.
class AdminCreateShippingProfile {
  AdminCreateShippingProfile({
    this.name,
    this.type,
    this.metadata,
  });

  /// The shipping profile's name.
  final String? name;
  /// The shipping profile's type.
  final String? type;
  /// The shipping profile's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateShippingProfile.fromJson(Map<String, dynamic> json) => AdminCreateShippingProfile(
    name: json["name"] as String?,
    type: json["type"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (type != null) "type": type!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The stock location's details.
class AdminCreateStockLocation {
  AdminCreateStockLocation({
    this.name,
    this.addressId,
    this.address,
    this.metadata,
  });

  /// The stock location's name.
  final String? name;
  /// The ID of the stock location's address.
  final String? addressId;
  final AdminUpsertStockLocationAddress? address;
  /// The stock location's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateStockLocation.fromJson(Map<String, dynamic> json) => AdminCreateStockLocation(
    name: json["name"] as String?,
    addressId: json["address_id"] as String?,
    address: json["address"] == null ? null : AdminUpsertStockLocationAddress.fromJson(json["address"] as Map<String, dynamic>),
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (addressId != null) "address_id": addressId!,
    if (address != null) "address": address!.toJson(),
    if (metadata != null) "metadata": metadata!,
  };
}

/// The fulfillment set to create.
class AdminCreateStockLocationFulfillmentSet {
  AdminCreateStockLocationFulfillmentSet({
    this.name,
    this.type,
  });

  /// The fulfillment set's name.
  final String? name;
  /// The fulfillment set's type.
  final String? type;

  factory AdminCreateStockLocationFulfillmentSet.fromJson(Map<String, dynamic> json) => AdminCreateStockLocationFulfillmentSet(
    name: json["name"] as String?,
    type: json["type"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (type != null) "type": type!,
  };
}

/// The details of the store credit account to create.
class AdminCreateStoreCreditAccount {
  AdminCreateStoreCreditAccount({
    this.currencyCode,
    this.customerId,
    this.metadata,
  });

  /// The store credit account's currency code.
  final String? currencyCode;
  /// The ID of the customer that the store credit account belongs to.
  final String? customerId;
  /// The store credit account's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateStoreCreditAccount.fromJson(Map<String, dynamic> json) => AdminCreateStoreCreditAccount(
    currencyCode: json["currency_code"] as String?,
    customerId: json["customer_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (currencyCode != null) "currency_code": currencyCode!,
    if (customerId != null) "customer_id": customerId!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The tax rate's details.
class AdminCreateTaxRate {
  AdminCreateTaxRate({
    this.name,
    this.taxRegionId,
    this.rate,
    this.code,
    this.rules,
    this.isDefault,
    this.isCombinable,
    this.metadata,
  });

  /// The tax rate's name.
  final String? name;
  /// The ID of the tax region this rate belongs to.
  final String? taxRegionId;
  /// The rate to charge.
  final num? rate;
  /// The code the tax rate is identified by.
  final String? code;
  /// The tax rate's rules.
  final List<AdminCreateTaxRateRule>? rules;
  /// Whether the tax rate is the default in its tax region.
  final bool? isDefault;
  /// Whether the tax rate should be combined with parent rates.
  final bool? isCombinable;
  /// The tax rate's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminCreateTaxRate.fromJson(Map<String, dynamic> json) => AdminCreateTaxRate(
    name: json["name"] as String?,
    taxRegionId: json["tax_region_id"] as String?,
    rate: json["rate"] as num?,
    code: json["code"] as String?,
    rules: (json["rules"] as List?)?.map((e) => e == null ? null : AdminCreateTaxRateRule.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateTaxRateRule>(),
    isDefault: json["is_default"] as bool?,
    isCombinable: json["is_combinable"] as bool?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (taxRegionId != null) "tax_region_id": taxRegionId!,
    if (rate != null) "rate": rate!,
    if (code != null) "code": code!,
    if (rules != null) "rules": rules!.map((e) => e.toJson()).toList(),
    if (isDefault != null) "is_default": isDefault!,
    if (isCombinable != null) "is_combinable": isCombinable!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The tax rate rule's details.
class AdminCreateTaxRateRule {
  AdminCreateTaxRateRule({
    this.reference,
    this.referenceId,
  });

  /// The name of a table in the database that this rule points to.
  final String? reference;
  /// The ID of a record in the table specified in reference.
  final String? referenceId;

  factory AdminCreateTaxRateRule.fromJson(Map<String, dynamic> json) => AdminCreateTaxRateRule(
    reference: json["reference"] as String?,
    referenceId: json["reference_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (reference != null) "reference": reference!,
    if (referenceId != null) "reference_id": referenceId!,
  };
}

/// The tax region's details.
class AdminCreateTaxRegion {
  AdminCreateTaxRegion({
    this.countryCode,
    this.provinceCode,
    this.parentId,
    this.defaultTaxRate,
    this.metadata,
    this.providerId,
  });

  /// The tax region's country code.
  final String? countryCode;
  /// The tax region's ISO 3166-2 province code. Must be lower-case.
  final String? provinceCode;
  /// The ID of the parent tax region.
  final String? parentId;
  /// The tax region's default tax rate.
  final Map<String, dynamic>? defaultTaxRate;
  /// The tax region's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the tax provider used to calculate the tax rate in this tax region.
  final String? providerId;

  factory AdminCreateTaxRegion.fromJson(Map<String, dynamic> json) => AdminCreateTaxRegion(
    countryCode: json["country_code"] as String?,
    provinceCode: json["province_code"] as String?,
    parentId: json["parent_id"] as String?,
    defaultTaxRate: json["default_tax_rate"] as Map<String, dynamic>?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    providerId: json["provider_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (countryCode != null) "country_code": countryCode!,
    if (provinceCode != null) "province_code": provinceCode!,
    if (parentId != null) "parent_id": parentId!,
    if (defaultTaxRate != null) "default_tax_rate": defaultTaxRate!,
    if (metadata != null) "metadata": metadata!,
    if (providerId != null) "provider_id": providerId!,
  };
}

/// The translation's details.
class AdminCreateTranslation {
  AdminCreateTranslation({
    this.reference,
    this.referenceId,
    this.localeCode,
    this.translations,
  });

  /// The resource that the translation belongs to.
  final String? reference;
  /// The ID of the resource that the translation belongs to. For example, the ID of a product.
  final String? referenceId;
  /// The translation's locale code in BCP 47 format.
  final String? localeCode;
  /// The translation key-value pairs. Each key is a field in the resource, and the value is the translated text.
  final Map<String, dynamic>? translations;

  factory AdminCreateTranslation.fromJson(Map<String, dynamic> json) => AdminCreateTranslation(
    reference: json["reference"] as String?,
    referenceId: json["reference_id"] as String?,
    localeCode: json["locale_code"] as String?,
    translations: json["translations"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (reference != null) "reference": reference!,
    if (referenceId != null) "reference_id": referenceId!,
    if (localeCode != null) "locale_code": localeCode!,
    if (translations != null) "translations": translations!,
  };
}

/// The translation settings to create.
class AdminCreateTranslationSettings {
  AdminCreateTranslationSettings({
    this.entityType,
    this.fields,
    this.isActive,
  });

  /// The entity type to create the translation settings for.
  final String? entityType;
  /// The fields to support translations for.
  final List<String>? fields;
  /// Whether translations are active for the given entity type.
  final bool? isActive;

  factory AdminCreateTranslationSettings.fromJson(Map<String, dynamic> json) => AdminCreateTranslationSettings(
    entityType: json["entity_type"] as String?,
    fields: (json["fields"] as List?)?.map((e) => e as String?).toList().cast<String>(),
    isActive: json["is_active"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (entityType != null) "entity_type": entityType!,
    if (fields != null) "fields": fields!.map((e) => e).toList(),
    if (isActive != null) "is_active": isActive!,
  };
}

/// The details of the variant-inventory item association.
class AdminCreateVariantInventoryItem {
  AdminCreateVariantInventoryItem({
    this.requiredQuantity,
    this.inventoryItemId,
  });

  /// The quantity of the variant in the inventory item.
  final num? requiredQuantity;
  /// The inventory item's ID.
  final String? inventoryItemId;

  factory AdminCreateVariantInventoryItem.fromJson(Map<String, dynamic> json) => AdminCreateVariantInventoryItem(
    requiredQuantity: json["required_quantity"] as num?,
    inventoryItemId: json["inventory_item_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (requiredQuantity != null) "required_quantity": requiredQuantity!,
    if (inventoryItemId != null) "inventory_item_id": inventoryItemId!,
  };
}

/// The details of a view configuration to create.
class AdminCreateViewConfiguration {
  AdminCreateViewConfiguration({
    this.isSystemDefault,
    this.setActive,
    this.configuration,
    this.name,
  });

  /// Whether the view is the system default. If so, it will be used as the default view for all users that don't have a custom active view set.
  final bool? isSystemDefault;
  /// Whether the view is set as active.
  final bool? setActive;
  /// The view's configuration.
  final Map<String, dynamic>? configuration;
  /// The view's name.
  final String? name;

  factory AdminCreateViewConfiguration.fromJson(Map<String, dynamic> json) => AdminCreateViewConfiguration(
    isSystemDefault: json["is_system_default"] as bool?,
    setActive: json["set_active"] as bool?,
    configuration: json["configuration"] as Map<String, dynamic>?,
    name: json["name"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (isSystemDefault != null) "is_system_default": isSystemDefault!,
    if (setActive != null) "set_active": setActive!,
    if (configuration != null) "configuration": configuration!,
    if (name != null) "name": name!,
  };
}

/// The details of changing a workflow execution's step status.
class AdminCreateWorkflowsAsyncResponse {
  AdminCreateWorkflowsAsyncResponse({
    this.transactionId,
    this.stepId,
    this.response,
    this.compensateInput,
    this.action,
  });

  /// The workflows execution's transaction ID.
  final String? transactionId;
  /// The ID of the step whose status was changed.
  final String? stepId;
  /// Sets the step's response. It accepts any type.
  final dynamic response;
  /// Sets the compensation function's input. It accepts any response.
  final dynamic compensateInput;
  /// Whether to invoke or compensate the step.
  final String? action;

  factory AdminCreateWorkflowsAsyncResponse.fromJson(Map<String, dynamic> json) => AdminCreateWorkflowsAsyncResponse(
    transactionId: json["transaction_id"] as String?,
    stepId: json["step_id"] as String?,
    response: json["response"],
    compensateInput: json["compensate_input"],
    action: json["action"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (transactionId != null) "transaction_id": transactionId!,
    if (stepId != null) "step_id": stepId!,
    if (response != null) "response": response!,
    if (compensateInput != null) "compensate_input": compensateInput!,
    if (action != null) "action": action!,
  };
}

/// The details of the workflow to execute.
class AdminCreateWorkflowsRun {
  AdminCreateWorkflowsRun({
    this.input,
    this.transactionId,
  });

  /// The input to pass to the workflow. Can be of any type.
  final dynamic input;
  /// The ID of the workflow execution's transaction.
  final String? transactionId;

  factory AdminCreateWorkflowsRun.fromJson(Map<String, dynamic> json) => AdminCreateWorkflowsRun(
    input: json["input"],
    transactionId: json["transaction_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (input != null) "input": input!,
    if (transactionId != null) "transaction_id": transactionId!,
  };
}

/// The details of crediting a store credit account.
class AdminCreditStoreCreditAccountParams {
  AdminCreditStoreCreditAccountParams({
    this.amount,
    this.note,
  });

  /// The amount to credit the store credit account with.
  final num? amount;
  /// An additional note to add to the store credit transaction.
  final String? note;

  factory AdminCreditStoreCreditAccountParams.fromJson(Map<String, dynamic> json) => AdminCreditStoreCreditAccountParams(
    amount: json["amount"] as num?,
    note: json["note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (amount != null) "amount": amount!,
    if (note != null) "note": note!,
  };
}

/// The currency's currencies.
class AdminCurrency {
  AdminCurrency({
    this.code,
    this.symbol,
    this.symbolNative,
    this.name,
    this.decimalDigits,
    this.rounding,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The currency's code.
  final String? code;
  /// The currency's symbol.
  final String? symbol;
  /// The currency's native symbol, if different than the symbol.
  final String? symbolNative;
  /// The currency's name.
  final String? name;
  /// The number of digits after the decimal for prices in this currency.
  final num? decimalDigits;
  /// The rounding percision applied on prices in this currency.
  final num? rounding;
  /// The currency's creation date.
  final DateTime? createdAt;
  /// The currency's update date.
  final DateTime? updatedAt;
  /// The currency's deletion date.
  final DateTime? deletedAt;

  factory AdminCurrency.fromJson(Map<String, dynamic> json) => AdminCurrency(
    code: json["code"] as String?,
    symbol: json["symbol"] as String?,
    symbolNative: json["symbol_native"] as String?,
    name: json["name"] as String?,
    decimalDigits: json["decimal_digits"] as num?,
    rounding: json["rounding"] as num?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (code != null) "code": code!,
    if (symbol != null) "symbol": symbol!,
    if (symbolNative != null) "symbol_native": symbolNative!,
    if (name != null) "name": name!,
    if (decimalDigits != null) "decimal_digits": decimalDigits!,
    if (rounding != null) "rounding": rounding!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The paginated list of currencies.
class AdminCurrencyListResponse {
  AdminCurrencyListResponse({
    this.limit,
    this.offset,
    this.count,
    this.currencies,
    this.estimateCount,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The total number of items.
  final num? count;
  /// The list of currencies.
  final List<AdminCurrency>? currencies;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory AdminCurrencyListResponse.fromJson(Map<String, dynamic> json) => AdminCurrencyListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    currencies: (json["currencies"] as List?)?.map((e) => e == null ? null : AdminCurrency.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCurrency>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (currencies != null) "currencies": currencies!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The currency's details.
class AdminCurrencyResponse {
  AdminCurrencyResponse({
    this.currency,
  });

  final AdminCurrency? currency;

  factory AdminCurrencyResponse.fromJson(Map<String, dynamic> json) => AdminCurrencyResponse(
    currency: json["currency"] == null ? null : AdminCurrency.fromJson(json["currency"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (currency != null) "currency": currency!.toJson(),
  };
}

/// The customer's details.
class AdminCustomer {
  AdminCustomer({
    this.id,
    this.hasAccount,
    this.groups,
    this.email,
    this.defaultBillingAddressId,
    this.defaultShippingAddressId,
    this.companyName,
    this.firstName,
    this.lastName,
    this.addresses,
    this.phone,
    this.metadata,
    this.createdBy,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The customer's ID.
  final String? id;
  /// Whether the customer is registered.
  final bool? hasAccount;
  /// The customer's groups.
  final List<AdminCustomerGroup>? groups;
  /// The customer's email.
  final String? email;
  /// The ID of the address used as the default billing address.
  final String? defaultBillingAddressId;
  /// The ID of the address used as the default shipping address.
  final String? defaultShippingAddressId;
  /// The customer's company name.
  final String? companyName;
  /// The customer's first name.
  final String? firstName;
  /// The customer's last name.
  final String? lastName;
  /// The customer's addresses.
  final List<AdminCustomerAddress>? addresses;
  /// The customer's phone.
  final String? phone;
  /// The customer's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the user that created this customer, if available.
  final String? createdBy;
  /// The customer's creation date.
  final DateTime? createdAt;
  /// The customer's update date.
  final DateTime? updatedAt;
  /// The customer's deletion date.
  final DateTime? deletedAt;

  factory AdminCustomer.fromJson(Map<String, dynamic> json) => AdminCustomer(
    id: json["id"] as String?,
    hasAccount: json["has_account"] as bool?,
    groups: (json["groups"] as List?)?.map((e) => e == null ? null : AdminCustomerGroup.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCustomerGroup>(),
    email: json["email"] as String?,
    defaultBillingAddressId: json["default_billing_address_id"] as String?,
    defaultShippingAddressId: json["default_shipping_address_id"] as String?,
    companyName: json["company_name"] as String?,
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    addresses: (json["addresses"] as List?)?.map((e) => e == null ? null : AdminCustomerAddress.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCustomerAddress>(),
    phone: json["phone"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdBy: json["created_by"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (hasAccount != null) "has_account": hasAccount!,
    if (groups != null) "groups": groups!.map((e) => e.toJson()).toList(),
    if (email != null) "email": email!,
    if (defaultBillingAddressId != null) "default_billing_address_id": defaultBillingAddressId!,
    if (defaultShippingAddressId != null) "default_shipping_address_id": defaultShippingAddressId!,
    if (companyName != null) "company_name": companyName!,
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (addresses != null) "addresses": addresses!.map((e) => e.toJson()).toList(),
    if (phone != null) "phone": phone!,
    if (metadata != null) "metadata": metadata!,
    if (createdBy != null) "created_by": createdBy!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The customer's address.
class AdminCustomerAddress {
  AdminCustomerAddress({
    this.id,
    this.addressName,
    this.isDefaultShipping,
    this.isDefaultBilling,
    this.customerId,
    this.company,
    this.firstName,
    this.lastName,
    this.address1,
    this.address2,
    this.city,
    this.countryCode,
    this.province,
    this.postalCode,
    this.phone,
    this.metadata,
    this.createdAt,
    this.updatedAt,
  });

  /// The address's ID.
  final String? id;
  /// The address's name.
  final String? addressName;
  /// Whether the address is the default shipping address.
  final bool? isDefaultShipping;
  /// Whether the address is the default billing address.
  final bool? isDefaultBilling;
  /// The ID of the customer that this address belongs to.
  final String? customerId;
  /// The customer's company.
  final String? company;
  /// The customer's first name.
  final String? firstName;
  /// The customer's last name.
  final String? lastName;
  /// The address's first line.
  final String? address1;
  /// The address's second line.
  final String? address2;
  /// The address's city.
  final String? city;
  /// The address's country code.
  final String? countryCode;
  /// The address's lower-case ISO 3166-2 province code.
  final String? province;
  /// The address's postal code.
  final String? postalCode;
  /// The address's phone.
  final String? phone;
  /// The address's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The address's creation date.
  final DateTime? createdAt;
  /// The address's update date.
  final DateTime? updatedAt;

  factory AdminCustomerAddress.fromJson(Map<String, dynamic> json) => AdminCustomerAddress(
    id: json["id"] as String?,
    addressName: json["address_name"] as String?,
    isDefaultShipping: json["is_default_shipping"] as bool?,
    isDefaultBilling: json["is_default_billing"] as bool?,
    customerId: json["customer_id"] as String?,
    company: json["company"] as String?,
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    address1: json["address_1"] as String?,
    address2: json["address_2"] as String?,
    city: json["city"] as String?,
    countryCode: json["country_code"] as String?,
    province: json["province"] as String?,
    postalCode: json["postal_code"] as String?,
    phone: json["phone"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (addressName != null) "address_name": addressName!,
    if (isDefaultShipping != null) "is_default_shipping": isDefaultShipping!,
    if (isDefaultBilling != null) "is_default_billing": isDefaultBilling!,
    if (customerId != null) "customer_id": customerId!,
    if (company != null) "company": company!,
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (address1 != null) "address_1": address1!,
    if (address2 != null) "address_2": address2!,
    if (city != null) "city": city!,
    if (countryCode != null) "country_code": countryCode!,
    if (province != null) "province": province!,
    if (postalCode != null) "postal_code": postalCode!,
    if (phone != null) "phone": phone!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
  };
}

/// The address's details.
class AdminCustomerAddressResponse {
  AdminCustomerAddressResponse({
    this.address,
  });

  final AdminCustomerAddress? address;

  factory AdminCustomerAddressResponse.fromJson(Map<String, dynamic> json) => AdminCustomerAddressResponse(
    address: json["address"] == null ? null : AdminCustomerAddress.fromJson(json["address"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (address != null) "address": address!.toJson(),
  };
}

/// The customer group's details.
class AdminCustomerGroup {
  AdminCustomerGroup({
    this.id,
    this.name,
    this.customers,
    this.metadata,
    this.createdAt,
    this.updatedAt,
  });

  /// The customer group's ID.
  final String? id;
  /// The customer group's name.
  final String? name;
  /// The customer group's customers.
  final List<Map<String, dynamic>>? customers;
  /// The customer group's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The customer group's creation date.
  final DateTime? createdAt;
  /// The customer group's update date.
  final DateTime? updatedAt;

  factory AdminCustomerGroup.fromJson(Map<String, dynamic> json) => AdminCustomerGroup(
    id: json["id"] as String?,
    name: json["name"] as String?,
    customers: (json["customers"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (name != null) "name": name!,
    if (customers != null) "customers": customers!.map((e) => e).toList(),
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
  };
}

/// The customer group's details.
class AdminCustomerGroupResponse {
  AdminCustomerGroupResponse({
    this.customerGroup,
  });

  final AdminCustomerGroup? customerGroup;

  factory AdminCustomerGroupResponse.fromJson(Map<String, dynamic> json) => AdminCustomerGroupResponse(
    customerGroup: json["customer_group"] == null ? null : AdminCustomerGroup.fromJson(json["customer_group"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (customerGroup != null) "customer_group": customerGroup!.toJson(),
  };
}

/// Filters to apply on customers to retrieve their groups.
class AdminCustomerInGroupFilters {
  AdminCustomerInGroupFilters({
    this.id,
    this.email,
    this.defaultBillingAddressId,
    this.defaultShippingAddressId,
    this.companyName,
    this.firstName,
    this.lastName,
    this.createdBy,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  final dynamic id;
  final dynamic email;
  final dynamic defaultBillingAddressId;
  final dynamic defaultShippingAddressId;
  final dynamic companyName;
  final dynamic firstName;
  final dynamic lastName;
  final dynamic createdBy;
  /// Filter the customer's creation date.
  final Map<String, dynamic>? createdAt;
  /// Filter the customer's update date.
  final Map<String, dynamic>? updatedAt;
  /// Filter the customer's deletion date.
  final Map<String, dynamic>? deletedAt;

  factory AdminCustomerInGroupFilters.fromJson(Map<String, dynamic> json) => AdminCustomerInGroupFilters(
    id: json["id"],
    email: json["email"],
    defaultBillingAddressId: json["default_billing_address_id"],
    defaultShippingAddressId: json["default_shipping_address_id"],
    companyName: json["company_name"],
    firstName: json["first_name"],
    lastName: json["last_name"],
    createdBy: json["created_by"],
    createdAt: json["created_at"] as Map<String, dynamic>?,
    updatedAt: json["updated_at"] as Map<String, dynamic>?,
    deletedAt: json["deleted_at"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (email != null) "email": email!,
    if (defaultBillingAddressId != null) "default_billing_address_id": defaultBillingAddressId!,
    if (defaultShippingAddressId != null) "default_shipping_address_id": defaultShippingAddressId!,
    if (companyName != null) "company_name": companyName!,
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (createdBy != null) "created_by": createdBy!,
    if (createdAt != null) "created_at": createdAt!,
    if (updatedAt != null) "updated_at": updatedAt!,
    if (deletedAt != null) "deleted_at": deletedAt!,
  };
}

/// The customer's details.
class AdminCustomerResponse {
  AdminCustomerResponse({
    this.customer,
  });

  final AdminCustomer? customer;

  factory AdminCustomerResponse.fromJson(Map<String, dynamic> json) => AdminCustomerResponse(
    customer: json["customer"] == null ? null : AdminCustomer.fromJson(json["customer"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (customer != null) "customer": customer!.toJson(),
  };
}

/// The result of deleting the payment collection.
class AdminDeletePaymentCollectionResponse {
  AdminDeletePaymentCollectionResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The payment collection's ID.
  final String? id;
  /// The name of the object that was deleted.
  final String? object;
  /// Whether the object was deleted.
  final bool? deleted;

  factory AdminDeletePaymentCollectionResponse.fromJson(Map<String, dynamic> json) => AdminDeletePaymentCollectionResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}
