// GENERATED by tool/generate_models.mjs — do not edit.
part of '../models.dart';

/// The items details.
class AdminDismissItems {
  AdminDismissItems({
    this.items,
  });

  /// The items details.
  final List<Map<String, dynamic>>? items;

  factory AdminDismissItems.fromJson(Map<String, dynamic> json) => AdminDismissItems(
    items: (json["items"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
  );

  Map<String, dynamic> toJson() => {
    if (items != null) "items": items!.map((e) => e).toList(),
  };
}

/// The draft order's details.
class AdminDraftOrder {
  AdminDraftOrder({
    this.paymentCollections,
    this.fulfillments,
    this.salesChannel,
    this.customer,
    this.shippingAddress,
    this.billingAddress,
    this.items,
    this.shippingMethods,
    this.status,
    this.currencyCode,
    this.id,
    this.version,
    this.regionId,
    this.customerId,
    this.salesChannelId,
    this.email,
    this.displayId,
    this.paymentStatus,
    this.fulfillmentStatus,
    this.transactions,
    this.summary,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.originalItemTotal,
    this.originalItemSubtotal,
    this.originalItemTaxTotal,
    this.itemTotal,
    this.itemSubtotal,
    this.itemTaxTotal,
    this.originalTotal,
    this.originalSubtotal,
    this.originalTaxTotal,
    this.total,
    this.subtotal,
    this.taxTotal,
    this.discountTotal,
    this.discountTaxTotal,
    this.giftCardTotal,
    this.giftCardTaxTotal,
    this.shippingTotal,
    this.shippingSubtotal,
    this.shippingTaxTotal,
    this.originalShippingTotal,
    this.originalShippingSubtotal,
    this.originalShippingTaxTotal,
    this.region,
    this.creditLines,
    this.creditLineTotal,
    this.itemDiscountTotal,
    this.shippingDiscountTotal,
    this.customDisplayId,
  });

  /// The draft order's payment collections.
  final List<AdminPaymentCollection>? paymentCollections;
  /// The draft order's fulfillments.
  final List<AdminOrderFulfillment>? fulfillments;
  final AdminSalesChannel? salesChannel;
  final AdminCustomer? customer;
  final AdminOrderAddress? shippingAddress;
  final AdminOrderAddress? billingAddress;
  /// The draft order's items.
  final List<AdminOrderLineItem>? items;
  /// The draft order's shipping methods.
  final List<AdminOrderShippingMethod>? shippingMethods;
  /// The draft order's status.
  final String? status;
  /// The draft order's currency code.
  final String? currencyCode;
  /// The draft order's ID.
  final String? id;
  /// The draft order's version.
  final num? version;
  /// The ID of the region associated with the draft order.
  final String? regionId;
  /// The ID of the customer that the draft order belongs to.
  final String? customerId;
  /// The ID of the sales channel that the draft order is placed in.
  final String? salesChannelId;
  /// The customer email associated with the draft order.
  final String? email;
  /// The draft order's display ID.
  final num? displayId;
  /// The draft order's payment status.
  final String? paymentStatus;
  /// The draft order's fulfillment status.
  final String? fulfillmentStatus;
  /// The draft order's transactions.
  final List<BaseOrderTransaction>? transactions;
  final BaseOrderSummary? summary;
  /// The draft order's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the draft order was created.
  final DateTime? createdAt;
  /// The date the draft order was updated.
  final DateTime? updatedAt;
  /// The total of the draft order's items including taxes, excluding promotions.
  final num? originalItemTotal;
  /// The total of the draft order's items excluding taxes, including promotions.
  final num? originalItemSubtotal;
  /// The tax total of the draft order's items excluding promotions.
  final num? originalItemTaxTotal;
  /// The total of the draft order's items including taxes and promotions.
  final num? itemTotal;
  /// The total of the draft order's items excluding taxes, including promotions.
  final num? itemSubtotal;
  /// The tax total of the draft order's items including promotions.
  final num? itemTaxTotal;
  /// The draft order's total excluding promotions, including taxes.
  final num? originalTotal;
  /// The draft order's total excluding taxes, including promotions.
  final num? originalSubtotal;
  /// The draft order's tax total, excluding promotions.
  final num? originalTaxTotal;
  /// The draft order's total including taxes and promotions.
  final num? total;
  /// The draft order's total excluding taxes, including promotions.
  final num? subtotal;
  /// The draft order's tax total including promotions.
  final num? taxTotal;
  /// The draft order's discount or promotions total.
  final num? discountTotal;
  /// The tax total of draft order's discount or promotion.
  final num? discountTaxTotal;
  /// The draft order's gift card total.
  final num? giftCardTotal;
  /// The tax total of the draft order's gift card.
  final num? giftCardTaxTotal;
  /// The draft order's shipping total including taxes and promotions.
  final num? shippingTotal;
  /// The draft order's shipping total excluding taxes, including promotions.
  final num? shippingSubtotal;
  /// The tax total of the draft order's shipping.
  final num? shippingTaxTotal;
  /// The draft order's shipping total including taxes, excluding promotions.
  final num? originalShippingTotal;
  /// The draft order's shipping total excluding taxes, including promotions.
  final num? originalShippingSubtotal;
  /// The tax total of the draft order's shipping excluding promotions.
  final num? originalShippingTaxTotal;
  final AdminRegion? region;
  /// The draft order's credit lines.
  final List<OrderCreditLine>? creditLines;
  /// The draft order's credit line total.
  final num? creditLineTotal;
  /// The total discount amount applied on the draft order's items.
  final num? itemDiscountTotal;
  /// The total discount amount applied on the draft order's shipping.
  final num? shippingDiscountTotal;
  /// The custom display ID of the draft order.
  final String? customDisplayId;

  factory AdminDraftOrder.fromJson(Map<String, dynamic> json) => AdminDraftOrder(
    paymentCollections: (json["payment_collections"] as List?)?.map((e) => e == null ? null : AdminPaymentCollection.fromJson(e as Map<String, dynamic>)).toList().cast<AdminPaymentCollection>(),
    fulfillments: (json["fulfillments"] as List?)?.map((e) => e == null ? null : AdminOrderFulfillment.fromJson(e as Map<String, dynamic>)).toList().cast<AdminOrderFulfillment>(),
    salesChannel: json["sales_channel"] == null ? null : AdminSalesChannel.fromJson(json["sales_channel"] as Map<String, dynamic>),
    customer: json["customer"] == null ? null : AdminCustomer.fromJson(json["customer"] as Map<String, dynamic>),
    shippingAddress: json["shipping_address"] == null ? null : AdminOrderAddress.fromJson(json["shipping_address"] as Map<String, dynamic>),
    billingAddress: json["billing_address"] == null ? null : AdminOrderAddress.fromJson(json["billing_address"] as Map<String, dynamic>),
    items: (json["items"] as List?)?.map((e) => e == null ? null : AdminOrderLineItem.fromJson(e as Map<String, dynamic>)).toList().cast<AdminOrderLineItem>(),
    shippingMethods: (json["shipping_methods"] as List?)?.map((e) => e == null ? null : AdminOrderShippingMethod.fromJson(e as Map<String, dynamic>)).toList().cast<AdminOrderShippingMethod>(),
    status: json["status"] as String?,
    currencyCode: json["currency_code"] as String?,
    id: json["id"] as String?,
    version: json["version"] as num?,
    regionId: json["region_id"] as String?,
    customerId: json["customer_id"] as String?,
    salesChannelId: json["sales_channel_id"] as String?,
    email: json["email"] as String?,
    displayId: json["display_id"] as num?,
    paymentStatus: json["payment_status"] as String?,
    fulfillmentStatus: json["fulfillment_status"] as String?,
    transactions: (json["transactions"] as List?)?.map((e) => e == null ? null : BaseOrderTransaction.fromJson(e as Map<String, dynamic>)).toList().cast<BaseOrderTransaction>(),
    summary: json["summary"] == null ? null : BaseOrderSummary.fromJson(json["summary"] as Map<String, dynamic>),
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    originalItemTotal: json["original_item_total"] as num?,
    originalItemSubtotal: json["original_item_subtotal"] as num?,
    originalItemTaxTotal: json["original_item_tax_total"] as num?,
    itemTotal: json["item_total"] as num?,
    itemSubtotal: json["item_subtotal"] as num?,
    itemTaxTotal: json["item_tax_total"] as num?,
    originalTotal: json["original_total"] as num?,
    originalSubtotal: json["original_subtotal"] as num?,
    originalTaxTotal: json["original_tax_total"] as num?,
    total: json["total"] as num?,
    subtotal: json["subtotal"] as num?,
    taxTotal: json["tax_total"] as num?,
    discountTotal: json["discount_total"] as num?,
    discountTaxTotal: json["discount_tax_total"] as num?,
    giftCardTotal: json["gift_card_total"] as num?,
    giftCardTaxTotal: json["gift_card_tax_total"] as num?,
    shippingTotal: json["shipping_total"] as num?,
    shippingSubtotal: json["shipping_subtotal"] as num?,
    shippingTaxTotal: json["shipping_tax_total"] as num?,
    originalShippingTotal: json["original_shipping_total"] as num?,
    originalShippingSubtotal: json["original_shipping_subtotal"] as num?,
    originalShippingTaxTotal: json["original_shipping_tax_total"] as num?,
    region: json["region"] == null ? null : AdminRegion.fromJson(json["region"] as Map<String, dynamic>),
    creditLines: (json["credit_lines"] as List?)?.map((e) => e == null ? null : OrderCreditLine.fromJson(e as Map<String, dynamic>)).toList().cast<OrderCreditLine>(),
    creditLineTotal: json["credit_line_total"] as num?,
    itemDiscountTotal: json["item_discount_total"] as num?,
    shippingDiscountTotal: json["shipping_discount_total"] as num?,
    customDisplayId: json["custom_display_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (paymentCollections != null) "payment_collections": paymentCollections!.map((e) => e.toJson()).toList(),
    if (fulfillments != null) "fulfillments": fulfillments!.map((e) => e.toJson()).toList(),
    if (salesChannel != null) "sales_channel": salesChannel!.toJson(),
    if (customer != null) "customer": customer!.toJson(),
    if (shippingAddress != null) "shipping_address": shippingAddress!.toJson(),
    if (billingAddress != null) "billing_address": billingAddress!.toJson(),
    if (items != null) "items": items!.map((e) => e.toJson()).toList(),
    if (shippingMethods != null) "shipping_methods": shippingMethods!.map((e) => e.toJson()).toList(),
    if (status != null) "status": status!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (id != null) "id": id!,
    if (version != null) "version": version!,
    if (regionId != null) "region_id": regionId!,
    if (customerId != null) "customer_id": customerId!,
    if (salesChannelId != null) "sales_channel_id": salesChannelId!,
    if (email != null) "email": email!,
    if (displayId != null) "display_id": displayId!,
    if (paymentStatus != null) "payment_status": paymentStatus!,
    if (fulfillmentStatus != null) "fulfillment_status": fulfillmentStatus!,
    if (transactions != null) "transactions": transactions!.map((e) => e.toJson()).toList(),
    if (summary != null) "summary": summary!.toJson(),
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (originalItemTotal != null) "original_item_total": originalItemTotal!,
    if (originalItemSubtotal != null) "original_item_subtotal": originalItemSubtotal!,
    if (originalItemTaxTotal != null) "original_item_tax_total": originalItemTaxTotal!,
    if (itemTotal != null) "item_total": itemTotal!,
    if (itemSubtotal != null) "item_subtotal": itemSubtotal!,
    if (itemTaxTotal != null) "item_tax_total": itemTaxTotal!,
    if (originalTotal != null) "original_total": originalTotal!,
    if (originalSubtotal != null) "original_subtotal": originalSubtotal!,
    if (originalTaxTotal != null) "original_tax_total": originalTaxTotal!,
    if (total != null) "total": total!,
    if (subtotal != null) "subtotal": subtotal!,
    if (taxTotal != null) "tax_total": taxTotal!,
    if (discountTotal != null) "discount_total": discountTotal!,
    if (discountTaxTotal != null) "discount_tax_total": discountTaxTotal!,
    if (giftCardTotal != null) "gift_card_total": giftCardTotal!,
    if (giftCardTaxTotal != null) "gift_card_tax_total": giftCardTaxTotal!,
    if (shippingTotal != null) "shipping_total": shippingTotal!,
    if (shippingSubtotal != null) "shipping_subtotal": shippingSubtotal!,
    if (shippingTaxTotal != null) "shipping_tax_total": shippingTaxTotal!,
    if (originalShippingTotal != null) "original_shipping_total": originalShippingTotal!,
    if (originalShippingSubtotal != null) "original_shipping_subtotal": originalShippingSubtotal!,
    if (originalShippingTaxTotal != null) "original_shipping_tax_total": originalShippingTaxTotal!,
    if (region != null) "region": region!.toJson(),
    if (creditLines != null) "credit_lines": creditLines!.map((e) => e.toJson()).toList(),
    if (creditLineTotal != null) "credit_line_total": creditLineTotal!,
    if (itemDiscountTotal != null) "item_discount_total": itemDiscountTotal!,
    if (shippingDiscountTotal != null) "shipping_discount_total": shippingDiscountTotal!,
    if (customDisplayId != null) "custom_display_id": customDisplayId!,
  };
}

/// The list of draft orders with pagination fields.
class AdminDraftOrderListResponse {
  AdminDraftOrderListResponse({
    this.limit,
    this.offset,
    this.count,
    this.draftOrders,
    this.estimateCount,
  });

  /// The maximum number of items retrieved.
  final num? limit;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The total count of items available.
  final num? count;
  /// The list of draft orders.
  final List<AdminDraftOrder>? draftOrders;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory AdminDraftOrderListResponse.fromJson(Map<String, dynamic> json) => AdminDraftOrderListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    draftOrders: (json["draft_orders"] as List?)?.map((e) => e == null ? null : AdminDraftOrder.fromJson(e as Map<String, dynamic>)).toList().cast<AdminDraftOrder>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (draftOrders != null) "draft_orders": draftOrders!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The parameters for retrieving draft orders.
class AdminDraftOrderParams {
  AdminDraftOrderParams({
    this.fields,
  });

  /// Comma-separated fields that should be included in the returned data. if a field is prefixed with `+` it will be added to the default fields, using `-` will remo
  final String? fields;

  factory AdminDraftOrderParams.fromJson(Map<String, dynamic> json) => AdminDraftOrderParams(
    fields: json["fields"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (fields != null) "fields": fields!,
  };
}

/// The draft order preview's details.
class AdminDraftOrderPreview {
  AdminDraftOrderPreview({
    this.returnRequestedTotal,
    this.orderChange,
    this.items,
    this.shippingMethods,
    this.currencyCode,
    this.version,
    this.id,
    this.regionId,
    this.customerId,
    this.salesChannelId,
    this.email,
    this.displayId,
    this.shippingAddress,
    this.billingAddress,
    this.paymentCollections,
    this.paymentStatus,
    this.fulfillments,
    this.fulfillmentStatus,
    this.transactions,
    this.summary,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.originalItemTotal,
    this.originalItemSubtotal,
    this.originalItemTaxTotal,
    this.itemTotal,
    this.itemSubtotal,
    this.itemTaxTotal,
    this.originalTotal,
    this.originalSubtotal,
    this.originalTaxTotal,
    this.total,
    this.subtotal,
    this.taxTotal,
    this.discountTotal,
    this.discountTaxTotal,
    this.giftCardTotal,
    this.giftCardTaxTotal,
    this.shippingTotal,
    this.shippingSubtotal,
    this.shippingTaxTotal,
    this.originalShippingTotal,
    this.originalShippingSubtotal,
    this.originalShippingTaxTotal,
    this.customer,
    this.salesChannel,
    this.status,
    this.region,
    this.creditLines,
    this.creditLineTotal,
    this.itemDiscountTotal,
    this.shippingDiscountTotal,
    this.customDisplayId,
  });

  /// The total of the requested return.
  final num? returnRequestedTotal;
  final AdminOrderChange? orderChange;
  /// The order's items.
  final List<AdminOrderLinePreview>? items;
  /// The order's shipping methods.
  final List<Map<String, dynamic>>? shippingMethods;
  /// The order's currency code.
  final String? currencyCode;
  /// The order's version when this preview is applied.
  final num? version;
  /// The order's ID.
  final String? id;
  /// The ID of the order's associated region.
  final String? regionId;
  /// The ID of the customer that placed the order.
  final String? customerId;
  /// The ID of the sales channel that the order was placed in.
  final String? salesChannelId;
  /// The email of the customer that placed the order.
  final String? email;
  /// The order's display ID.
  final num? displayId;
  final AdminOrderAddress? shippingAddress;
  final AdminOrderAddress? billingAddress;
  /// The order's payment collections.
  final List<AdminPaymentCollection>? paymentCollections;
  /// The order's payment status.
  final String? paymentStatus;
  /// The order's fulfillments.
  final List<AdminOrderFulfillment>? fulfillments;
  /// The order's fulfillment status.
  final String? fulfillmentStatus;
  /// The order's transactions.
  final List<BaseOrderTransaction>? transactions;
  final BaseOrderSummary? summary;
  /// The order's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the order was created.
  final DateTime? createdAt;
  /// The date the order was updated.
  final DateTime? updatedAt;
  /// The total of the order's items including taxes, excluding promotions.
  final num? originalItemTotal;
  /// The total of the order's items excluding taxes, including promotions.
  final num? originalItemSubtotal;
  /// The tax total of the order's items excluding promotions.
  final num? originalItemTaxTotal;
  /// The total of the order's items including taxes and promotions.
  final num? itemTotal;
  /// The total of the order's items excluding taxes, including promotions.
  final num? itemSubtotal;
  /// The tax total of the order's items including promotions.
  final num? itemTaxTotal;
  /// The order's total excluding promotions, including taxes.
  final num? originalTotal;
  /// The order's total excluding taxes, including promotions.
  final num? originalSubtotal;
  /// The order's tax total, excluding promotions.
  final num? originalTaxTotal;
  /// The order's total including taxes and promotions.
  final num? total;
  /// The order's total excluding taxes, including promotions.
  final num? subtotal;
  /// The order's tax total including promotions.
  final num? taxTotal;
  /// The order's discount or promotions total.
  final num? discountTotal;
  /// The tax total of order's discount or promotion.
  final num? discountTaxTotal;
  /// The order's gift card total.
  final num? giftCardTotal;
  /// The tax total of the order's gift card.
  final num? giftCardTaxTotal;
  /// The order's shipping total including taxes and promotions.
  final num? shippingTotal;
  /// The order's shipping total excluding taxes, including promotions.
  final num? shippingSubtotal;
  /// The tax total of the order's shipping.
  final num? shippingTaxTotal;
  /// The order's shipping total including taxes, excluding promotions.
  final num? originalShippingTotal;
  /// The order's shipping total excluding taxes, including promotions.
  final num? originalShippingSubtotal;
  /// The tax total of the order's shipping excluding promotions.
  final num? originalShippingTaxTotal;
  final AdminCustomer? customer;
  final AdminSalesChannel? salesChannel;
  /// The order's status.
  final String? status;
  final AdminRegion? region;
  /// The order preview's credit lines.
  final List<OrderCreditLine>? creditLines;
  /// The draft order preview's credit line total.
  final num? creditLineTotal;
  /// The total discount amount applied on the draft order's items.
  final num? itemDiscountTotal;
  /// The total discount amount applied on the draft order's shipping.
  final num? shippingDiscountTotal;
  /// The custom display ID of the draft order.
  final String? customDisplayId;

  factory AdminDraftOrderPreview.fromJson(Map<String, dynamic> json) => AdminDraftOrderPreview(
    returnRequestedTotal: json["return_requested_total"] as num?,
    orderChange: json["order_change"] == null ? null : AdminOrderChange.fromJson(json["order_change"] as Map<String, dynamic>),
    items: (json["items"] as List?)?.map((e) => e == null ? null : AdminOrderLinePreview.fromJson(e as Map<String, dynamic>)).toList().cast<AdminOrderLinePreview>(),
    shippingMethods: (json["shipping_methods"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    currencyCode: json["currency_code"] as String?,
    version: json["version"] as num?,
    id: json["id"] as String?,
    regionId: json["region_id"] as String?,
    customerId: json["customer_id"] as String?,
    salesChannelId: json["sales_channel_id"] as String?,
    email: json["email"] as String?,
    displayId: json["display_id"] as num?,
    shippingAddress: json["shipping_address"] == null ? null : AdminOrderAddress.fromJson(json["shipping_address"] as Map<String, dynamic>),
    billingAddress: json["billing_address"] == null ? null : AdminOrderAddress.fromJson(json["billing_address"] as Map<String, dynamic>),
    paymentCollections: (json["payment_collections"] as List?)?.map((e) => e == null ? null : AdminPaymentCollection.fromJson(e as Map<String, dynamic>)).toList().cast<AdminPaymentCollection>(),
    paymentStatus: json["payment_status"] as String?,
    fulfillments: (json["fulfillments"] as List?)?.map((e) => e == null ? null : AdminOrderFulfillment.fromJson(e as Map<String, dynamic>)).toList().cast<AdminOrderFulfillment>(),
    fulfillmentStatus: json["fulfillment_status"] as String?,
    transactions: (json["transactions"] as List?)?.map((e) => e == null ? null : BaseOrderTransaction.fromJson(e as Map<String, dynamic>)).toList().cast<BaseOrderTransaction>(),
    summary: json["summary"] == null ? null : BaseOrderSummary.fromJson(json["summary"] as Map<String, dynamic>),
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    originalItemTotal: json["original_item_total"] as num?,
    originalItemSubtotal: json["original_item_subtotal"] as num?,
    originalItemTaxTotal: json["original_item_tax_total"] as num?,
    itemTotal: json["item_total"] as num?,
    itemSubtotal: json["item_subtotal"] as num?,
    itemTaxTotal: json["item_tax_total"] as num?,
    originalTotal: json["original_total"] as num?,
    originalSubtotal: json["original_subtotal"] as num?,
    originalTaxTotal: json["original_tax_total"] as num?,
    total: json["total"] as num?,
    subtotal: json["subtotal"] as num?,
    taxTotal: json["tax_total"] as num?,
    discountTotal: json["discount_total"] as num?,
    discountTaxTotal: json["discount_tax_total"] as num?,
    giftCardTotal: json["gift_card_total"] as num?,
    giftCardTaxTotal: json["gift_card_tax_total"] as num?,
    shippingTotal: json["shipping_total"] as num?,
    shippingSubtotal: json["shipping_subtotal"] as num?,
    shippingTaxTotal: json["shipping_tax_total"] as num?,
    originalShippingTotal: json["original_shipping_total"] as num?,
    originalShippingSubtotal: json["original_shipping_subtotal"] as num?,
    originalShippingTaxTotal: json["original_shipping_tax_total"] as num?,
    customer: json["customer"] == null ? null : AdminCustomer.fromJson(json["customer"] as Map<String, dynamic>),
    salesChannel: json["sales_channel"] == null ? null : AdminSalesChannel.fromJson(json["sales_channel"] as Map<String, dynamic>),
    status: json["status"] as String?,
    region: json["region"] == null ? null : AdminRegion.fromJson(json["region"] as Map<String, dynamic>),
    creditLines: (json["credit_lines"] as List?)?.map((e) => e == null ? null : OrderCreditLine.fromJson(e as Map<String, dynamic>)).toList().cast<OrderCreditLine>(),
    creditLineTotal: json["credit_line_total"] as num?,
    itemDiscountTotal: json["item_discount_total"] as num?,
    shippingDiscountTotal: json["shipping_discount_total"] as num?,
    customDisplayId: json["custom_display_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (returnRequestedTotal != null) "return_requested_total": returnRequestedTotal!,
    if (orderChange != null) "order_change": orderChange!.toJson(),
    if (items != null) "items": items!.map((e) => e.toJson()).toList(),
    if (shippingMethods != null) "shipping_methods": shippingMethods!.map((e) => e).toList(),
    if (currencyCode != null) "currency_code": currencyCode!,
    if (version != null) "version": version!,
    if (id != null) "id": id!,
    if (regionId != null) "region_id": regionId!,
    if (customerId != null) "customer_id": customerId!,
    if (salesChannelId != null) "sales_channel_id": salesChannelId!,
    if (email != null) "email": email!,
    if (displayId != null) "display_id": displayId!,
    if (shippingAddress != null) "shipping_address": shippingAddress!.toJson(),
    if (billingAddress != null) "billing_address": billingAddress!.toJson(),
    if (paymentCollections != null) "payment_collections": paymentCollections!.map((e) => e.toJson()).toList(),
    if (paymentStatus != null) "payment_status": paymentStatus!,
    if (fulfillments != null) "fulfillments": fulfillments!.map((e) => e.toJson()).toList(),
    if (fulfillmentStatus != null) "fulfillment_status": fulfillmentStatus!,
    if (transactions != null) "transactions": transactions!.map((e) => e.toJson()).toList(),
    if (summary != null) "summary": summary!.toJson(),
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (originalItemTotal != null) "original_item_total": originalItemTotal!,
    if (originalItemSubtotal != null) "original_item_subtotal": originalItemSubtotal!,
    if (originalItemTaxTotal != null) "original_item_tax_total": originalItemTaxTotal!,
    if (itemTotal != null) "item_total": itemTotal!,
    if (itemSubtotal != null) "item_subtotal": itemSubtotal!,
    if (itemTaxTotal != null) "item_tax_total": itemTaxTotal!,
    if (originalTotal != null) "original_total": originalTotal!,
    if (originalSubtotal != null) "original_subtotal": originalSubtotal!,
    if (originalTaxTotal != null) "original_tax_total": originalTaxTotal!,
    if (total != null) "total": total!,
    if (subtotal != null) "subtotal": subtotal!,
    if (taxTotal != null) "tax_total": taxTotal!,
    if (discountTotal != null) "discount_total": discountTotal!,
    if (discountTaxTotal != null) "discount_tax_total": discountTaxTotal!,
    if (giftCardTotal != null) "gift_card_total": giftCardTotal!,
    if (giftCardTaxTotal != null) "gift_card_tax_total": giftCardTaxTotal!,
    if (shippingTotal != null) "shipping_total": shippingTotal!,
    if (shippingSubtotal != null) "shipping_subtotal": shippingSubtotal!,
    if (shippingTaxTotal != null) "shipping_tax_total": shippingTaxTotal!,
    if (originalShippingTotal != null) "original_shipping_total": originalShippingTotal!,
    if (originalShippingSubtotal != null) "original_shipping_subtotal": originalShippingSubtotal!,
    if (originalShippingTaxTotal != null) "original_shipping_tax_total": originalShippingTaxTotal!,
    if (customer != null) "customer": customer!.toJson(),
    if (salesChannel != null) "sales_channel": salesChannel!.toJson(),
    if (status != null) "status": status!,
    if (region != null) "region": region!.toJson(),
    if (creditLines != null) "credit_lines": creditLines!.map((e) => e.toJson()).toList(),
    if (creditLineTotal != null) "credit_line_total": creditLineTotal!,
    if (itemDiscountTotal != null) "item_discount_total": itemDiscountTotal!,
    if (shippingDiscountTotal != null) "shipping_discount_total": shippingDiscountTotal!,
    if (customDisplayId != null) "custom_display_id": customDisplayId!,
  };
}

/// The details of the preview on the draft order.
class AdminDraftOrderPreviewResponse {
  AdminDraftOrderPreviewResponse({
    this.draftOrderPreview,
  });

  final AdminDraftOrderPreview? draftOrderPreview;

  factory AdminDraftOrderPreviewResponse.fromJson(Map<String, dynamic> json) => AdminDraftOrderPreviewResponse(
    draftOrderPreview: json["draft_order_preview"] == null ? null : AdminDraftOrderPreview.fromJson(json["draft_order_preview"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (draftOrderPreview != null) "draft_order_preview": draftOrderPreview!.toJson(),
  };
}

/// The draft order's details.
class AdminDraftOrderResponse {
  AdminDraftOrderResponse({
    this.draftOrder,
  });

  final AdminDraftOrder? draftOrder;

  factory AdminDraftOrderResponse.fromJson(Map<String, dynamic> json) => AdminDraftOrderResponse(
    draftOrder: json["draft_order"] == null ? null : AdminDraftOrder.fromJson(json["draft_order"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (draftOrder != null) "draft_order": draftOrder!.toJson(),
  };
}

/// The details of an entity.
class AdminEntityInfo {
  AdminEntityInfo({
    this.name,
    this.pluralName,
    this.module,
    this.propertyCount,
    this.hasOverrides,
  });

  /// The entity's name.
  final String? name;
  /// The entity's plural name.
  final String? pluralName;
  /// The module the entity belongs to.
  final String? module;
  /// The number of properties the entity has.
  final num? propertyCount;
  /// Whether the entity has overrides.
  final bool? hasOverrides;

  factory AdminEntityInfo.fromJson(Map<String, dynamic> json) => AdminEntityInfo(
    name: json["name"] as String?,
    pluralName: json["pluralName"] as String?,
    module: json["module"] as String?,
    propertyCount: json["propertyCount"] as num?,
    hasOverrides: json["hasOverrides"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (pluralName != null) "pluralName": pluralName!,
    if (module != null) "module": module!,
    if (propertyCount != null) "propertyCount": propertyCount!,
    if (hasOverrides != null) "hasOverrides": hasOverrides!,
  };
}

/// The list of entities in the view.
class AdminEntityListResponse {
  AdminEntityListResponse({
    this.entities,
  });

  /// The list of entities.
  final List<AdminEntityInfo>? entities;

  factory AdminEntityListResponse.fromJson(Map<String, dynamic> json) => AdminEntityListResponse(
    entities: (json["entities"] as List?)?.map((e) => e == null ? null : AdminEntityInfo.fromJson(e as Map<String, dynamic>)).toList().cast<AdminEntityInfo>(),
  );

  Map<String, dynamic> toJson() => {
    if (entities != null) "entities": entities!.map((e) => e.toJson()).toList(),
  };
}

/// The exchange's details.
class AdminExchange {
  AdminExchange({
    this.orderId,
    this.returnItems,
    this.additionalItems,
    this.noNotification,
    this.differenceDue,
    this.return_,
    this.returnId,
    this.id,
    this.displayId,
    this.shippingMethods,
    this.transactions,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.orderVersion,
    this.createdBy,
    this.canceledAt,
    this.deletedAt,
    this.order,
    this.allowBackorder,
  });

  /// The ID of the order the exchange is created for.
  final String? orderId;
  /// The items returned (inbound) by the exchange.
  final List<AdminReturnItem>? returnItems;
  /// The new items (outbound) sent by the exchange.
  final List<BaseExchangeItem>? additionalItems;
  /// Whether to send the customer notifications when the exchange is updated.
  final bool? noNotification;
  /// The amount to be exchanged or refunded. If the amount is negative, it must be refunded. If positive, additional payment is required from the customer.
  final num? differenceDue;
  final AdminReturn? return_;
  /// The ID of the associated exchange.
  final String? returnId;
  /// The exchange's ID.
  final String? id;
  /// The exchange's display ID.
  final String? displayId;
  /// The shipping methods used to send the new (outbound) items.
  final List<BaseOrderShippingMethod>? shippingMethods;
  /// The exchange's transactions.
  final List<BaseOrderTransaction>? transactions;
  /// The exchange's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date that the exchange was created.
  final DateTime? createdAt;
  /// The date that the exchange was updated.
  final DateTime? updatedAt;
  /// The version of the order once the exchange is applied.
  final String? orderVersion;
  /// The ID of the user that created the exchange.
  final String? createdBy;
  /// The date the exchange was canceled.
  final DateTime? canceledAt;
  /// The date the exchange was deleted.
  final DateTime? deletedAt;
  final BaseOrder? order;
  /// Whether variants that are out-of-stock can still be added as additional or outbound items.
  final bool? allowBackorder;

  factory AdminExchange.fromJson(Map<String, dynamic> json) => AdminExchange(
    orderId: json["order_id"] as String?,
    returnItems: (json["return_items"] as List?)?.map((e) => e == null ? null : AdminReturnItem.fromJson(e as Map<String, dynamic>)).toList().cast<AdminReturnItem>(),
    additionalItems: (json["additional_items"] as List?)?.map((e) => e == null ? null : BaseExchangeItem.fromJson(e as Map<String, dynamic>)).toList().cast<BaseExchangeItem>(),
    noNotification: json["no_notification"] as bool?,
    differenceDue: json["difference_due"] as num?,
    return_: json["return"] == null ? null : AdminReturn.fromJson(json["return"] as Map<String, dynamic>),
    returnId: json["return_id"] as String?,
    id: json["id"] as String?,
    displayId: json["display_id"] as String?,
    shippingMethods: (json["shipping_methods"] as List?)?.map((e) => e == null ? null : BaseOrderShippingMethod.fromJson(e as Map<String, dynamic>)).toList().cast<BaseOrderShippingMethod>(),
    transactions: (json["transactions"] as List?)?.map((e) => e == null ? null : BaseOrderTransaction.fromJson(e as Map<String, dynamic>)).toList().cast<BaseOrderTransaction>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    orderVersion: json["order_version"] as String?,
    createdBy: json["created_by"] as String?,
    canceledAt: json["canceled_at"] == null ? null : DateTime.parse(json["canceled_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    order: json["order"] == null ? null : BaseOrder.fromJson(json["order"] as Map<String, dynamic>),
    allowBackorder: json["allow_backorder"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (orderId != null) "order_id": orderId!,
    if (returnItems != null) "return_items": returnItems!.map((e) => e.toJson()).toList(),
    if (additionalItems != null) "additional_items": additionalItems!.map((e) => e.toJson()).toList(),
    if (noNotification != null) "no_notification": noNotification!,
    if (differenceDue != null) "difference_due": differenceDue!,
    if (return_ != null) "return": return_!.toJson(),
    if (returnId != null) "return_id": returnId!,
    if (id != null) "id": id!,
    if (displayId != null) "display_id": displayId!,
    if (shippingMethods != null) "shipping_methods": shippingMethods!.map((e) => e.toJson()).toList(),
    if (transactions != null) "transactions": transactions!.map((e) => e.toJson()).toList(),
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (orderVersion != null) "order_version": orderVersion!,
    if (createdBy != null) "created_by": createdBy!,
    if (canceledAt != null) "canceled_at": canceledAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (order != null) "order": order!.toJson(),
    if (allowBackorder != null) "allow_backorder": allowBackorder!,
  };
}

/// The outbound shipping method's details.
class AdminExchangeAddOutboundShipping {
  AdminExchangeAddOutboundShipping({
    this.shippingOptionId,
    this.customAmount,
    this.description,
    this.internalNote,
    this.metadata,
  });

  /// The ID of the associated shipping option.
  final String? shippingOptionId;
  /// Set a custom amount for the shipping method.
  final num? customAmount;
  /// The shipping method's description.
  final String? description;
  /// A note viewed by admin users only.
  final String? internalNote;
  /// The exchange's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminExchangeAddOutboundShipping.fromJson(Map<String, dynamic> json) => AdminExchangeAddOutboundShipping(
    shippingOptionId: json["shipping_option_id"] as String?,
    customAmount: json["custom_amount"] as num?,
    description: json["description"] as String?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (customAmount != null) "custom_amount": customAmount!,
    if (description != null) "description": description!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of deleting an exchange.
class AdminExchangeDeleteResponse {
  AdminExchangeDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The exchange's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the exchange was deleted.
  final bool? deleted;

  factory AdminExchangeDeleteResponse.fromJson(Map<String, dynamic> json) => AdminExchangeDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The exchange's details.
class AdminExchangeOrderResponse {
  AdminExchangeOrderResponse({
    this.order,
    this.exchange,
  });

  final Order? order;
  final AdminExchange? exchange;

  factory AdminExchangeOrderResponse.fromJson(Map<String, dynamic> json) => AdminExchangeOrderResponse(
    order: json["order"] == null ? null : Order.fromJson(json["order"] as Map<String, dynamic>),
    exchange: json["exchange"] == null ? null : AdminExchange.fromJson(json["exchange"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (order != null) "order": order!.toJson(),
    if (exchange != null) "exchange": exchange!.toJson(),
  };
}

/// A preview of the order once the exchange is applied.
class AdminExchangePreviewResponse {
  AdminExchangePreviewResponse({
    this.orderPreview,
    this.exchange,
  });

  final AdminOrderPreview? orderPreview;
  final AdminExchange? exchange;

  factory AdminExchangePreviewResponse.fromJson(Map<String, dynamic> json) => AdminExchangePreviewResponse(
    orderPreview: json["order_preview"] == null ? null : AdminOrderPreview.fromJson(json["order_preview"] as Map<String, dynamic>),
    exchange: json["exchange"] == null ? null : AdminExchange.fromJson(json["exchange"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (orderPreview != null) "order_preview": orderPreview!.toJson(),
    if (exchange != null) "exchange": exchange!.toJson(),
  };
}

/// The details of a requested exchange.
class AdminExchangeRequestResponse {
  AdminExchangeRequestResponse({
    this.return_,
    this.orderPreview,
    this.exchange,
  });

  final AdminReturn? return_;
  final AdminOrderPreview? orderPreview;
  final AdminExchange? exchange;

  factory AdminExchangeRequestResponse.fromJson(Map<String, dynamic> json) => AdminExchangeRequestResponse(
    return_: json["return"] == null ? null : AdminReturn.fromJson(json["return"] as Map<String, dynamic>),
    orderPreview: json["order_preview"] == null ? null : AdminOrderPreview.fromJson(json["order_preview"] as Map<String, dynamic>),
    exchange: json["exchange"] == null ? null : AdminExchange.fromJson(json["exchange"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (return_ != null) "return": return_!.toJson(),
    if (orderPreview != null) "order_preview": orderPreview!.toJson(),
    if (exchange != null) "exchange": exchange!.toJson(),
  };
}

/// The exchange's details.
class AdminExchangeResponse {
  AdminExchangeResponse({
    this.exchange,
  });

  final AdminExchange? exchange;

  factory AdminExchangeResponse.fromJson(Map<String, dynamic> json) => AdminExchangeResponse(
    exchange: json["exchange"] == null ? null : AdminExchange.fromJson(json["exchange"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (exchange != null) "exchange": exchange!.toJson(),
  };
}

/// The details of an exchange's return.
class AdminExchangeReturnResponse {
  AdminExchangeReturnResponse({
    this.orderPreview,
    this.return_,
  });

  final AdminOrderPreview? orderPreview;
  final AdminReturn? return_;

  factory AdminExchangeReturnResponse.fromJson(Map<String, dynamic> json) => AdminExchangeReturnResponse(
    orderPreview: json["order_preview"] == null ? null : AdminOrderPreview.fromJson(json["order_preview"] as Map<String, dynamic>),
    return_: json["return"] == null ? null : AdminReturn.fromJson(json["return"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (orderPreview != null) "order_preview": orderPreview!.toJson(),
    if (return_ != null) "return": return_!.toJson(),
  };
}

/// The details of the shipping method to update.
class AdminExchangeUpdateInboundShipping {
  AdminExchangeUpdateInboundShipping({
    this.customAmount,
    this.internalNote,
    this.metadata,
  });

  /// The shipping method's custom amount.
  final num? customAmount;
  /// A note viewed by admin users only.
  final String? internalNote;
  /// The exchange's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminExchangeUpdateInboundShipping.fromJson(Map<String, dynamic> json) => AdminExchangeUpdateInboundShipping(
    customAmount: json["custom_amount"] as num?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (customAmount != null) "custom_amount": customAmount!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of the shipping method to update.
class AdminExchangeUpdateOutboundShipping {
  AdminExchangeUpdateOutboundShipping({
    this.customAmount,
    this.internalNote,
    this.metadata,
  });

  /// The shipping method's custom amount.
  final num? customAmount;
  /// A note viewed by admin users only.
  final String? internalNote;
  /// The exchange's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminExchangeUpdateOutboundShipping.fromJson(Map<String, dynamic> json) => AdminExchangeUpdateOutboundShipping(
    customAmount: json["custom_amount"] as num?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (customAmount != null) "custom_amount": customAmount!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of the order export.
class AdminExportOrderResponse {
  AdminExportOrderResponse({
    this.transactionId,
  });

  /// The ID of the workflow execution's transaction. Use it to check the status of the export by sending a GET request to `/admin/workflows-executions/export-orders/
  final String? transactionId;

  factory AdminExportOrderResponse.fromJson(Map<String, dynamic> json) => AdminExportOrderResponse(
    transactionId: json["transaction_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (transactionId != null) "transaction_id": transactionId!,
  };
}

/// The details of the product export.
class AdminExportProductResponse {
  AdminExportProductResponse({
    this.transactionId,
  });

  /// The ID of the workflow execution's transaction. Use it to check the status of the export by sending a GET request to `/admin/workflows-executions/export-product
  final String? transactionId;

  factory AdminExportProductResponse.fromJson(Map<String, dynamic> json) => AdminExportProductResponse(
    transactionId: json["transaction_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (transactionId != null) "transaction_id": transactionId!,
  };
}

/// A file's details.
class AdminFile {
  AdminFile({
    this.id,
    this.url,
  });

  /// The file's ID.
  final String? id;
  /// The file's URL.
  final String? url;

  factory AdminFile.fromJson(Map<String, dynamic> json) => AdminFile(
    id: json["id"] as String?,
    url: json["url"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (url != null) "url": url!,
  };
}

/// The list of uploaded files.
class AdminFileListResponse {
  AdminFileListResponse({
    this.files,
  });

  /// The list of uploaded files.
  final List<AdminFile>? files;

  factory AdminFileListResponse.fromJson(Map<String, dynamic> json) => AdminFileListResponse(
    files: (json["files"] as List?)?.map((e) => e == null ? null : AdminFile.fromJson(e as Map<String, dynamic>)).toList().cast<AdminFile>(),
  );

  Map<String, dynamic> toJson() => {
    if (files != null) "files": files!.map((e) => e.toJson()).toList(),
  };
}

/// A file's details.
class AdminFileResponse {
  AdminFileResponse({
    this.file,
  });

  final AdminFile? file;

  factory AdminFileResponse.fromJson(Map<String, dynamic> json) => AdminFileResponse(
    file: json["file"] == null ? null : AdminFile.fromJson(json["file"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (file != null) "file": file!.toJson(),
  };
}

/// The fulfillment's details.
class AdminFulfillment {
  AdminFulfillment({
    this.id,
    this.locationId,
    this.providerId,
    this.shippingOptionId,
    this.provider,
    this.deliveryAddress,
    this.items,
    this.labels,
    this.packedAt,
    this.shippedAt,
    this.deliveredAt,
    this.canceledAt,
    this.data,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The fulfillment's ID.
  final String? id;
  /// The ID of the location the fulfillment's items are shipped from.
  final String? locationId;
  /// The ID of the fulfillment provider handling this fulfillment.
  final String? providerId;
  /// The ID of the shipping option this fulfillment is created for.
  final String? shippingOptionId;
  final AdminFulfillmentProvider? provider;
  final AdminFulfillmentAddress? deliveryAddress;
  /// The fulfillment's items.
  final List<AdminFulfillmentItem>? items;
  /// The fulfillment's shipment labels.
  final List<AdminFulfillmentLabel>? labels;
  /// The date the fulfillment was packed at.
  final String? packedAt;
  /// The date the fulfillment was shipped at.
  final String? shippedAt;
  /// The date the fulfillment was delivered at.
  final String? deliveredAt;
  /// The date the fulfillment was canceled at.
  final String? canceledAt;
  /// The fulfillment's data, useful for the third-party provider handling the fulfillment.
  final Map<String, dynamic>? data;
  /// The fulfillment's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the fulfillment was created at.
  final DateTime? createdAt;
  /// The date the fulfillment was updated at.
  final DateTime? updatedAt;
  /// The date the fulfillment was deleted at.
  final DateTime? deletedAt;

  factory AdminFulfillment.fromJson(Map<String, dynamic> json) => AdminFulfillment(
    id: json["id"] as String?,
    locationId: json["location_id"] as String?,
    providerId: json["provider_id"] as String?,
    shippingOptionId: json["shipping_option_id"] as String?,
    provider: json["provider"] == null ? null : AdminFulfillmentProvider.fromJson(json["provider"] as Map<String, dynamic>),
    deliveryAddress: json["delivery_address"] == null ? null : AdminFulfillmentAddress.fromJson(json["delivery_address"] as Map<String, dynamic>),
    items: (json["items"] as List?)?.map((e) => e == null ? null : AdminFulfillmentItem.fromJson(e as Map<String, dynamic>)).toList().cast<AdminFulfillmentItem>(),
    labels: (json["labels"] as List?)?.map((e) => e == null ? null : AdminFulfillmentLabel.fromJson(e as Map<String, dynamic>)).toList().cast<AdminFulfillmentLabel>(),
    packedAt: json["packed_at"] as String?,
    shippedAt: json["shipped_at"] as String?,
    deliveredAt: json["delivered_at"] as String?,
    canceledAt: json["canceled_at"] as String?,
    data: json["data"] as Map<String, dynamic>?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (locationId != null) "location_id": locationId!,
    if (providerId != null) "provider_id": providerId!,
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (provider != null) "provider": provider!.toJson(),
    if (deliveryAddress != null) "delivery_address": deliveryAddress!.toJson(),
    if (items != null) "items": items!.map((e) => e.toJson()).toList(),
    if (labels != null) "labels": labels!.map((e) => e.toJson()).toList(),
    if (packedAt != null) "packed_at": packedAt!,
    if (shippedAt != null) "shipped_at": shippedAt!,
    if (deliveredAt != null) "delivered_at": deliveredAt!,
    if (canceledAt != null) "canceled_at": canceledAt!,
    if (data != null) "data": data!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// An address's details.
class AdminFulfillmentAddress {
  AdminFulfillmentAddress({
    this.id,
    this.fulfillmentId,
    this.company,
    this.firstName,
    this.lastName,
    this.address1,
    this.address2,
    this.city,
    this.countryCode,
    this.province,
    this.postalCode,
    this.phone,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The address's ID.
  final String? id;
  /// The ID of the fulfillment that the address belongs to.
  final String? fulfillmentId;
  /// The address's company.
  final String? company;
  /// The address's first name.
  final String? firstName;
  /// The address's last name.
  final String? lastName;
  /// The address's first line.
  final String? address1;
  /// The address's second line.
  final String? address2;
  /// The address's city.
  final String? city;
  /// The address's country code.
  final String? countryCode;
  /// The address's lower-case ISO 3166-2 province code.
  final String? province;
  /// The address's postal code.
  final String? postalCode;
  /// The address's phone.
  final String? phone;
  /// The address's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the address was created.
  final DateTime? createdAt;
  /// The date the address was updated.
  final DateTime? updatedAt;
  /// The date the address was deleted.
  final DateTime? deletedAt;

  factory AdminFulfillmentAddress.fromJson(Map<String, dynamic> json) => AdminFulfillmentAddress(
    id: json["id"] as String?,
    fulfillmentId: json["fulfillment_id"] as String?,
    company: json["company"] as String?,
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    address1: json["address_1"] as String?,
    address2: json["address_2"] as String?,
    city: json["city"] as String?,
    countryCode: json["country_code"] as String?,
    province: json["province"] as String?,
    postalCode: json["postal_code"] as String?,
    phone: json["phone"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (fulfillmentId != null) "fulfillment_id": fulfillmentId!,
    if (company != null) "company": company!,
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (address1 != null) "address_1": address1!,
    if (address2 != null) "address_2": address2!,
    if (city != null) "city": city!,
    if (countryCode != null) "country_code": countryCode!,
    if (province != null) "province": province!,
    if (postalCode != null) "postal_code": postalCode!,
    if (phone != null) "phone": phone!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The address to deliver the items to.
class AdminFulfillmentDeliveryAddress {
  AdminFulfillmentDeliveryAddress({
    this.firstName,
    this.lastName,
    this.phone,
    this.company,
    this.address1,
    this.address2,
    this.city,
    this.countryCode,
    this.province,
    this.postalCode,
    this.metadata,
  });

  /// The customer's first name.
  final String? firstName;
  /// The customer's last name.
  final String? lastName;
  /// The customer's phone.
  final String? phone;
  /// The delivery address's company.
  final String? company;
  /// The delivery address's first line.
  final String? address1;
  /// The delivery address's second line.
  final String? address2;
  /// The delivery address's city.
  final String? city;
  /// The delivery address's country code.
  final String? countryCode;
  /// The delivery address's ISO 3166-2 province code. Must be lower-case.
  final String? province;
  /// The delivery address's postal code.
  final String? postalCode;
  /// The delivery address's metadata, used to store custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminFulfillmentDeliveryAddress.fromJson(Map<String, dynamic> json) => AdminFulfillmentDeliveryAddress(
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    phone: json["phone"] as String?,
    company: json["company"] as String?,
    address1: json["address_1"] as String?,
    address2: json["address_2"] as String?,
    city: json["city"] as String?,
    countryCode: json["country_code"] as String?,
    province: json["province"] as String?,
    postalCode: json["postal_code"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (phone != null) "phone": phone!,
    if (company != null) "company": company!,
    if (address1 != null) "address_1": address1!,
    if (address2 != null) "address_2": address2!,
    if (city != null) "city": city!,
    if (countryCode != null) "country_code": countryCode!,
    if (province != null) "province": province!,
    if (postalCode != null) "postal_code": postalCode!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of a fulfillment's item.
class AdminFulfillmentItem {
  AdminFulfillmentItem({
    this.id,
    this.title,
    this.quantity,
    this.sku,
    this.barcode,
    this.lineItemId,
    this.inventoryItemId,
    this.fulfillmentId,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The item's ID.
  final String? id;
  /// The item's title.
  final String? title;
  /// The item's quantity to be fulfilled.
  final num? quantity;
  /// The item's SKU.
  final String? sku;
  /// The item's barcode.
  final String? barcode;
  /// The ID of the order's line item to be fulfilled.
  final String? lineItemId;
  /// The ID of the inventory item of the underlying product variant.
  final String? inventoryItemId;
  /// The ID of the fulfillment the item belongs to.
  final String? fulfillmentId;
  /// The date the item was created.
  final DateTime? createdAt;
  /// The date the item was updated.
  final DateTime? updatedAt;
  /// The date the item was deleted.
  final DateTime? deletedAt;

  factory AdminFulfillmentItem.fromJson(Map<String, dynamic> json) => AdminFulfillmentItem(
    id: json["id"] as String?,
    title: json["title"] as String?,
    quantity: json["quantity"] as num?,
    sku: json["sku"] as String?,
    barcode: json["barcode"] as String?,
    lineItemId: json["line_item_id"] as String?,
    inventoryItemId: json["inventory_item_id"] as String?,
    fulfillmentId: json["fulfillment_id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (title != null) "title": title!,
    if (quantity != null) "quantity": quantity!,
    if (sku != null) "sku": sku!,
    if (barcode != null) "barcode": barcode!,
    if (lineItemId != null) "line_item_id": lineItemId!,
    if (inventoryItemId != null) "inventory_item_id": inventoryItemId!,
    if (fulfillmentId != null) "fulfillment_id": fulfillmentId!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The details of a fulfillmet's shipment label.
class AdminFulfillmentLabel {
  AdminFulfillmentLabel({
    this.id,
    this.trackingNumber,
    this.trackingUrl,
    this.labelUrl,
    this.fulfillmentId,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The label's ID.
  final String? id;
  /// The label's tracking number.
  final String? trackingNumber;
  /// The label's tracking URL.
  final String? trackingUrl;
  /// The label's URL.
  final String? labelUrl;
  /// The ID of the fulfillment the label is associated with.
  final String? fulfillmentId;
  /// The date the label was created.
  final DateTime? createdAt;
  /// The date the label was updated.
  final DateTime? updatedAt;
  /// The date the label was deleted.
  final DateTime? deletedAt;

  factory AdminFulfillmentLabel.fromJson(Map<String, dynamic> json) => AdminFulfillmentLabel(
    id: json["id"] as String?,
    trackingNumber: json["tracking_number"] as String?,
    trackingUrl: json["tracking_url"] as String?,
    labelUrl: json["label_url"] as String?,
    fulfillmentId: json["fulfillment_id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (trackingNumber != null) "tracking_number": trackingNumber!,
    if (trackingUrl != null) "tracking_url": trackingUrl!,
    if (labelUrl != null) "label_url": labelUrl!,
    if (fulfillmentId != null) "fulfillment_id": fulfillmentId!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The fulfillment provider's details.
class AdminFulfillmentProvider {
  AdminFulfillmentProvider({
    this.id,
    this.isEnabled,
  });

  /// The provider's ID.
  final String? id;
  /// The provider's is enabled.
  final bool? isEnabled;

  factory AdminFulfillmentProvider.fromJson(Map<String, dynamic> json) => AdminFulfillmentProvider(
    id: json["id"] as String?,
    isEnabled: json["is_enabled"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (isEnabled != null) "is_enabled": isEnabled!,
  };
}

/// The paginated list of fulfillment providers.
class AdminFulfillmentProviderListResponse {
  AdminFulfillmentProviderListResponse({
    this.limit,
    this.offset,
    this.count,
    this.fulfillmentProviders,
    this.estimateCount,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The total count of items.
  final num? count;
  /// The list of fulfillment providers.
  final List<AdminFulfillmentProvider>? fulfillmentProviders;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory AdminFulfillmentProviderListResponse.fromJson(Map<String, dynamic> json) => AdminFulfillmentProviderListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    fulfillmentProviders: (json["fulfillment_providers"] as List?)?.map((e) => e == null ? null : AdminFulfillmentProvider.fromJson(e as Map<String, dynamic>)).toList().cast<AdminFulfillmentProvider>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (fulfillmentProviders != null) "fulfillment_providers": fulfillmentProviders!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The fulfillment option's details.
class AdminFulfillmentProviderOption {
  AdminFulfillmentProviderOption({
    this.id,
    this.isReturn,
  });

  /// The fulfillment option's ID.
  final String? id;
  /// Whether the fulfillment option is used for returns.
  final bool? isReturn;

  factory AdminFulfillmentProviderOption.fromJson(Map<String, dynamic> json) => AdminFulfillmentProviderOption(
    id: json["id"] as String?,
    isReturn: json["is_return"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (isReturn != null) "is_return": isReturn!,
  };
}

/// The paginated list of fulfillment options.
class AdminFulfillmentProviderOptionsListResponse {
  AdminFulfillmentProviderOptionsListResponse({
    this.limit,
    this.offset,
    this.count,
    this.fulfillmentOptions,
    this.estimateCount,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The total number of items.
  final num? count;
  /// The list of fulfillment options.
  final List<AdminFulfillmentProviderOption>? fulfillmentOptions;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory AdminFulfillmentProviderOptionsListResponse.fromJson(Map<String, dynamic> json) => AdminFulfillmentProviderOptionsListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    fulfillmentOptions: (json["fulfillment_options"] as List?)?.map((e) => e == null ? null : AdminFulfillmentProviderOption.fromJson(e as Map<String, dynamic>)).toList().cast<AdminFulfillmentProviderOption>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (fulfillmentOptions != null) "fulfillment_options": fulfillmentOptions!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// A fulfillment's details.
class AdminFulfillmentResponse {
  AdminFulfillmentResponse({
    this.fulfillment,
  });

  final AdminFulfillment? fulfillment;

  factory AdminFulfillmentResponse.fromJson(Map<String, dynamic> json) => AdminFulfillmentResponse(
    fulfillment: json["fulfillment"] == null ? null : AdminFulfillment.fromJson(json["fulfillment"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (fulfillment != null) "fulfillment": fulfillment!.toJson(),
  };
}

/// The service zone's fulfillment set.
class AdminFulfillmentSet {
  AdminFulfillmentSet({
    this.id,
    this.name,
    this.type,
    this.location,
    this.serviceZones,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The fulfillment set's ID.
  final String? id;
  /// The fulfillment set's name.
  final String? name;
  /// The fulfillment set's type.
  final String? type;
  final AdminStockLocation? location;
  /// The fulfillment set's service zones.
  final List<AdminServiceZone>? serviceZones;
  /// The fulfillment set's created at.
  final DateTime? createdAt;
  /// The fulfillment set's updated at.
  final DateTime? updatedAt;
  /// The fulfillment set's deleted at.
  final DateTime? deletedAt;

  factory AdminFulfillmentSet.fromJson(Map<String, dynamic> json) => AdminFulfillmentSet(
    id: json["id"] as String?,
    name: json["name"] as String?,
    type: json["type"] as String?,
    location: json["location"] == null ? null : AdminStockLocation.fromJson(json["location"] as Map<String, dynamic>),
    serviceZones: (json["service_zones"] as List?)?.map((e) => e == null ? null : AdminServiceZone.fromJson(e as Map<String, dynamic>)).toList().cast<AdminServiceZone>(),
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (name != null) "name": name!,
    if (type != null) "type": type!,
    if (location != null) "location": location!.toJson(),
    if (serviceZones != null) "service_zones": serviceZones!.map((e) => e.toJson()).toList(),
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The deletion details.
class AdminFulfillmentSetDeleteResponse {
  AdminFulfillmentSetDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The fulfillment set's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the fulfillment set was deleted.
  final bool? deleted;

  factory AdminFulfillmentSetDeleteResponse.fromJson(Map<String, dynamic> json) => AdminFulfillmentSetDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The fulfillment set's details.
class AdminFulfillmentSetResponse {
  AdminFulfillmentSetResponse({
    this.fulfillmentSet,
  });

  final AdminFulfillmentSet? fulfillmentSet;

  factory AdminFulfillmentSetResponse.fromJson(Map<String, dynamic> json) => AdminFulfillmentSetResponse(
    fulfillmentSet: json["fulfillment_set"] == null ? null : AdminFulfillmentSet.fromJson(json["fulfillment_set"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (fulfillmentSet != null) "fulfillment_set": fulfillmentSet!.toJson(),
  };
}

/// The geo zone's geo zones.
class AdminGeoZone {
  AdminGeoZone({
    this.id,
    this.type,
    this.countryCode,
    this.provinceCode,
    this.city,
    this.postalExpression,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The geo zone's ID.
  final String? id;
  /// The geo zone's type.
  final String? type;
  /// The geo zone's country code.
  final String? countryCode;
  /// The geo zone's lower-case ISO 3166-2 province code.
  final String? provinceCode;
  /// The geo zone's city.
  final String? city;
  /// The geo zone's postal expression.
  final Map<String, dynamic>? postalExpression;
  /// The geo zone's created at.
  final DateTime? createdAt;
  /// The geo zone's updated at.
  final DateTime? updatedAt;
  /// The geo zone's deleted at.
  final DateTime? deletedAt;

  factory AdminGeoZone.fromJson(Map<String, dynamic> json) => AdminGeoZone(
    id: json["id"] as String?,
    type: json["type"] as String?,
    countryCode: json["country_code"] as String?,
    provinceCode: json["province_code"] as String?,
    city: json["city"] as String?,
    postalExpression: json["postal_expression"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (type != null) "type": type!,
    if (countryCode != null) "country_code": countryCode!,
    if (provinceCode != null) "province_code": provinceCode!,
    if (city != null) "city": city!,
    if (postalExpression != null) "postal_expression": postalExpression!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The details of the user to be created.
class AdminGetInviteAcceptParams {
  AdminGetInviteAcceptParams({
    this.token,
    this.fields,
  });

  /// The invite's token.
  final String? token;
  /// The invite's fields.
  final String? fields;

  factory AdminGetInviteAcceptParams.fromJson(Map<String, dynamic> json) => AdminGetInviteAcceptParams(
    token: json["token"] as String?,
    fields: json["fields"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (token != null) "token": token!,
    if (fields != null) "fields": fields!,
  };
}

/// The gift card's details.
class AdminGiftCard {
  AdminGiftCard({
    this.lineItem,
    this.customer,
    this.id,
    this.code,
    this.status,
    this.value,
    this.currencyCode,
    this.customerId,
    this.referenceId,
    this.note,
    this.reference,
    this.expiresAt,
    this.createdAt,
    this.updatedAt,
  });

  final AdminOrderLineItem? lineItem;
  final AdminCustomer? customer;
  /// The gift card's ID.
  final String? id;
  /// The gift card's code.
  final String? code;
  /// The gift card's status.
  final String? status;
  /// The gift card's amount.
  final num? value;
  /// The gift card's currency code.
  final String? currencyCode;
  /// The ID of the customer associated with the gift card.
  final String? customerId;
  /// The gift card's reference ID.
  final String? referenceId;
  /// The gift card's note.
  final String? note;
  /// The gift card's reference.
  final String? reference;
  /// The date the gift card expires at.
  final String? expiresAt;
  /// The date the gift card was created at.
  final DateTime? createdAt;
  /// The date the gift card was updated at.
  final DateTime? updatedAt;

  factory AdminGiftCard.fromJson(Map<String, dynamic> json) => AdminGiftCard(
    lineItem: json["line_item"] == null ? null : AdminOrderLineItem.fromJson(json["line_item"] as Map<String, dynamic>),
    customer: json["customer"] == null ? null : AdminCustomer.fromJson(json["customer"] as Map<String, dynamic>),
    id: json["id"] as String?,
    code: json["code"] as String?,
    status: json["status"] as String?,
    value: json["value"] as num?,
    currencyCode: json["currency_code"] as String?,
    customerId: json["customer_id"] as String?,
    referenceId: json["reference_id"] as String?,
    note: json["note"] as String?,
    reference: json["reference"] as String?,
    expiresAt: json["expires_at"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (lineItem != null) "line_item": lineItem!.toJson(),
    if (customer != null) "customer": customer!.toJson(),
    if (id != null) "id": id!,
    if (code != null) "code": code!,
    if (status != null) "status": status!,
    if (value != null) "value": value!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (customerId != null) "customer_id": customerId!,
    if (referenceId != null) "reference_id": referenceId!,
    if (note != null) "note": note!,
    if (reference != null) "reference": reference!,
    if (expiresAt != null) "expires_at": expiresAt!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
  };
}

/// The gift card's details.
class AdminGiftCardResponse {
  AdminGiftCardResponse({
    this.giftCard,
  });

  final AdminGiftCard? giftCard;

  factory AdminGiftCardResponse.fromJson(Map<String, dynamic> json) => AdminGiftCardResponse(
    giftCard: json["gift_card"] == null ? null : AdminGiftCard.fromJson(json["gift_card"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (giftCard != null) "gift_card": giftCard!.toJson(),
  };
}

/// The paginated list of gift cards.
class AdminGiftCardsResponse {
  AdminGiftCardsResponse({
    this.limit,
    this.offset,
    this.count,
    this.giftCards,
    this.estimateCount,
  });

  /// The maximum number of gift cards to return.
  final num? limit;
  /// The number of gift cards to skip before retrieving the results.
  final num? offset;
  /// The total number of gift cards available.
  final num? count;
  /// The list of gift cards.
  final List<AdminGiftCard>? giftCards;
  /// The gift card's estimate count.
  final num? estimateCount;

  factory AdminGiftCardsResponse.fromJson(Map<String, dynamic> json) => AdminGiftCardsResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    giftCards: (json["gift_cards"] as List?)?.map((e) => e == null ? null : AdminGiftCard.fromJson(e as Map<String, dynamic>)).toList().cast<AdminGiftCard>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (giftCards != null) "gift_cards": giftCards!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The import's details.
class AdminImportProductRequest {
  AdminImportProductRequest({
    this.file,
  });

  /// A File to upload.
  final Map<String, dynamic>? file;

  factory AdminImportProductRequest.fromJson(Map<String, dynamic> json) => AdminImportProductRequest(
    file: json["file"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (file != null) "file": file!,
  };
}

/// The import process's details.
class AdminImportProductResponse {
  AdminImportProductResponse({
    this.transactionId,
    this.summary,
  });

  /// The ID of the workflow execution's transaction. This is useful to confirm the import using the `/admin/products/:transaction-id/import` API route.
  final String? transactionId;
  /// The import's summary.
  final Map<String, dynamic>? summary;

  factory AdminImportProductResponse.fromJson(Map<String, dynamic> json) => AdminImportProductResponse(
    transactionId: json["transaction_id"] as String?,
    summary: json["summary"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (transactionId != null) "transaction_id": transactionId!,
    if (summary != null) "summary": summary!,
  };
}

/// The details of the product's import file.
class AdminImportProducts {
  AdminImportProducts({
    this.fileKey,
    this.originalname,
    this.extension,
    this.size,
    this.mimeType,
  });

  /// The name of the file as stored in the configured File Module Provider.
  final String? fileKey;
  /// The file's original name.
  final String? originalname;
  /// The file's extension.
  final String? extension;
  /// The file's size in bytes.
  final num? size;
  /// The file's mime type.
  final String? mimeType;

  factory AdminImportProducts.fromJson(Map<String, dynamic> json) => AdminImportProducts(
    fileKey: json["file_key"] as String?,
    originalname: json["originalname"] as String?,
    extension: json["extension"] as String?,
    size: json["size"] as num?,
    mimeType: json["mime_type"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (fileKey != null) "file_key": fileKey!,
    if (originalname != null) "originalname": originalname!,
    if (extension != null) "extension": extension!,
    if (size != null) "size": size!,
    if (mimeType != null) "mime_type": mimeType!,
  };
}

/// The index's metadata details.
class AdminIndexDetailsResponse {
  AdminIndexDetailsResponse({
    this.metadata,
  });

  /// The index's metadata.
  final List<IndexInfo>? metadata;

  factory AdminIndexDetailsResponse.fromJson(Map<String, dynamic> json) => AdminIndexDetailsResponse(
    metadata: (json["metadata"] as List?)?.map((e) => e == null ? null : IndexInfo.fromJson(e as Map<String, dynamic>)).toList().cast<IndexInfo>(),
  );

  Map<String, dynamic> toJson() => {
    if (metadata != null) "metadata": metadata!.map((e) => e.toJson()).toList(),
  };
}

/// The details of the index sync.
class AdminIndexSyncPayload {
  AdminIndexSyncPayload({
    this.strategy,
  });

  /// The syncing strategy. `full` indicates a full reindex, while `reset` truncates tables and performs a fresh sync.
  final String? strategy;

  factory AdminIndexSyncPayload.fromJson(Map<String, dynamic> json) => AdminIndexSyncPayload(
    strategy: json["strategy"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (strategy != null) "strategy": strategy!,
  };
}

/// The details of the payment session to initialize in the payment collection.
class AdminInitializePaymentSession {
  AdminInitializePaymentSession({
    this.providerId,
    this.data,
  });

  /// The ID of the payment provider to initialize the session with.
  final String? providerId;
  /// Any data necessary for the payment provider to process the payment.
  final Map<String, dynamic>? data;

  factory AdminInitializePaymentSession.fromJson(Map<String, dynamic> json) => AdminInitializePaymentSession(
    providerId: json["provider_id"] as String?,
    data: json["data"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (providerId != null) "provider_id": providerId!,
    if (data != null) "data": data!,
  };
}

/// The return receival details.
class AdminInitiateReceiveReturn {
  AdminInitiateReceiveReturn({
    this.internalNote,
    this.description,
    this.metadata,
  });

  /// A note viewed only by admin users.
  final String? internalNote;
  /// The return's description.
  final String? description;
  /// The return's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminInitiateReceiveReturn.fromJson(Map<String, dynamic> json) => AdminInitiateReceiveReturn(
    internalNote: json["internal_note"] as String?,
    description: json["description"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (internalNote != null) "internal_note": internalNote!,
    if (description != null) "description": description!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The return's details.
class AdminInitiateReturnRequest {
  AdminInitiateReturnRequest({
    this.orderId,
    this.locationId,
    this.description,
    this.internalNote,
    this.noNotification,
    this.metadata,
  });

  /// The ID of the order the return belongs to.
  final String? orderId;
  /// The ID of the location the items are returned to.
  final String? locationId;
  /// The return's description.
  final String? description;
  /// A note viewed only by admin users.
  final String? internalNote;
  /// Whether to send the customer a notification about the created return.
  final bool? noNotification;
  /// The return's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminInitiateReturnRequest.fromJson(Map<String, dynamic> json) => AdminInitiateReturnRequest(
    orderId: json["order_id"] as String?,
    locationId: json["location_id"] as String?,
    description: json["description"] as String?,
    internalNote: json["internal_note"] as String?,
    noNotification: json["no_notification"] as bool?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (orderId != null) "order_id": orderId!,
    if (locationId != null) "location_id": locationId!,
    if (description != null) "description": description!,
    if (internalNote != null) "internal_note": internalNote!,
    if (noNotification != null) "no_notification": noNotification!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The inventory item's details.
class AdminInventoryItem {
  AdminInventoryItem({
    this.id,
    this.sku,
    this.originCountry,
    this.hsCode,
    this.requiresShipping,
    this.midCode,
    this.material,
    this.weight,
    this.length,
    this.height,
    this.width,
    this.title,
    this.description,
    this.thumbnail,
    this.metadata,
    this.locationLevels,
    this.stockedQuantity,
    this.reservedQuantity,
  });

  /// The inventory item's ID.
  final String? id;
  /// The inventory item's sku.
  final String? sku;
  /// The inventory item's origin country.
  final String? originCountry;
  /// The inventory item's HS code.
  final String? hsCode;
  /// Whether the inventory item requires shipping.
  final bool? requiresShipping;
  /// The inventory item's MID code.
  final String? midCode;
  /// The inventory item's material.
  final String? material;
  /// The inventory item's weight.
  final num? weight;
  /// The inventory item's length.
  final num? length;
  /// The inventory item's height.
  final num? height;
  /// The inventory item's width.
  final num? width;
  /// The inventory item's title.
  final String? title;
  /// The inventory item's description.
  final String? description;
  /// The thumbnail URL of the inventory item.
  final String? thumbnail;
  /// Custom key-value pairs, used to store additional information about the inventory item.
  final Map<String, dynamic>? metadata;
  /// The inventory item's location levels.
  final List<AdminInventoryLevel>? locationLevels;
  /// The inventory item's stocked quantity.
  final num? stockedQuantity;
  /// The inventory item's reserved quantity.
  final num? reservedQuantity;

  factory AdminInventoryItem.fromJson(Map<String, dynamic> json) => AdminInventoryItem(
    id: json["id"] as String?,
    sku: json["sku"] as String?,
    originCountry: json["origin_country"] as String?,
    hsCode: json["hs_code"] as String?,
    requiresShipping: json["requires_shipping"] as bool?,
    midCode: json["mid_code"] as String?,
    material: json["material"] as String?,
    weight: json["weight"] as num?,
    length: json["length"] as num?,
    height: json["height"] as num?,
    width: json["width"] as num?,
    title: json["title"] as String?,
    description: json["description"] as String?,
    thumbnail: json["thumbnail"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    locationLevels: (json["location_levels"] as List?)?.map((e) => e == null ? null : AdminInventoryLevel.fromJson(e as Map<String, dynamic>)).toList().cast<AdminInventoryLevel>(),
    stockedQuantity: json["stocked_quantity"] as num?,
    reservedQuantity: json["reserved_quantity"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (sku != null) "sku": sku!,
    if (originCountry != null) "origin_country": originCountry!,
    if (hsCode != null) "hs_code": hsCode!,
    if (requiresShipping != null) "requires_shipping": requiresShipping!,
    if (midCode != null) "mid_code": midCode!,
    if (material != null) "material": material!,
    if (weight != null) "weight": weight!,
    if (length != null) "length": length!,
    if (height != null) "height": height!,
    if (width != null) "width": width!,
    if (title != null) "title": title!,
    if (description != null) "description": description!,
    if (thumbnail != null) "thumbnail": thumbnail!,
    if (metadata != null) "metadata": metadata!,
    if (locationLevels != null) "location_levels": locationLevels!.map((e) => e.toJson()).toList(),
    if (stockedQuantity != null) "stocked_quantity": stockedQuantity!,
    if (reservedQuantity != null) "reserved_quantity": reservedQuantity!,
  };
}

/// The inventory item's details.
class AdminInventoryItemResponse {
  AdminInventoryItemResponse({
    this.inventoryItem,
  });

  final AdminInventoryItem? inventoryItem;

  factory AdminInventoryItemResponse.fromJson(Map<String, dynamic> json) => AdminInventoryItemResponse(
    inventoryItem: json["inventory_item"] == null ? null : AdminInventoryItem.fromJson(json["inventory_item"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (inventoryItem != null) "inventory_item": inventoryItem!.toJson(),
  };
}

/// The location level's location levels.
class AdminInventoryLevel {
  AdminInventoryLevel({
    this.id,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.inventoryItemId,
    this.locationId,
    this.stockedQuantity,
    this.reservedQuantity,
    this.incomingQuantity,
    this.metadata,
    this.inventoryItem,
    this.availableQuantity,
  });

  /// The location level's ID.
  final String? id;
  /// The location level's created at.
  final DateTime? createdAt;
  /// The location level's updated at.
  final DateTime? updatedAt;
  /// The location level's deleted at.
  final DateTime? deletedAt;
  /// The location level's inventory item id.
  final String? inventoryItemId;
  /// The location level's location id.
  final String? locationId;
  /// The location level's stocked quantity.
  final num? stockedQuantity;
  /// The location level's reserved quantity.
  final num? reservedQuantity;
  /// The location level's incoming quantity.
  final num? incomingQuantity;
  /// The location level's metadata.
  final Map<String, dynamic>? metadata;
  final Map<String, dynamic>? inventoryItem;
  /// The location level's available quantity.
  final num? availableQuantity;

  factory AdminInventoryLevel.fromJson(Map<String, dynamic> json) => AdminInventoryLevel(
    id: json["id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    inventoryItemId: json["inventory_item_id"] as String?,
    locationId: json["location_id"] as String?,
    stockedQuantity: json["stocked_quantity"] as num?,
    reservedQuantity: json["reserved_quantity"] as num?,
    incomingQuantity: json["incoming_quantity"] as num?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    inventoryItem: json["inventory_item"] as Map<String, dynamic>?,
    availableQuantity: json["available_quantity"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (inventoryItemId != null) "inventory_item_id": inventoryItemId!,
    if (locationId != null) "location_id": locationId!,
    if (stockedQuantity != null) "stocked_quantity": stockedQuantity!,
    if (reservedQuantity != null) "reserved_quantity": reservedQuantity!,
    if (incomingQuantity != null) "incoming_quantity": incomingQuantity!,
    if (metadata != null) "metadata": metadata!,
    if (inventoryItem != null) "inventory_item": inventoryItem!,
    if (availableQuantity != null) "available_quantity": availableQuantity!,
  };
}

/// The invite's details.
class AdminInvite {
  AdminInvite({
    this.id,
    this.email,
    this.accepted,
    this.token,
    this.expiresAt,
    this.metadata,
    this.createdAt,
    this.updatedAt,
  });

  /// The invite's ID.
  final String? id;
  /// The invite's email.
  final String? email;
  /// Whether the invite has been accepted.
  final bool? accepted;
  /// The invite's token.
  final String? token;
  /// The invite's expiry date.
  final DateTime? expiresAt;
  /// The invite's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the invite was created.
  final DateTime? createdAt;
  /// The date the invite was updated.
  final DateTime? updatedAt;

  factory AdminInvite.fromJson(Map<String, dynamic> json) => AdminInvite(
    id: json["id"] as String?,
    email: json["email"] as String?,
    accepted: json["accepted"] as bool?,
    token: json["token"] as String?,
    expiresAt: json["expires_at"] == null ? null : DateTime.parse(json["expires_at"] as String),
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (email != null) "email": email!,
    if (accepted != null) "accepted": accepted!,
    if (token != null) "token": token!,
    if (expiresAt != null) "expires_at": expiresAt!.toIso8601String(),
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
  };
}

/// The invite's details.
class AdminInviteResponse {
  AdminInviteResponse({
    this.invite,
  });

  final AdminInvite? invite;

  factory AdminInviteResponse.fromJson(Map<String, dynamic> json) => AdminInviteResponse(
    invite: json["invite"] == null ? null : AdminInvite.fromJson(json["invite"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (invite != null) "invite": invite!.toJson(),
  };
}

/// The products removal details.
class AdminLinkPriceListProducts {
  AdminLinkPriceListProducts({
    this.remove,
  });

  /// The products to remove from the price list.
  final List<String>? remove;

  factory AdminLinkPriceListProducts.fromJson(Map<String, dynamic> json) => AdminLinkPriceListProducts(
    remove: (json["remove"] as List?)?.map((e) => e as String?).toList().cast<String>(),
  );

  Map<String, dynamic> toJson() => {
    if (remove != null) "remove": remove!.map((e) => e).toList(),
  };
}

/// The locale's details.
class AdminLocale {
  AdminLocale({
    this.code,
    this.name,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The locale's code in BCP 47 format.
  final String? code;
  /// The locale's display name.
  final String? name;
  /// The date and time at which the locale was created.
  final DateTime? createdAt;
  /// The date and time at which the locale was last updated.
  final DateTime? updatedAt;
  /// The date and time at which the locale was deleted.
  final DateTime? deletedAt;

  factory AdminLocale.fromJson(Map<String, dynamic> json) => AdminLocale(
    code: json["code"] as String?,
    name: json["name"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (code != null) "code": code!,
    if (name != null) "name": name!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The list of locales with pagination details.
class AdminLocaleListResponse {
  AdminLocaleListResponse({
    this.limit,
    this.offset,
    this.count,
    this.estimateCount,
    this.locales,
  });

  /// The maximum number of locales returned.
  final num? limit;
  /// The number of locales skipped before retrieving the returned locales.
  final num? offset;
  /// The total number of locales matching the query.
  final num? count;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;
  /// The list of locales.
  final List<AdminLocale>? locales;

  factory AdminLocaleListResponse.fromJson(Map<String, dynamic> json) => AdminLocaleListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    estimateCount: json["estimate_count"] as num?,
    locales: (json["locales"] as List?)?.map((e) => e == null ? null : AdminLocale.fromJson(e as Map<String, dynamic>)).toList().cast<AdminLocale>(),
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (estimateCount != null) "estimate_count": estimateCount!,
    if (locales != null) "locales": locales!.map((e) => e.toJson()).toList(),
  };
}

/// The locale's details.
class AdminLocaleResponse {
  AdminLocaleResponse({
    this.locale,
  });

  final AdminLocale? locale;

  factory AdminLocaleResponse.fromJson(Map<String, dynamic> json) => AdminLocaleResponse(
    locale: json["locale"] == null ? null : AdminLocale.fromJson(json["locale"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (locale != null) "locale": locale!.toJson(),
  };
}

/// The details of marking an order fulfillment as delivered.
class AdminMarkOrderFulfillmentAsDelivered {
  AdminMarkOrderFulfillmentAsDelivered({
    this.noNotification,
  });

  /// Whether to send a notification to the customer about the fulfillment being marked as delivered.
  final bool? noNotification;

  factory AdminMarkOrderFulfillmentAsDelivered.fromJson(Map<String, dynamic> json) => AdminMarkOrderFulfillmentAsDelivered(
    noNotification: json["no_notification"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (noNotification != null) "no_notification": noNotification!,
  };
}
