// GENERATED by tool/generate_models.mjs — do not edit.
part of '../models.dart';

/// The shipping option's details.
class AdminShippingOption {
  AdminShippingOption({
    this.id,
    this.name,
    this.priceType,
    this.serviceZoneId,
    this.serviceZone,
    this.providerId,
    this.provider,
    this.shippingOptionTypeId,
    this.type,
    this.shippingProfileId,
    this.shippingProfile,
    this.rules,
    this.prices,
    this.data,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The shipping option's ID.
  final String? id;
  /// The shipping option's name.
  final String? name;
  /// The shipping option's price type. If it's `flat`, the price is fixed and is set in the `prices` property. If it's `calculated`, the price is calculated on check
  final String? priceType;
  /// The ID of the service zone this option belongs to.
  final String? serviceZoneId;
  final Map<String, dynamic>? serviceZone;
  /// The ID of the provider handling fulfillments created from this shipping option.
  final String? providerId;
  final AdminFulfillmentProvider? provider;
  /// The ID of the associated shipping option type.
  final String? shippingOptionTypeId;
  final AdminShippingOptionType? type;
  /// The ID of the associated shipping profile.
  final String? shippingProfileId;
  final AdminShippingProfile? shippingProfile;
  /// The shipping option's rules.
  final List<AdminShippingOptionRule>? rules;
  /// The shipping option's prices. If the `price_type` is `calculated`, this array will be empty since the price is calculated by the fulfillment provider during che
  final List<AdminShippingOptionPrice>? prices;
  /// The shipping option's data, useful for the fulfillment provider handling fulfillments created from this option.
  final Map<String, dynamic>? data;
  /// The shipping option's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the shipping option was created.
  final DateTime? createdAt;
  /// The date the shipping option was updated.
  final DateTime? updatedAt;
  /// The date the shipping option was deleted.
  final DateTime? deletedAt;

  factory AdminShippingOption.fromJson(Map<String, dynamic> json) => AdminShippingOption(
    id: json["id"] as String?,
    name: json["name"] as String?,
    priceType: json["price_type"] as String?,
    serviceZoneId: json["service_zone_id"] as String?,
    serviceZone: json["service_zone"] as Map<String, dynamic>?,
    providerId: json["provider_id"] as String?,
    provider: json["provider"] == null ? null : AdminFulfillmentProvider.fromJson(json["provider"] as Map<String, dynamic>),
    shippingOptionTypeId: json["shipping_option_type_id"] as String?,
    type: json["type"] == null ? null : AdminShippingOptionType.fromJson(json["type"] as Map<String, dynamic>),
    shippingProfileId: json["shipping_profile_id"] as String?,
    shippingProfile: json["shipping_profile"] == null ? null : AdminShippingProfile.fromJson(json["shipping_profile"] as Map<String, dynamic>),
    rules: (json["rules"] as List?)?.map((e) => e == null ? null : AdminShippingOptionRule.fromJson(e as Map<String, dynamic>)).toList().cast<AdminShippingOptionRule>(),
    prices: (json["prices"] as List?)?.map((e) => e == null ? null : AdminShippingOptionPrice.fromJson(e as Map<String, dynamic>)).toList().cast<AdminShippingOptionPrice>(),
    data: json["data"] as Map<String, dynamic>?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (name != null) "name": name!,
    if (priceType != null) "price_type": priceType!,
    if (serviceZoneId != null) "service_zone_id": serviceZoneId!,
    if (serviceZone != null) "service_zone": serviceZone!,
    if (providerId != null) "provider_id": providerId!,
    if (provider != null) "provider": provider!.toJson(),
    if (shippingOptionTypeId != null) "shipping_option_type_id": shippingOptionTypeId!,
    if (type != null) "type": type!.toJson(),
    if (shippingProfileId != null) "shipping_profile_id": shippingProfileId!,
    if (shippingProfile != null) "shipping_profile": shippingProfile!.toJson(),
    if (rules != null) "rules": rules!.map((e) => e.toJson()).toList(),
    if (prices != null) "prices": prices!.map((e) => e.toJson()).toList(),
    if (data != null) "data": data!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The details of the shipping option's deletion.
class AdminShippingOptionDeleteResponse {
  AdminShippingOptionDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The shipping option's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the shipping option was deleted.
  final bool? deleted;

  factory AdminShippingOptionDeleteResponse.fromJson(Map<String, dynamic> json) => AdminShippingOptionDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The details of the shipping option's price.
class AdminShippingOptionPrice {
  AdminShippingOptionPrice({
    this.priceRules,
    this.rulesCount,
    this.id,
    this.title,
    this.currencyCode,
    this.amount,
    this.rawAmount,
    this.minQuantity,
    this.maxQuantity,
    this.priceSetId,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The price's rules.
  final List<AdminShippingOptionPriceRule>? priceRules;
  /// The number of rules the price has.
  final num? rulesCount;
  /// The price's ID.
  final String? id;
  /// The price's title.
  final String? title;
  /// The price's currency code.
  final String? currencyCode;
  /// The price's amount.
  final num? amount;
  /// The price's raw amount.
  final Map<String, dynamic>? rawAmount;
  /// The minimum quantity required in the cart for this price to apply.
  final num? minQuantity;
  /// The maximum quantity that the cart's items must not surpass for this price to apply.
  final num? maxQuantity;
  /// The ID of the price set this price belongs to.
  final String? priceSetId;
  /// The date the price was created.
  final DateTime? createdAt;
  /// The date the price was updated.
  final DateTime? updatedAt;
  /// The date the price was deleted.
  final DateTime? deletedAt;

  factory AdminShippingOptionPrice.fromJson(Map<String, dynamic> json) => AdminShippingOptionPrice(
    priceRules: (json["price_rules"] as List?)?.map((e) => e == null ? null : AdminShippingOptionPriceRule.fromJson(e as Map<String, dynamic>)).toList().cast<AdminShippingOptionPriceRule>(),
    rulesCount: json["rules_count"] as num?,
    id: json["id"] as String?,
    title: json["title"] as String?,
    currencyCode: json["currency_code"] as String?,
    amount: json["amount"] as num?,
    rawAmount: json["raw_amount"] as Map<String, dynamic>?,
    minQuantity: json["min_quantity"] as num?,
    maxQuantity: json["max_quantity"] as num?,
    priceSetId: json["price_set_id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (priceRules != null) "price_rules": priceRules!.map((e) => e.toJson()).toList(),
    if (rulesCount != null) "rules_count": rulesCount!,
    if (id != null) "id": id!,
    if (title != null) "title": title!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (amount != null) "amount": amount!,
    if (rawAmount != null) "raw_amount": rawAmount!,
    if (minQuantity != null) "min_quantity": minQuantity!,
    if (maxQuantity != null) "max_quantity": maxQuantity!,
    if (priceSetId != null) "price_set_id": priceSetId!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The details of a shipping option price's rule.
class AdminShippingOptionPriceRule {
  AdminShippingOptionPriceRule({
    this.id,
    this.value,
    this.operator,
    this.attribute,
    this.priceId,
    this.priority,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The price rule's ID.
  final String? id;
  /// The price rule's value.
  final dynamic value;
  /// The price rule's operator.
  final String? operator;
  /// The price rule's attribute.
  final String? attribute;
  /// The ID of the price this rule applies to.
  final String? priceId;
  /// The price rule's priority.
  final num? priority;
  /// The date the price rule was created.
  final DateTime? createdAt;
  /// The date the price rule was updated.
  final DateTime? updatedAt;
  /// The date the price rule was deleted.
  final DateTime? deletedAt;

  factory AdminShippingOptionPriceRule.fromJson(Map<String, dynamic> json) => AdminShippingOptionPriceRule(
    id: json["id"] as String?,
    value: json["value"],
    operator: json["operator"] as String?,
    attribute: json["attribute"] as String?,
    priceId: json["price_id"] as String?,
    priority: json["priority"] as num?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (value != null) "value": value!,
    if (operator != null) "operator": operator!,
    if (attribute != null) "attribute": attribute!,
    if (priceId != null) "price_id": priceId!,
    if (priority != null) "priority": priority!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The shipping option's details.
class AdminShippingOptionResponse {
  AdminShippingOptionResponse({
    this.shippingOption,
  });

  final AdminShippingOption? shippingOption;

  factory AdminShippingOptionResponse.fromJson(Map<String, dynamic> json) => AdminShippingOptionResponse(
    shippingOption: json["shipping_option"] == null ? null : AdminShippingOption.fromJson(json["shipping_option"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (shippingOption != null) "shipping_option": shippingOption!.toJson(),
  };
}

/// The shipping option rule's details.
class AdminShippingOptionRule {
  AdminShippingOptionRule({
    this.id,
    this.attribute,
    this.operator,
    this.value,
    this.shippingOptionId,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The shipping option rule's ID.
  final String? id;
  /// The shipping option rule's attribute.
  final String? attribute;
  /// The rule's operator.
  final String? operator;
  final dynamic value;
  /// The ID of the shipping option this rule is for.
  final String? shippingOptionId;
  /// The date the shipping option rule was created.
  final DateTime? createdAt;
  /// The date the shipping option rule was updated.
  final DateTime? updatedAt;
  /// The date the shipping option rule was deleted.
  final DateTime? deletedAt;

  factory AdminShippingOptionRule.fromJson(Map<String, dynamic> json) => AdminShippingOptionRule(
    id: json["id"] as String?,
    attribute: json["attribute"] as String?,
    operator: json["operator"] as String?,
    value: json["value"],
    shippingOptionId: json["shipping_option_id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (attribute != null) "attribute": attribute!,
    if (operator != null) "operator": operator!,
    if (value != null) "value": value!,
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The shipping option's details.
class AdminShippingOptionType {
  AdminShippingOptionType({
    this.id,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.label,
    this.description,
    this.code,
    this.shippingOptionId,
  });

  /// The shipping option's ID.
  final String? id;
  /// The date the shipping option was created.
  final DateTime? createdAt;
  /// The date the shipping option was updated.
  final DateTime? updatedAt;
  /// The date the shipping option was deleted.
  final DateTime? deletedAt;
  /// The type's label.
  final String? label;
  /// The type's description.
  final String? description;
  /// The type's code.
  final String? code;
  /// The type's shipping option id.
  final String? shippingOptionId;

  factory AdminShippingOptionType.fromJson(Map<String, dynamic> json) => AdminShippingOptionType(
    id: json["id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    label: json["label"] as String?,
    description: json["description"] as String?,
    code: json["code"] as String?,
    shippingOptionId: json["shipping_option_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (label != null) "label": label!,
    if (description != null) "description": description!,
    if (code != null) "code": code!,
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
  };
}

/// The response returned after deleting a shipping option type.
class AdminShippingOptionTypeDeleteResponse {
  AdminShippingOptionTypeDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The shipping option type's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the Shipping Option Type was deleted.
  final bool? deleted;

  factory AdminShippingOptionTypeDeleteResponse.fromJson(Map<String, dynamic> json) => AdminShippingOptionTypeDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The paginated list of shipping option types.
class AdminShippingOptionTypeListResponse {
  AdminShippingOptionTypeListResponse({
    this.limit,
    this.offset,
    this.count,
    this.estimateCount,
    this.shippingOptionTypes,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items skipped before returning the results.
  final num? offset;
  /// The total number of items.
  final num? count;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;
  /// The list of shipping option types.
  final List<AdminShippingOptionType>? shippingOptionTypes;

  factory AdminShippingOptionTypeListResponse.fromJson(Map<String, dynamic> json) => AdminShippingOptionTypeListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    estimateCount: json["estimate_count"] as num?,
    shippingOptionTypes: (json["shipping_option_types"] as List?)?.map((e) => e == null ? null : AdminShippingOptionType.fromJson(e as Map<String, dynamic>)).toList().cast<AdminShippingOptionType>(),
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (estimateCount != null) "estimate_count": estimateCount!,
    if (shippingOptionTypes != null) "shipping_option_types": shippingOptionTypes!.map((e) => e.toJson()).toList(),
  };
}

/// The shipping option type's details.
class AdminShippingOptionTypeResponse {
  AdminShippingOptionTypeResponse({
    this.shippingOptionType,
  });

  final AdminShippingOptionType? shippingOptionType;

  factory AdminShippingOptionTypeResponse.fromJson(Map<String, dynamic> json) => AdminShippingOptionTypeResponse(
    shippingOptionType: json["shipping_option_type"] == null ? null : AdminShippingOptionType.fromJson(json["shipping_option_type"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (shippingOptionType != null) "shipping_option_type": shippingOptionType!.toJson(),
  };
}

/// The shipping profile's details..
class AdminShippingProfile {
  AdminShippingProfile({
    this.id,
    this.name,
    this.type,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The shipping profile's ID.
  final String? id;
  /// The shipping profile's name.
  final String? name;
  /// The shipping profile's type.
  final String? type;
  /// The shipping profile's metadata, holds custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the shipping profile was created.
  final DateTime? createdAt;
  /// The date the shipping profile was updated.
  final DateTime? updatedAt;
  /// The date the shipping profile was deleted.
  final DateTime? deletedAt;

  factory AdminShippingProfile.fromJson(Map<String, dynamic> json) => AdminShippingProfile(
    id: json["id"] as String?,
    name: json["name"] as String?,
    type: json["type"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (name != null) "name": name!,
    if (type != null) "type": type!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The details of the shipping profile's deletion.
class AdminShippingProfileDeleteResponse {
  AdminShippingProfileDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The shipping profile's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the shipping profile was deleted.
  final bool? deleted;

  factory AdminShippingProfileDeleteResponse.fromJson(Map<String, dynamic> json) => AdminShippingProfileDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The shipping profile's details.
class AdminShippingProfileResponse {
  AdminShippingProfileResponse({
    this.shippingProfile,
  });

  final AdminShippingProfile? shippingProfile;

  factory AdminShippingProfileResponse.fromJson(Map<String, dynamic> json) => AdminShippingProfileResponse(
    shippingProfile: json["shipping_profile"] == null ? null : AdminShippingProfile.fromJson(json["shipping_profile"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (shippingProfile != null) "shipping_profile": shippingProfile!.toJson(),
  };
}

/// The stock location's details.
class AdminStockLocation {
  AdminStockLocation({
    this.id,
    this.name,
    this.addressId,
    this.address,
    this.salesChannels,
    this.fulfillmentProviders,
    this.fulfillmentSets,
    this.metadata,
  });

  /// The location's ID.
  final String? id;
  /// The location's name.
  final String? name;
  /// The ID of the associated address.
  final String? addressId;
  final AdminStockLocationAddress? address;
  /// The sales channels associated with the location.
  final List<AdminSalesChannel>? salesChannels;
  /// The fulfillment providers associated with the location.
  final List<AdminFulfillmentProvider>? fulfillmentProviders;
  /// The fulfillment sets associated with the location.
  final List<Map<String, dynamic>>? fulfillmentSets;
  /// Key-value pairs of custom data.
  final Map<String, dynamic>? metadata;

  factory AdminStockLocation.fromJson(Map<String, dynamic> json) => AdminStockLocation(
    id: json["id"] as String?,
    name: json["name"] as String?,
    addressId: json["address_id"] as String?,
    address: json["address"] == null ? null : AdminStockLocationAddress.fromJson(json["address"] as Map<String, dynamic>),
    salesChannels: (json["sales_channels"] as List?)?.map((e) => e == null ? null : AdminSalesChannel.fromJson(e as Map<String, dynamic>)).toList().cast<AdminSalesChannel>(),
    fulfillmentProviders: (json["fulfillment_providers"] as List?)?.map((e) => e == null ? null : AdminFulfillmentProvider.fromJson(e as Map<String, dynamic>)).toList().cast<AdminFulfillmentProvider>(),
    fulfillmentSets: (json["fulfillment_sets"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (name != null) "name": name!,
    if (addressId != null) "address_id": addressId!,
    if (address != null) "address": address!.toJson(),
    if (salesChannels != null) "sales_channels": salesChannels!.map((e) => e.toJson()).toList(),
    if (fulfillmentProviders != null) "fulfillment_providers": fulfillmentProviders!.map((e) => e.toJson()).toList(),
    if (fulfillmentSets != null) "fulfillment_sets": fulfillmentSets!.map((e) => e).toList(),
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of the stock location address.
class AdminStockLocationAddress {
  AdminStockLocationAddress({
    this.id,
    this.address1,
    this.address2,
    this.company,
    this.countryCode,
    this.city,
    this.phone,
    this.postalCode,
    this.province,
    this.metadata,
  });

  /// The address's ID.
  final String? id;
  /// The address's first line.
  final String? address1;
  /// The address's second line.
  final String? address2;
  /// The address's company.
  final String? company;
  /// The address's country code.
  final String? countryCode;
  /// The address's city.
  final String? city;
  /// The address's phone.
  final String? phone;
  /// The address's postal code.
  final String? postalCode;
  /// The address's lower-case ISO 3166-2 province code.
  final String? province;
  /// The address's metadata.
  final Map<String, dynamic>? metadata;

  factory AdminStockLocationAddress.fromJson(Map<String, dynamic> json) => AdminStockLocationAddress(
    id: json["id"] as String?,
    address1: json["address_1"] as String?,
    address2: json["address_2"] as String?,
    company: json["company"] as String?,
    countryCode: json["country_code"] as String?,
    city: json["city"] as String?,
    phone: json["phone"] as String?,
    postalCode: json["postal_code"] as String?,
    province: json["province"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (address1 != null) "address_1": address1!,
    if (address2 != null) "address_2": address2!,
    if (company != null) "company": company!,
    if (countryCode != null) "country_code": countryCode!,
    if (city != null) "city": city!,
    if (phone != null) "phone": phone!,
    if (postalCode != null) "postal_code": postalCode!,
    if (province != null) "province": province!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of the stock location's deletion.
class AdminStockLocationDeleteResponse {
  AdminStockLocationDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The stock location's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the stock location was deleted.
  final bool? deleted;

  factory AdminStockLocationDeleteResponse.fromJson(Map<String, dynamic> json) => AdminStockLocationDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The paginated list of stock locations.
class AdminStockLocationListResponse {
  AdminStockLocationListResponse({
    this.limit,
    this.offset,
    this.count,
    this.stockLocations,
    this.estimateCount,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The total number of items.
  final num? count;
  /// The list of stock locations.
  final List<AdminStockLocation>? stockLocations;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory AdminStockLocationListResponse.fromJson(Map<String, dynamic> json) => AdminStockLocationListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    stockLocations: (json["stock_locations"] as List?)?.map((e) => e == null ? null : AdminStockLocation.fromJson(e as Map<String, dynamic>)).toList().cast<AdminStockLocation>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (stockLocations != null) "stock_locations": stockLocations!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The stock location's details.
class AdminStockLocationResponse {
  AdminStockLocationResponse({
    this.stockLocation,
  });

  final AdminStockLocation? stockLocation;

  factory AdminStockLocationResponse.fromJson(Map<String, dynamic> json) => AdminStockLocationResponse(
    stockLocation: json["stock_location"] == null ? null : AdminStockLocation.fromJson(json["stock_location"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (stockLocation != null) "stock_location": stockLocation!.toJson(),
  };
}

/// The store's details.
class AdminStore {
  AdminStore({
    this.id,
    this.name,
    this.supportedCurrencies,
    this.defaultSalesChannelId,
    this.defaultRegionId,
    this.defaultLocationId,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.supportedLocales,
  });

  /// The store's ID.
  final String? id;
  /// The store's name.
  final String? name;
  /// The store's supported currencies.
  final List<AdminStoreCurrency>? supportedCurrencies;
  /// The ID of the sales channel used by default in the store.
  final String? defaultSalesChannelId;
  /// The ID of the region used by default in the store.
  final String? defaultRegionId;
  /// The ID of the stock location used by default in the store.
  final String? defaultLocationId;
  /// The store's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the store was created.
  final DateTime? createdAt;
  /// The date the store was updated.
  final DateTime? updatedAt;
  /// The store's supported locales.
  final List<AdminStoreLocale>? supportedLocales;

  factory AdminStore.fromJson(Map<String, dynamic> json) => AdminStore(
    id: json["id"] as String?,
    name: json["name"] as String?,
    supportedCurrencies: (json["supported_currencies"] as List?)?.map((e) => e == null ? null : AdminStoreCurrency.fromJson(e as Map<String, dynamic>)).toList().cast<AdminStoreCurrency>(),
    defaultSalesChannelId: json["default_sales_channel_id"] as String?,
    defaultRegionId: json["default_region_id"] as String?,
    defaultLocationId: json["default_location_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    supportedLocales: (json["supported_locales"] as List?)?.map((e) => e == null ? null : AdminStoreLocale.fromJson(e as Map<String, dynamic>)).toList().cast<AdminStoreLocale>(),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (name != null) "name": name!,
    if (supportedCurrencies != null) "supported_currencies": supportedCurrencies!.map((e) => e.toJson()).toList(),
    if (defaultSalesChannelId != null) "default_sales_channel_id": defaultSalesChannelId!,
    if (defaultRegionId != null) "default_region_id": defaultRegionId!,
    if (defaultLocationId != null) "default_location_id": defaultLocationId!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (supportedLocales != null) "supported_locales": supportedLocales!.map((e) => e.toJson()).toList(),
  };
}

/// The store credit account's details.
class AdminStoreCreditAccount {
  AdminStoreCreditAccount({
    this.customer,
    this.id,
    this.customerId,
    this.currencyCode,
    this.credits,
    this.debits,
    this.balance,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.code,
  });

  final AdminCustomer? customer;
  /// The store credit account's ID.
  final String? id;
  /// The ID of the customer that the store credit account belongs to.
  final String? customerId;
  /// The store credit account's currency code.
  final String? currencyCode;
  /// The account's credits.
  final num? credits;
  /// The account's debits.
  final num? debits;
  /// The account's balance.
  final num? balance;
  /// The store credit account's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the store credit account was created at.
  final DateTime? createdAt;
  /// The date the store credit account was updated at.
  final DateTime? updatedAt;
  /// The store credit account's code.
  final String? code;

  factory AdminStoreCreditAccount.fromJson(Map<String, dynamic> json) => AdminStoreCreditAccount(
    customer: json["customer"] == null ? null : AdminCustomer.fromJson(json["customer"] as Map<String, dynamic>),
    id: json["id"] as String?,
    customerId: json["customer_id"] as String?,
    currencyCode: json["currency_code"] as String?,
    credits: json["credits"] as num?,
    debits: json["debits"] as num?,
    balance: json["balance"] as num?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    code: json["code"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (customer != null) "customer": customer!.toJson(),
    if (id != null) "id": id!,
    if (customerId != null) "customer_id": customerId!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (credits != null) "credits": credits!,
    if (debits != null) "debits": debits!,
    if (balance != null) "balance": balance!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (code != null) "code": code!,
  };
}

/// The store credit account's details.
class AdminStoreCreditAccountResponse {
  AdminStoreCreditAccountResponse({
    this.storeCreditAccount,
  });

  final AdminStoreCreditAccount? storeCreditAccount;

  factory AdminStoreCreditAccountResponse.fromJson(Map<String, dynamic> json) => AdminStoreCreditAccountResponse(
    storeCreditAccount: json["store_credit_account"] == null ? null : AdminStoreCreditAccount.fromJson(json["store_credit_account"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (storeCreditAccount != null) "store_credit_account": storeCreditAccount!.toJson(),
  };
}

/// The paginated list of store credit accounts.
class AdminStoreCreditAccountsResponse {
  AdminStoreCreditAccountsResponse({
    this.limit,
    this.offset,
    this.count,
    this.storeCreditAccounts,
    this.estimateCount,
  });

  /// The maximum number of store credit accounts to return.
  final num? limit;
  /// The number of store credit accounts to skip before retrieving the results.
  final num? offset;
  /// The total number of store credit accounts available.
  final num? count;
  /// The list of store credit accounts.
  final List<AdminStoreCreditAccount>? storeCreditAccounts;
  /// The store credit account's estimate count.
  final num? estimateCount;

  factory AdminStoreCreditAccountsResponse.fromJson(Map<String, dynamic> json) => AdminStoreCreditAccountsResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    storeCreditAccounts: (json["store_credit_accounts"] as List?)?.map((e) => e == null ? null : AdminStoreCreditAccount.fromJson(e as Map<String, dynamic>)).toList().cast<AdminStoreCreditAccount>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (storeCreditAccounts != null) "store_credit_accounts": storeCreditAccounts!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The details of a store's currency.
class AdminStoreCurrency {
  AdminStoreCurrency({
    this.id,
    this.currencyCode,
    this.storeId,
    this.isDefault,
    this.currency,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The currency's ID.
  final String? id;
  /// The currency's code.
  final String? currencyCode;
  /// The ID of the store this currency belongs to.
  final String? storeId;
  /// Whether this currency is the default in the store.
  final bool? isDefault;
  final AdminCurrency? currency;
  /// The date the currency was created.
  final DateTime? createdAt;
  /// The date the currency was updated.
  final DateTime? updatedAt;
  /// The date the currency was deleted.
  final DateTime? deletedAt;

  factory AdminStoreCurrency.fromJson(Map<String, dynamic> json) => AdminStoreCurrency(
    id: json["id"] as String?,
    currencyCode: json["currency_code"] as String?,
    storeId: json["store_id"] as String?,
    isDefault: json["is_default"] as bool?,
    currency: json["currency"] == null ? null : AdminCurrency.fromJson(json["currency"] as Map<String, dynamic>),
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (storeId != null) "store_id": storeId!,
    if (isDefault != null) "is_default": isDefault!,
    if (currency != null) "currency": currency!.toJson(),
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The paginated list of stores.
class AdminStoreListResponse {
  AdminStoreListResponse({
    this.limit,
    this.offset,
    this.count,
    this.stores,
    this.estimateCount,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The total number of items.
  final num? count;
  /// The list of stores.
  final List<AdminStore>? stores;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory AdminStoreListResponse.fromJson(Map<String, dynamic> json) => AdminStoreListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    stores: (json["stores"] as List?)?.map((e) => e == null ? null : AdminStore.fromJson(e as Map<String, dynamic>)).toList().cast<AdminStore>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (stores != null) "stores": stores!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The details of a store's locale.
class AdminStoreLocale {
  AdminStoreLocale({
    this.id,
    this.localeCode,
    this.storeId,
    this.locale,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The locale's ID.
  final String? id;
  /// The locale's code in BCP 47 format.
  final String? localeCode;
  /// The ID of the store to which the locale belongs.
  final String? storeId;
  final AdminLocale? locale;
  /// The date the locale was created.
  final DateTime? createdAt;
  /// The date the locale was updated.
  final DateTime? updatedAt;
  /// The date the locale was deleted.
  final DateTime? deletedAt;

  factory AdminStoreLocale.fromJson(Map<String, dynamic> json) => AdminStoreLocale(
    id: json["id"] as String?,
    localeCode: json["locale_code"] as String?,
    storeId: json["store_id"] as String?,
    locale: json["locale"] == null ? null : AdminLocale.fromJson(json["locale"] as Map<String, dynamic>),
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (localeCode != null) "locale_code": localeCode!,
    if (storeId != null) "store_id": storeId!,
    if (locale != null) "locale": locale!.toJson(),
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The store's details.
class AdminStoreResponse {
  AdminStoreResponse({
    this.store,
  });

  final AdminStore? store;

  factory AdminStoreResponse.fromJson(Map<String, dynamic> json) => AdminStoreResponse(
    store: json["store"] == null ? null : AdminStore.fromJson(json["store"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (store != null) "store": store!.toJson(),
  };
}

/// The tax provider's details.
class AdminTaxProvider {
  AdminTaxProvider({
    this.id,
    this.isEnabled,
  });

  /// The tax provider's ID.
  final String? id;
  /// Whether the tax provider is enabled in the Medusa application.
  final bool? isEnabled;

  factory AdminTaxProvider.fromJson(Map<String, dynamic> json) => AdminTaxProvider(
    id: json["id"] as String?,
    isEnabled: json["is_enabled"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (isEnabled != null) "is_enabled": isEnabled!,
  };
}

/// The tax rate's details.
class AdminTaxRate {
  AdminTaxRate({
    this.id,
    this.rate,
    this.code,
    this.name,
    this.metadata,
    this.taxRegionId,
    this.isCombinable,
    this.isDefault,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.createdBy,
    this.taxRegion,
    this.rules,
  });

  /// The tax rate's ID.
  final String? id;
  /// The rate to charge.
  final num? rate;
  /// The code the tax rate is identified by.
  final String? code;
  /// The tax rate's name.
  final String? name;
  /// The tax rate's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the tax region this rate belongs to.
  final String? taxRegionId;
  /// Whether the tax rate should be combined with parent rates.
  final bool? isCombinable;
  /// Whether this tax rate is the default in the tax region.
  final bool? isDefault;
  /// The date the tax rate was created.
  final DateTime? createdAt;
  /// The date the tax rate was updated.
  final DateTime? updatedAt;
  /// The date the tax rate was deleted.
  final DateTime? deletedAt;
  /// The ID of the user that created the tax rate.
  final String? createdBy;
  final AdminTaxRegion? taxRegion;
  /// The tax rate's rules.
  final List<AdminTaxRateRule>? rules;

  factory AdminTaxRate.fromJson(Map<String, dynamic> json) => AdminTaxRate(
    id: json["id"] as String?,
    rate: json["rate"] as num?,
    code: json["code"] as String?,
    name: json["name"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    taxRegionId: json["tax_region_id"] as String?,
    isCombinable: json["is_combinable"] as bool?,
    isDefault: json["is_default"] as bool?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    createdBy: json["created_by"] as String?,
    taxRegion: json["tax_region"] == null ? null : AdminTaxRegion.fromJson(json["tax_region"] as Map<String, dynamic>),
    rules: (json["rules"] as List?)?.map((e) => e == null ? null : AdminTaxRateRule.fromJson(e as Map<String, dynamic>)).toList().cast<AdminTaxRateRule>(),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (rate != null) "rate": rate!,
    if (code != null) "code": code!,
    if (name != null) "name": name!,
    if (metadata != null) "metadata": metadata!,
    if (taxRegionId != null) "tax_region_id": taxRegionId!,
    if (isCombinable != null) "is_combinable": isCombinable!,
    if (isDefault != null) "is_default": isDefault!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (createdBy != null) "created_by": createdBy!,
    if (taxRegion != null) "tax_region": taxRegion!.toJson(),
    if (rules != null) "rules": rules!.map((e) => e.toJson()).toList(),
  };
}

/// The details of the tax rate deletion.
class AdminTaxRateDeleteResponse {
  AdminTaxRateDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The tax rate's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the tax rate was deleted.
  final bool? deleted;

  factory AdminTaxRateDeleteResponse.fromJson(Map<String, dynamic> json) => AdminTaxRateDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The tax rate's details.
class AdminTaxRateResponse {
  AdminTaxRateResponse({
    this.taxRate,
  });

  final AdminTaxRate? taxRate;

  factory AdminTaxRateResponse.fromJson(Map<String, dynamic> json) => AdminTaxRateResponse(
    taxRate: json["tax_rate"] == null ? null : AdminTaxRate.fromJson(json["tax_rate"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (taxRate != null) "tax_rate": taxRate!.toJson(),
  };
}

/// The tax rate rule's details.
class AdminTaxRateRule {
  AdminTaxRateRule({
    this.reference,
    this.referenceId,
    this.createdAt,
  });

  /// The name of the table this rule references.
  final String? reference;
  /// The ID of a record in the table that this rule references.
  final String? referenceId;
  /// The date the tax rate rule was created.
  final DateTime? createdAt;

  factory AdminTaxRateRule.fromJson(Map<String, dynamic> json) => AdminTaxRateRule(
    reference: json["reference"] as String?,
    referenceId: json["reference_id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (reference != null) "reference": reference!,
    if (referenceId != null) "reference_id": referenceId!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
  };
}

/// The tax region's details.
class AdminTaxRegion {
  AdminTaxRegion({
    this.id,
    this.countryCode,
    this.provinceCode,
    this.metadata,
    this.parentId,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.createdBy,
    this.taxRates,
    this.parent,
    this.children,
  });

  /// The tax region's ID.
  final String? id;
  /// The tax region's country code.
  final String? countryCode;
  /// The tax region's lower-case ISO 3166-2 province code.
  final String? provinceCode;
  /// The tax region's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the parent tax region.
  final String? parentId;
  /// The date the tax region was created.
  final DateTime? createdAt;
  /// The date the tax region was updated.
  final DateTime? updatedAt;
  /// The date the tax region was deleted.
  final DateTime? deletedAt;
  /// The ID of the user that created the tax region.
  final String? createdBy;
  /// The tax region's rates.
  final List<Map<String, dynamic>>? taxRates;
  final Map<String, dynamic>? parent;
  /// The tax region's children.
  final List<Map<String, dynamic>>? children;

  factory AdminTaxRegion.fromJson(Map<String, dynamic> json) => AdminTaxRegion(
    id: json["id"] as String?,
    countryCode: json["country_code"] as String?,
    provinceCode: json["province_code"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    parentId: json["parent_id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    createdBy: json["created_by"] as String?,
    taxRates: (json["tax_rates"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    parent: json["parent"] as Map<String, dynamic>?,
    children: (json["children"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (countryCode != null) "country_code": countryCode!,
    if (provinceCode != null) "province_code": provinceCode!,
    if (metadata != null) "metadata": metadata!,
    if (parentId != null) "parent_id": parentId!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (createdBy != null) "created_by": createdBy!,
    if (taxRates != null) "tax_rates": taxRates!.map((e) => e).toList(),
    if (parent != null) "parent": parent!,
    if (children != null) "children": children!.map((e) => e).toList(),
  };
}

/// The details of the tax region deletion.
class AdminTaxRegionDeleteResponse {
  AdminTaxRegionDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The tax region's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the tax region was deleted.
  final bool? deleted;

  factory AdminTaxRegionDeleteResponse.fromJson(Map<String, dynamic> json) => AdminTaxRegionDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The tax region's details.
class AdminTaxRegionResponse {
  AdminTaxRegionResponse({
    this.taxRegion,
  });

  final AdminTaxRegion? taxRegion;

  factory AdminTaxRegionResponse.fromJson(Map<String, dynamic> json) => AdminTaxRegionResponse(
    taxRegion: json["tax_region"] == null ? null : AdminTaxRegion.fromJson(json["tax_region"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (taxRegion != null) "tax_region": taxRegion!.toJson(),
  };
}

/// The transaction's details.
class AdminTransaction {
  AdminTransaction({
    this.id,
    this.accountId,
    this.type,
    this.amount,
    this.account,
    this.note,
    this.reference,
    this.referenceId,
    this.metadata,
    this.createdAt,
    this.updatedAt,
  });

  /// The transaction's ID.
  final String? id;
  /// The ID of the store credit account that the transaction belongs to.
  final String? accountId;
  /// The transaction's type.
  final String? type;
  /// The transaction's amount.
  final num? amount;
  final AdminStoreCreditAccount? account;
  /// The transaction's note.
  final String? note;
  /// The transaction's reference.
  final String? reference;
  /// The transaction's reference ID.
  final String? referenceId;
  /// The transaction's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the transaction was created at.
  final DateTime? createdAt;
  /// The date the transaction was updated at.
  final DateTime? updatedAt;

  factory AdminTransaction.fromJson(Map<String, dynamic> json) => AdminTransaction(
    id: json["id"] as String?,
    accountId: json["account_id"] as String?,
    type: json["type"] as String?,
    amount: json["amount"] as num?,
    account: json["account"] == null ? null : AdminStoreCreditAccount.fromJson(json["account"] as Map<String, dynamic>),
    note: json["note"] as String?,
    reference: json["reference"] as String?,
    referenceId: json["reference_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (accountId != null) "account_id": accountId!,
    if (type != null) "type": type!,
    if (amount != null) "amount": amount!,
    if (account != null) "account": account!.toJson(),
    if (note != null) "note": note!,
    if (reference != null) "reference": reference!,
    if (referenceId != null) "reference_id": referenceId!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
  };
}

/// The paginated list of transactions.
class AdminTransactionsResponse {
  AdminTransactionsResponse({
    this.limit,
    this.offset,
    this.count,
    this.transactions,
    this.estimateCount,
  });

  /// The maximum number of transactions to return.
  final num? limit;
  /// The number of transactions to skip before retrieving the results.
  final num? offset;
  /// The total number of transactions available.
  final num? count;
  /// The list of transactions.
  final List<AdminTransaction>? transactions;
  /// The store credit account's estimate count.
  final num? estimateCount;

  factory AdminTransactionsResponse.fromJson(Map<String, dynamic> json) => AdminTransactionsResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    transactions: (json["transactions"] as List?)?.map((e) => e == null ? null : AdminTransaction.fromJson(e as Map<String, dynamic>)).toList().cast<AdminTransaction>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (transactions != null) "transactions": transactions!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The translation's details.
class AdminTranslation {
  AdminTranslation({
    this.id,
    this.referenceId,
    this.reference,
    this.localeCode,
    this.translations,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The translation's ID.
  final String? id;
  /// The ID of the resource that the translation belongs to. For example, the ID of a product.
  final String? referenceId;
  /// The resource that the translation belongs to.
  final String? reference;
  /// The translation's locale code in BCP 47 format.
  final String? localeCode;
  /// The translation key-value pairs. Each key is a field in the resource, and the value is the translated text.
  final Map<String, dynamic>? translations;
  /// The date that the translation was created.
  final DateTime? createdAt;
  /// The date that the translation was updated.
  final DateTime? updatedAt;
  /// The date that the translation was deleted.
  final DateTime? deletedAt;

  factory AdminTranslation.fromJson(Map<String, dynamic> json) => AdminTranslation(
    id: json["id"] as String?,
    referenceId: json["reference_id"] as String?,
    reference: json["reference"] as String?,
    localeCode: json["locale_code"] as String?,
    translations: json["translations"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (referenceId != null) "reference_id": referenceId!,
    if (reference != null) "reference": reference!,
    if (localeCode != null) "locale_code": localeCode!,
    if (translations != null) "translations": translations!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The list of translatable entities.
class AdminTranslationEntitiesResponse {
  AdminTranslationEntitiesResponse({
    this.data,
    this.count,
    this.offset,
    this.limit,
  });

  /// The list of translatable entities.
  final List<Map<String, dynamic>>? data;
  /// The total number of translatable entities.
  final num? count;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The maximum number of items returned in the response.
  final num? limit;

  factory AdminTranslationEntitiesResponse.fromJson(Map<String, dynamic> json) => AdminTranslationEntitiesResponse(
    data: (json["data"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    count: json["count"] as num?,
    offset: json["offset"] as num?,
    limit: json["limit"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (data != null) "data": data!.map((e) => e).toList(),
    if (count != null) "count": count!,
    if (offset != null) "offset": offset!,
    if (limit != null) "limit": limit!,
  };
}

/// The translation settings details.
class AdminTranslationSettings {
  AdminTranslationSettings({
    this.id,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.entityType,
    this.fields,
    this.isActive,
  });

  /// The ID of the translation settings.
  final String? id;
  /// The date the translation settings was created.
  final DateTime? createdAt;
  /// The date the translation settings was updated.
  final DateTime? updatedAt;
  /// The date the translation settings was deleted.
  final DateTime? deletedAt;
  /// The entity type the translation settings are for.
  final String? entityType;
  /// The fields supported for translations.
  final List<String>? fields;
  /// Whether translations are active for the given entity type.
  final bool? isActive;

  factory AdminTranslationSettings.fromJson(Map<String, dynamic> json) => AdminTranslationSettings(
    id: json["id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    entityType: json["entity_type"] as String?,
    fields: (json["fields"] as List?)?.map((e) => e as String?).toList().cast<String>(),
    isActive: json["is_active"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (entityType != null) "entity_type": entityType!,
    if (fields != null) "fields": fields!.map((e) => e).toList(),
    if (isActive != null) "is_active": isActive!,
  };
}

/// The translation settings' details.
class AdminTranslationSettingsResponse {
  AdminTranslationSettingsResponse({
    this.translationSettings,
  });

  /// The translation settings details.
  final Map<String, dynamic>? translationSettings;

  factory AdminTranslationSettingsResponse.fromJson(Map<String, dynamic> json) => AdminTranslationSettingsResponse(
    translationSettings: json["translation_settings"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (translationSettings != null) "translation_settings": translationSettings!,
  };
}

/// The translation statistics details.
class AdminTranslationStatisticsResponse {
  AdminTranslationStatisticsResponse({
    this.statistics,
  });

  /// The translation statistics for different entity types. The key is the entity type, and the value is an object containing the statistics for that entity type.
  final Map<String, dynamic>? statistics;

  factory AdminTranslationStatisticsResponse.fromJson(Map<String, dynamic> json) => AdminTranslationStatisticsResponse(
    statistics: json["statistics"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (statistics != null) "statistics": statistics!,
  };
}

/// The batch response for managing translations.
class AdminTranslationsBatchResponse {
  AdminTranslationsBatchResponse({
    this.created,
    this.updated,
    this.deleted,
  });

  /// The created translations.
  final List<AdminTranslation>? created;
  /// The updated translations.
  final List<AdminTranslation>? updated;
  /// Summary of the deleted translations.
  final Map<String, dynamic>? deleted;

  factory AdminTranslationsBatchResponse.fromJson(Map<String, dynamic> json) => AdminTranslationsBatchResponse(
    created: (json["created"] as List?)?.map((e) => e == null ? null : AdminTranslation.fromJson(e as Map<String, dynamic>)).toList().cast<AdminTranslation>(),
    updated: (json["updated"] as List?)?.map((e) => e == null ? null : AdminTranslation.fromJson(e as Map<String, dynamic>)).toList().cast<AdminTranslation>(),
    deleted: json["deleted"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (created != null) "created": created!.map((e) => e.toJson()).toList(),
    if (updated != null) "updated": updated!.map((e) => e.toJson()).toList(),
    if (deleted != null) "deleted": deleted!,
  };
}

/// The details to update in an API key.
class AdminUpdateApiKey {
  AdminUpdateApiKey({
    this.title,
  });

  /// The API key's title.
  final String? title;

  factory AdminUpdateApiKey.fromJson(Map<String, dynamic> json) => AdminUpdateApiKey(
    title: json["title"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
  };
}

/// The details to update in the item.
class AdminUpdateClaimItem {
  AdminUpdateClaimItem({
    this.quantity,
    this.reasonId,
    this.internalNote,
  });

  /// The item's quantity.
  final num? quantity;
  /// The ID of the return reason associated with the item.
  final String? reasonId;
  /// A note that's only viewed by admin users.
  final String? internalNote;

  factory AdminUpdateClaimItem.fromJson(Map<String, dynamic> json) => AdminUpdateClaimItem(
    quantity: json["quantity"] as num?,
    reasonId: json["reason_id"] as String?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (reasonId != null) "reason_id": reasonId!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// The details to update in the item.
class AdminUpdateClaimOutboundItem {
  AdminUpdateClaimOutboundItem({
    this.quantity,
    this.reasonId,
    this.internalNote,
  });

  /// The item's quantity.
  final num? quantity;
  /// The ID of the return reason associated with the item.
  final String? reasonId;
  /// A note that's only viewed by admin users.
  final String? internalNote;

  factory AdminUpdateClaimOutboundItem.fromJson(Map<String, dynamic> json) => AdminUpdateClaimOutboundItem(
    quantity: json["quantity"] as num?,
    reasonId: json["reason_id"] as String?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (reasonId != null) "reason_id": reasonId!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// The details to update in a customer group.
class AdminUpdateCustomerGroup {
  AdminUpdateCustomerGroup({
    this.name,
    this.metadata,
  });

  /// The customer group's name.
  final String? name;
  /// The customer group's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateCustomerGroup.fromJson(Map<String, dynamic> json) => AdminUpdateCustomerGroup(
    name: json["name"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The data to update in the draft order.
class AdminUpdateDraftOrder {
  AdminUpdateDraftOrder({
    this.email,
    this.shippingAddress,
    this.billingAddress,
    this.metadata,
    this.customerId,
    this.salesChannelId,
    this.locale,
  });

  /// The customer email associated with the draft order.
  final String? email;
  final OrderAddress? shippingAddress;
  final OrderAddress? billingAddress;
  /// The draft order's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the customer associated with the draft order.
  final String? customerId;
  /// The ID of the sales channel associated with the draft order.
  final String? salesChannelId;
  /// The draft order's locale.
  final String? locale;

  factory AdminUpdateDraftOrder.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrder(
    email: json["email"] as String?,
    shippingAddress: json["shipping_address"] == null ? null : OrderAddress.fromJson(json["shipping_address"] as Map<String, dynamic>),
    billingAddress: json["billing_address"] == null ? null : OrderAddress.fromJson(json["billing_address"] as Map<String, dynamic>),
    metadata: json["metadata"] as Map<String, dynamic>?,
    customerId: json["customer_id"] as String?,
    salesChannelId: json["sales_channel_id"] as String?,
    locale: json["locale"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (email != null) "email": email!,
    if (shippingAddress != null) "shipping_address": shippingAddress!.toJson(),
    if (billingAddress != null) "billing_address": billingAddress!.toJson(),
    if (metadata != null) "metadata": metadata!,
    if (customerId != null) "customer_id": customerId!,
    if (salesChannelId != null) "sales_channel_id": salesChannelId!,
    if (locale != null) "locale": locale!,
  };
}

/// The updates to make on a draft order's item.
class AdminUpdateDraftOrderActionItem {
  AdminUpdateDraftOrderActionItem({
    this.quantity,
    this.unitPrice,
    this.compareAtUnitPrice,
    this.internalNote,
  });

  /// The item's quantity.
  final num? quantity;
  /// The item's unit price.
  final num? unitPrice;
  /// The original price of the item before a promotion or sale.
  final num? compareAtUnitPrice;
  /// A note viewed only by admin users about the item.
  final String? internalNote;

  factory AdminUpdateDraftOrderActionItem.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrderActionItem(
    quantity: json["quantity"] as num?,
    unitPrice: json["unit_price"] as num?,
    compareAtUnitPrice: json["compare_at_unit_price"] as num?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (unitPrice != null) "unit_price": unitPrice!,
    if (compareAtUnitPrice != null) "compare_at_unit_price": compareAtUnitPrice!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// The updates to make on a changed shipping method.
class AdminUpdateDraftOrderActionShippingMethod {
  AdminUpdateDraftOrderActionShippingMethod({
    this.shippingOptionId,
    this.customAmount,
    this.description,
    this.internalNote,
    this.metadata,
  });

  /// The ID of the associated shipping option.
  final String? shippingOptionId;
  /// The custom amount of the shipping method. If not provided, the shipping option's amount will be used.
  final num? customAmount;
  /// The shipping method's description.
  final String? description;
  /// A note viewed only by admin users about the shipping method.
  final String? internalNote;
  /// The shipping method's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateDraftOrderActionShippingMethod.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrderActionShippingMethod(
    shippingOptionId: json["shipping_option_id"] as String?,
    customAmount: json["custom_amount"] as num?,
    description: json["description"] as String?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (customAmount != null) "custom_amount": customAmount!,
    if (description != null) "description": description!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The updates to make on a draft order's item.
class AdminUpdateDraftOrderItem {
  AdminUpdateDraftOrderItem({
    this.quantity,
    this.unitPrice,
    this.compareAtUnitPrice,
    this.internalNote,
    this.metadata,
  });

  /// The item's quantity.
  final num? quantity;
  /// The item's unit price.
  final num? unitPrice;
  /// The original price of the item before a promotion or sale.
  final num? compareAtUnitPrice;
  /// A note viewed only by admin users about the item.
  final String? internalNote;
  /// Key-value pairs of custom data.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateDraftOrderItem.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrderItem(
    quantity: json["quantity"] as num?,
    unitPrice: json["unit_price"] as num?,
    compareAtUnitPrice: json["compare_at_unit_price"] as num?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (unitPrice != null) "unit_price": unitPrice!,
    if (compareAtUnitPrice != null) "compare_at_unit_price": compareAtUnitPrice!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The updates to make on a draft order's shipping method.
class AdminUpdateDraftOrderShippingMethod {
  AdminUpdateDraftOrderShippingMethod({
    this.shippingOptionId,
    this.customAmount,
    this.internalNote,
  });

  /// The ID of the associated shipping option.
  final String? shippingOptionId;
  /// The custom amount of the shipping method. If not provided, the shipping option's amount will be used.
  final num? customAmount;
  /// A note viewed only by admin users about the shipping method.
  final String? internalNote;

  factory AdminUpdateDraftOrderShippingMethod.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrderShippingMethod(
    shippingOptionId: json["shipping_option_id"] as String?,
    customAmount: json["custom_amount"] as num?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (customAmount != null) "custom_amount": customAmount!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// The details to update in an outbound item.
class AdminUpdateExchangeOutboundItem {
  AdminUpdateExchangeOutboundItem({
    this.quantity,
    this.internalNote,
  });

  /// The item's quantity.
  final num? quantity;
  /// A note only viewed by admin users.
  final String? internalNote;

  factory AdminUpdateExchangeOutboundItem.fromJson(Map<String, dynamic> json) => AdminUpdateExchangeOutboundItem(
    quantity: json["quantity"] as num?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// The service zone's details.
class AdminUpdateFulfillmentSetServiceZone {
  AdminUpdateFulfillmentSetServiceZone({
    this.name,
    this.geoZones,
  });

  /// The service zone's name.
  final String? name;
  /// The service zone's associated geo zones.
  final List<dynamic>? geoZones;

  factory AdminUpdateFulfillmentSetServiceZone.fromJson(Map<String, dynamic> json) => AdminUpdateFulfillmentSetServiceZone(
    name: json["name"] as String?,
    geoZones: (json["geo_zones"] as List?)?.map((e) => e).toList().cast<dynamic>(),
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (geoZones != null) "geo_zones": geoZones!.map((e) => e).toList(),
  };
}

/// The details to update in the gift card.
class AdminUpdateGiftCardParams {
  AdminUpdateGiftCardParams({
    this.status,
    this.value,
    this.customerId,
    this.currencyCode,
    this.note,
    this.expiresAt,
    this.metadata,
  });

  /// The gift card's status.
  final String? status;
  /// The gift card's amount.
  final num? value;
  /// The ID of the customer that the gift card belongs to.
  final String? customerId;
  /// The gift card's currency code.
  final String? currencyCode;
  /// The gift card's note.
  final String? note;
  /// The date the gift card expires at.
  final String? expiresAt;
  /// The gift card's metadata.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateGiftCardParams.fromJson(Map<String, dynamic> json) => AdminUpdateGiftCardParams(
    status: json["status"] as String?,
    value: json["value"] as num?,
    customerId: json["customer_id"] as String?,
    currencyCode: json["currency_code"] as String?,
    note: json["note"] as String?,
    expiresAt: json["expires_at"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (status != null) "status": status!,
    if (value != null) "value": value!,
    if (customerId != null) "customer_id": customerId!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (note != null) "note": note!,
    if (expiresAt != null) "expires_at": expiresAt!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in the inventory item.
class AdminUpdateInventoryItem {
  AdminUpdateInventoryItem({
    this.sku,
    this.hsCode,
    this.weight,
    this.length,
    this.height,
    this.width,
    this.originCountry,
    this.midCode,
    this.material,
    this.title,
    this.description,
    this.requiresShipping,
    this.thumbnail,
    this.metadata,
  });

  /// The inventory item's SKU.
  final String? sku;
  /// The inventory item's HS code.
  final String? hsCode;
  /// The inventory item's weight.
  final num? weight;
  /// The inventory item's length.
  final num? length;
  /// The inventory item's height.
  final num? height;
  /// The inventory item's width.
  final num? width;
  /// The inventory item's origin country.
  final String? originCountry;
  /// The inventory item's MID code.
  final String? midCode;
  /// The inventory item's material.
  final String? material;
  /// The inventory item's title.
  final String? title;
  /// The inventory item's description.
  final String? description;
  /// Whether the inventory item requires shipping.
  final bool? requiresShipping;
  /// The URL of an image to be used as the inventory item's thumbnail. You can use the Upload API routes to upload an image and get its URL.
  final String? thumbnail;
  /// The inventory item's metadata. Can be custom data in key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateInventoryItem.fromJson(Map<String, dynamic> json) => AdminUpdateInventoryItem(
    sku: json["sku"] as String?,
    hsCode: json["hs_code"] as String?,
    weight: json["weight"] as num?,
    length: json["length"] as num?,
    height: json["height"] as num?,
    width: json["width"] as num?,
    originCountry: json["origin_country"] as String?,
    midCode: json["mid_code"] as String?,
    material: json["material"] as String?,
    title: json["title"] as String?,
    description: json["description"] as String?,
    requiresShipping: json["requires_shipping"] as bool?,
    thumbnail: json["thumbnail"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (sku != null) "sku": sku!,
    if (hsCode != null) "hs_code": hsCode!,
    if (weight != null) "weight": weight!,
    if (length != null) "length": length!,
    if (height != null) "height": height!,
    if (width != null) "width": width!,
    if (originCountry != null) "origin_country": originCountry!,
    if (midCode != null) "mid_code": midCode!,
    if (material != null) "material": material!,
    if (title != null) "title": title!,
    if (description != null) "description": description!,
    if (requiresShipping != null) "requires_shipping": requiresShipping!,
    if (thumbnail != null) "thumbnail": thumbnail!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in the inventory level.
class AdminUpdateInventoryLevel {
  AdminUpdateInventoryLevel({
    this.stockedQuantity,
    this.incomingQuantity,
  });

  /// The inventory level's stocked quantity.
  final num? stockedQuantity;
  /// The inventory level's incoming quantity.
  final num? incomingQuantity;

  factory AdminUpdateInventoryLevel.fromJson(Map<String, dynamic> json) => AdminUpdateInventoryLevel(
    stockedQuantity: json["stocked_quantity"] as num?,
    incomingQuantity: json["incoming_quantity"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (stockedQuantity != null) "stocked_quantity": stockedQuantity!,
    if (incomingQuantity != null) "incoming_quantity": incomingQuantity!,
  };
}

/// The details to update in the order.
class AdminUpdateOrder {
  AdminUpdateOrder({
    this.email,
    this.shippingAddress,
    this.billingAddress,
    this.metadata,
    this.locale,
  });

  /// The order's email.
  final String? email;
  final OrderAddress? shippingAddress;
  final OrderAddress? billingAddress;
  /// The order's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The order's locale in [BCP 47](https://gist.github.com/typpo/b2b828a35e683b9bf8db91b5404f1bd1) format.
  final String? locale;

  factory AdminUpdateOrder.fromJson(Map<String, dynamic> json) => AdminUpdateOrder(
    email: json["email"] as String?,
    shippingAddress: json["shipping_address"] == null ? null : OrderAddress.fromJson(json["shipping_address"] as Map<String, dynamic>),
    billingAddress: json["billing_address"] == null ? null : OrderAddress.fromJson(json["billing_address"] as Map<String, dynamic>),
    metadata: json["metadata"] as Map<String, dynamic>?,
    locale: json["locale"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (email != null) "email": email!,
    if (shippingAddress != null) "shipping_address": shippingAddress!.toJson(),
    if (billingAddress != null) "billing_address": billingAddress!.toJson(),
    if (metadata != null) "metadata": metadata!,
    if (locale != null) "locale": locale!,
  };
}

/// The data to update in the order change.
class AdminUpdateOrderChange {
  AdminUpdateOrderChange({
    this.carryOverPromotions,
    this.internalNote,
  });

  /// Whether promotions from the original order should be carried over to the order change (specifically, exchanges).
  final bool? carryOverPromotions;
  /// The order change's internal note.
  final String? internalNote;

  factory AdminUpdateOrderChange.fromJson(Map<String, dynamic> json) => AdminUpdateOrderChange(
    carryOverPromotions: json["carry_over_promotions"] as bool?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (carryOverPromotions != null) "carry_over_promotions": carryOverPromotions!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// the details to update in a price list.
class AdminUpdatePriceList {
  AdminUpdatePriceList({
    this.title,
    this.description,
    this.startsAt,
    this.endsAt,
    this.status,
    this.type,
    this.rules,
    this.metadata,
  });

  /// The price list's title.
  final String? title;
  /// The price list's description.
  final String? description;
  /// The date the price list starts.
  final String? startsAt;
  /// The date the price list ends.
  final String? endsAt;
  /// The price list's status.
  final String? status;
  /// The price list's type.
  final String? type;
  /// The price list's rules.
  final Map<String, dynamic>? rules;
  /// Key-value pairs of custom data.
  final Map<String, dynamic>? metadata;

  factory AdminUpdatePriceList.fromJson(Map<String, dynamic> json) => AdminUpdatePriceList(
    title: json["title"] as String?,
    description: json["description"] as String?,
    startsAt: json["starts_at"] as String?,
    endsAt: json["ends_at"] as String?,
    status: json["status"] as String?,
    type: json["type"] as String?,
    rules: json["rules"] as Map<String, dynamic>?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (description != null) "description": description!,
    if (startsAt != null) "starts_at": startsAt!,
    if (endsAt != null) "ends_at": endsAt!,
    if (status != null) "status": status!,
    if (type != null) "type": type!,
    if (rules != null) "rules": rules!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details to update in the price preference.
class AdminUpdatePricePreference {
  AdminUpdatePricePreference({
    this.attribute,
    this.value,
    this.isTaxInclusive,
  });

  /// The price preference's attribute.
  final String? attribute;
  /// The price preference's value.
  final String? value;
  /// Whether prices are tax inclusive for this price preference.
  final bool? isTaxInclusive;

  factory AdminUpdatePricePreference.fromJson(Map<String, dynamic> json) => AdminUpdatePricePreference(
    attribute: json["attribute"] as String?,
    value: json["value"] as String?,
    isTaxInclusive: json["is_tax_inclusive"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (attribute != null) "attribute": attribute!,
    if (value != null) "value": value!,
    if (isTaxInclusive != null) "is_tax_inclusive": isTaxInclusive!,
  };
}
