// GENERATED by tool/generate_models.mjs — do not edit.
part of '../models.dart';

/// The data to update in the draft order.
class AdminUpdateDraftOrder {
  AdminUpdateDraftOrder({
    this.email,
    this.shippingAddress,
    this.billingAddress,
    this.metadata,
    this.customerId,
    this.salesChannelId,
    this.locale,
  });

  /// The customer email associated with the draft order.
  final String? email;
  final OrderAddress? shippingAddress;
  final OrderAddress? billingAddress;
  /// The draft order's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the customer associated with the draft order.
  final String? customerId;
  /// The ID of the sales channel associated with the draft order.
  final String? salesChannelId;
  /// The draft order's locale.
  final String? locale;

  factory AdminUpdateDraftOrder.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrder(
    email: json["email"] as String?,
    shippingAddress: json["shipping_address"] == null ? null : OrderAddress.fromJson(json["shipping_address"] as Map<String, dynamic>),
    billingAddress: json["billing_address"] == null ? null : OrderAddress.fromJson(json["billing_address"] as Map<String, dynamic>),
    metadata: json["metadata"] as Map<String, dynamic>?,
    customerId: json["customer_id"] as String?,
    salesChannelId: json["sales_channel_id"] as String?,
    locale: json["locale"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (email != null) "email": email!,
    if (shippingAddress != null) "shipping_address": shippingAddress!.toJson(),
    if (billingAddress != null) "billing_address": billingAddress!.toJson(),
    if (metadata != null) "metadata": metadata!,
    if (customerId != null) "customer_id": customerId!,
    if (salesChannelId != null) "sales_channel_id": salesChannelId!,
    if (locale != null) "locale": locale!,
  };
}

/// The updates to make on a draft order's item.
class AdminUpdateDraftOrderActionItem {
  AdminUpdateDraftOrderActionItem({
    this.quantity,
    this.unitPrice,
    this.compareAtUnitPrice,
    this.internalNote,
  });

  /// The item's quantity.
  final num? quantity;
  /// The item's unit price.
  final num? unitPrice;
  /// The original price of the item before a promotion or sale.
  final num? compareAtUnitPrice;
  /// A note viewed only by admin users about the item.
  final String? internalNote;

  factory AdminUpdateDraftOrderActionItem.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrderActionItem(
    quantity: json["quantity"] as num?,
    unitPrice: json["unit_price"] as num?,
    compareAtUnitPrice: json["compare_at_unit_price"] as num?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (unitPrice != null) "unit_price": unitPrice!,
    if (compareAtUnitPrice != null) "compare_at_unit_price": compareAtUnitPrice!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// The updates to make on a changed shipping method.
class AdminUpdateDraftOrderActionShippingMethod {
  AdminUpdateDraftOrderActionShippingMethod({
    this.shippingOptionId,
    this.customAmount,
    this.description,
    this.internalNote,
    this.metadata,
  });

  /// The ID of the associated shipping option.
  final String? shippingOptionId;
  /// The custom amount of the shipping method. If not provided, the shipping option's amount will be used.
  final num? customAmount;
  /// The shipping method's description.
  final String? description;
  /// A note viewed only by admin users about the shipping method.
  final String? internalNote;
  /// The shipping method's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateDraftOrderActionShippingMethod.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrderActionShippingMethod(
    shippingOptionId: json["shipping_option_id"] as String?,
    customAmount: json["custom_amount"] as num?,
    description: json["description"] as String?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (customAmount != null) "custom_amount": customAmount!,
    if (description != null) "description": description!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The updates to make on a draft order's item.
class AdminUpdateDraftOrderItem {
  AdminUpdateDraftOrderItem({
    this.quantity,
    this.unitPrice,
    this.compareAtUnitPrice,
    this.internalNote,
    this.metadata,
  });

  /// The item's quantity.
  final num? quantity;
  /// The item's unit price.
  final num? unitPrice;
  /// The original price of the item before a promotion or sale.
  final num? compareAtUnitPrice;
  /// A note viewed only by admin users about the item.
  final String? internalNote;
  /// Key-value pairs of custom data.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateDraftOrderItem.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrderItem(
    quantity: json["quantity"] as num?,
    unitPrice: json["unit_price"] as num?,
    compareAtUnitPrice: json["compare_at_unit_price"] as num?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (unitPrice != null) "unit_price": unitPrice!,
    if (compareAtUnitPrice != null) "compare_at_unit_price": compareAtUnitPrice!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The updates to make on a draft order's shipping method.
class AdminUpdateDraftOrderShippingMethod {
  AdminUpdateDraftOrderShippingMethod({
    this.shippingOptionId,
    this.customAmount,
    this.internalNote,
  });

  /// The ID of the associated shipping option.
  final String? shippingOptionId;
  /// The custom amount of the shipping method. If not provided, the shipping option's amount will be used.
  final num? customAmount;
  /// A note viewed only by admin users about the shipping method.
  final String? internalNote;

  factory AdminUpdateDraftOrderShippingMethod.fromJson(Map<String, dynamic> json) => AdminUpdateDraftOrderShippingMethod(
    shippingOptionId: json["shipping_option_id"] as String?,
    customAmount: json["custom_amount"] as num?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (customAmount != null) "custom_amount": customAmount!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// The details to update in an outbound item.
class AdminUpdateExchangeOutboundItem {
  AdminUpdateExchangeOutboundItem({
    this.quantity,
    this.internalNote,
  });

  /// The item's quantity.
  final num? quantity;
  /// A note only viewed by admin users.
  final String? internalNote;

  factory AdminUpdateExchangeOutboundItem.fromJson(Map<String, dynamic> json) => AdminUpdateExchangeOutboundItem(
    quantity: json["quantity"] as num?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// The service zone's details.
class AdminUpdateFulfillmentSetServiceZone {
  AdminUpdateFulfillmentSetServiceZone({
    this.name,
    this.geoZones,
  });

  /// The service zone's name.
  final String? name;
  /// The service zone's associated geo zones.
  final List<dynamic>? geoZones;

  factory AdminUpdateFulfillmentSetServiceZone.fromJson(Map<String, dynamic> json) => AdminUpdateFulfillmentSetServiceZone(
    name: json["name"] as String?,
    geoZones: (json["geo_zones"] as List?)?.map((e) => e).toList().cast<dynamic>(),
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (geoZones != null) "geo_zones": geoZones!.map((e) => e).toList(),
  };
}

/// The details to update in the gift card.
class AdminUpdateGiftCardParams {
  AdminUpdateGiftCardParams({
    this.status,
    this.value,
    this.customerId,
    this.currencyCode,
    this.note,
    this.expiresAt,
    this.metadata,
  });

  /// The gift card's status.
  final String? status;
  /// The gift card's amount.
  final num? value;
  /// The ID of the customer that the gift card belongs to.
  final String? customerId;
  /// The gift card's currency code.
  final String? currencyCode;
  /// The gift card's note.
  final String? note;
  /// The date the gift card expires at.
  final String? expiresAt;
  /// The gift card's metadata.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateGiftCardParams.fromJson(Map<String, dynamic> json) => AdminUpdateGiftCardParams(
    status: json["status"] as String?,
    value: json["value"] as num?,
    customerId: json["customer_id"] as String?,
    currencyCode: json["currency_code"] as String?,
    note: json["note"] as String?,
    expiresAt: json["expires_at"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (status != null) "status": status!,
    if (value != null) "value": value!,
    if (customerId != null) "customer_id": customerId!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (note != null) "note": note!,
    if (expiresAt != null) "expires_at": expiresAt!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in the inventory item.
class AdminUpdateInventoryItem {
  AdminUpdateInventoryItem({
    this.sku,
    this.hsCode,
    this.weight,
    this.length,
    this.height,
    this.width,
    this.originCountry,
    this.midCode,
    this.material,
    this.title,
    this.description,
    this.requiresShipping,
    this.thumbnail,
    this.metadata,
  });

  /// The inventory item's SKU.
  final String? sku;
  /// The inventory item's HS code.
  final String? hsCode;
  /// The inventory item's weight.
  final num? weight;
  /// The inventory item's length.
  final num? length;
  /// The inventory item's height.
  final num? height;
  /// The inventory item's width.
  final num? width;
  /// The inventory item's origin country.
  final String? originCountry;
  /// The inventory item's MID code.
  final String? midCode;
  /// The inventory item's material.
  final String? material;
  /// The inventory item's title.
  final String? title;
  /// The inventory item's description.
  final String? description;
  /// Whether the inventory item requires shipping.
  final bool? requiresShipping;
  /// The URL of an image to be used as the inventory item's thumbnail. You can use the Upload API routes to upload an image and get its URL.
  final String? thumbnail;
  /// The inventory item's metadata. Can be custom data in key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateInventoryItem.fromJson(Map<String, dynamic> json) => AdminUpdateInventoryItem(
    sku: json["sku"] as String?,
    hsCode: json["hs_code"] as String?,
    weight: json["weight"] as num?,
    length: json["length"] as num?,
    height: json["height"] as num?,
    width: json["width"] as num?,
    originCountry: json["origin_country"] as String?,
    midCode: json["mid_code"] as String?,
    material: json["material"] as String?,
    title: json["title"] as String?,
    description: json["description"] as String?,
    requiresShipping: json["requires_shipping"] as bool?,
    thumbnail: json["thumbnail"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (sku != null) "sku": sku!,
    if (hsCode != null) "hs_code": hsCode!,
    if (weight != null) "weight": weight!,
    if (length != null) "length": length!,
    if (height != null) "height": height!,
    if (width != null) "width": width!,
    if (originCountry != null) "origin_country": originCountry!,
    if (midCode != null) "mid_code": midCode!,
    if (material != null) "material": material!,
    if (title != null) "title": title!,
    if (description != null) "description": description!,
    if (requiresShipping != null) "requires_shipping": requiresShipping!,
    if (thumbnail != null) "thumbnail": thumbnail!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in the inventory level.
class AdminUpdateInventoryLevel {
  AdminUpdateInventoryLevel({
    this.stockedQuantity,
    this.incomingQuantity,
  });

  /// The inventory level's stocked quantity.
  final num? stockedQuantity;
  /// The inventory level's incoming quantity.
  final num? incomingQuantity;

  factory AdminUpdateInventoryLevel.fromJson(Map<String, dynamic> json) => AdminUpdateInventoryLevel(
    stockedQuantity: json["stocked_quantity"] as num?,
    incomingQuantity: json["incoming_quantity"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (stockedQuantity != null) "stocked_quantity": stockedQuantity!,
    if (incomingQuantity != null) "incoming_quantity": incomingQuantity!,
  };
}

/// The details to update in the order.
class AdminUpdateOrder {
  AdminUpdateOrder({
    this.email,
    this.shippingAddress,
    this.billingAddress,
    this.metadata,
    this.locale,
  });

  /// The order's email.
  final String? email;
  final OrderAddress? shippingAddress;
  final OrderAddress? billingAddress;
  /// The order's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The order's locale in [BCP 47](https://gist.github.com/typpo/b2b828a35e683b9bf8db91b5404f1bd1) format.
  final String? locale;

  factory AdminUpdateOrder.fromJson(Map<String, dynamic> json) => AdminUpdateOrder(
    email: json["email"] as String?,
    shippingAddress: json["shipping_address"] == null ? null : OrderAddress.fromJson(json["shipping_address"] as Map<String, dynamic>),
    billingAddress: json["billing_address"] == null ? null : OrderAddress.fromJson(json["billing_address"] as Map<String, dynamic>),
    metadata: json["metadata"] as Map<String, dynamic>?,
    locale: json["locale"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (email != null) "email": email!,
    if (shippingAddress != null) "shipping_address": shippingAddress!.toJson(),
    if (billingAddress != null) "billing_address": billingAddress!.toJson(),
    if (metadata != null) "metadata": metadata!,
    if (locale != null) "locale": locale!,
  };
}

/// The data to update in the order change.
class AdminUpdateOrderChange {
  AdminUpdateOrderChange({
    this.carryOverPromotions,
    this.internalNote,
  });

  /// Whether promotions from the original order should be carried over to the order change (specifically, exchanges).
  final bool? carryOverPromotions;
  /// The order change's internal note.
  final String? internalNote;

  factory AdminUpdateOrderChange.fromJson(Map<String, dynamic> json) => AdminUpdateOrderChange(
    carryOverPromotions: json["carry_over_promotions"] as bool?,
    internalNote: json["internal_note"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (carryOverPromotions != null) "carry_over_promotions": carryOverPromotions!,
    if (internalNote != null) "internal_note": internalNote!,
  };
}

/// the details to update in a price list.
class AdminUpdatePriceList {
  AdminUpdatePriceList({
    this.title,
    this.description,
    this.startsAt,
    this.endsAt,
    this.status,
    this.type,
    this.rules,
    this.metadata,
  });

  /// The price list's title.
  final String? title;
  /// The price list's description.
  final String? description;
  /// The date the price list starts.
  final String? startsAt;
  /// The date the price list ends.
  final String? endsAt;
  /// The price list's status.
  final String? status;
  /// The price list's type.
  final String? type;
  /// The price list's rules.
  final Map<String, dynamic>? rules;
  /// Key-value pairs of custom data.
  final Map<String, dynamic>? metadata;

  factory AdminUpdatePriceList.fromJson(Map<String, dynamic> json) => AdminUpdatePriceList(
    title: json["title"] as String?,
    description: json["description"] as String?,
    startsAt: json["starts_at"] as String?,
    endsAt: json["ends_at"] as String?,
    status: json["status"] as String?,
    type: json["type"] as String?,
    rules: json["rules"] as Map<String, dynamic>?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (description != null) "description": description!,
    if (startsAt != null) "starts_at": startsAt!,
    if (endsAt != null) "ends_at": endsAt!,
    if (status != null) "status": status!,
    if (type != null) "type": type!,
    if (rules != null) "rules": rules!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details to update in the price preference.
class AdminUpdatePricePreference {
  AdminUpdatePricePreference({
    this.attribute,
    this.value,
    this.isTaxInclusive,
  });

  /// The price preference's attribute.
  final String? attribute;
  /// The price preference's value.
  final String? value;
  /// Whether prices are tax inclusive for this price preference.
  final bool? isTaxInclusive;

  factory AdminUpdatePricePreference.fromJson(Map<String, dynamic> json) => AdminUpdatePricePreference(
    attribute: json["attribute"] as String?,
    value: json["value"] as String?,
    isTaxInclusive: json["is_tax_inclusive"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (attribute != null) "attribute": attribute!,
    if (value != null) "value": value!,
    if (isTaxInclusive != null) "is_tax_inclusive": isTaxInclusive!,
  };
}

/// The product's details.
class AdminUpdateProduct {
  AdminUpdateProduct({
    this.title,
    this.subtitle,
    this.description,
    this.isGiftcard,
    this.discountable,
    this.images,
    this.thumbnail,
    this.handle,
    this.status,
    this.typeId,
    this.collectionId,
    this.categories,
    this.tags,
    this.options,
    this.variants,
    this.salesChannels,
    this.weight,
    this.length,
    this.height,
    this.width,
    this.hsCode,
    this.midCode,
    this.originCountry,
    this.material,
    this.metadata,
    this.externalId,
  });

  /// The product's title.
  final String? title;
  /// The product's subtitle.
  final String? subtitle;
  /// The product's description.
  final String? description;
  /// Whether the product is a gift card.
  final bool? isGiftcard;
  /// Whether discounts can be applied on the product.
  final bool? discountable;
  /// The product's images.
  final List<Map<String, dynamic>>? images;
  /// The product's thumbnail URL.
  final String? thumbnail;
  /// The product's unique handle.
  final String? handle;
  /// The product's status.
  final String? status;
  /// The ID of the product's type.
  final String? typeId;
  /// The ID of the product's collection.
  final String? collectionId;
  /// The product's categories.
  final List<Map<String, dynamic>>? categories;
  /// The product's tags.
  final List<Map<String, dynamic>>? tags;
  /// The product's options.
  final List<AdminUpdateProductOption>? options;
  /// The product's variants. You can add new variants or update existing ones, passing their IDs in the object.
  final List<dynamic>? variants;
  /// The sales channels that the product is available in.
  final List<Map<String, dynamic>>? salesChannels;
  /// The product's weight.
  final num? weight;
  /// The product's length.
  final num? length;
  /// The product's height.
  final num? height;
  /// The product's width.
  final num? width;
  /// The product's HS code.
  final String? hsCode;
  /// The product's MID code.
  final String? midCode;
  /// The product's origin country.
  final String? originCountry;
  /// The product's material.
  final String? material;
  /// The product's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the product in an external or third-party system.
  final String? externalId;

  factory AdminUpdateProduct.fromJson(Map<String, dynamic> json) => AdminUpdateProduct(
    title: json["title"] as String?,
    subtitle: json["subtitle"] as String?,
    description: json["description"] as String?,
    isGiftcard: json["is_giftcard"] as bool?,
    discountable: json["discountable"] as bool?,
    images: (json["images"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    thumbnail: json["thumbnail"] as String?,
    handle: json["handle"] as String?,
    status: json["status"] as String?,
    typeId: json["type_id"] as String?,
    collectionId: json["collection_id"] as String?,
    categories: (json["categories"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    tags: (json["tags"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    options: (json["options"] as List?)?.map((e) => e == null ? null : AdminUpdateProductOption.fromJson(e as Map<String, dynamic>)).toList().cast<AdminUpdateProductOption>(),
    variants: (json["variants"] as List?)?.map((e) => e).toList().cast<dynamic>(),
    salesChannels: (json["sales_channels"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
    weight: json["weight"] as num?,
    length: json["length"] as num?,
    height: json["height"] as num?,
    width: json["width"] as num?,
    hsCode: json["hs_code"] as String?,
    midCode: json["mid_code"] as String?,
    originCountry: json["origin_country"] as String?,
    material: json["material"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (subtitle != null) "subtitle": subtitle!,
    if (description != null) "description": description!,
    if (isGiftcard != null) "is_giftcard": isGiftcard!,
    if (discountable != null) "discountable": discountable!,
    if (images != null) "images": images!.map((e) => e).toList(),
    if (thumbnail != null) "thumbnail": thumbnail!,
    if (handle != null) "handle": handle!,
    if (status != null) "status": status!,
    if (typeId != null) "type_id": typeId!,
    if (collectionId != null) "collection_id": collectionId!,
    if (categories != null) "categories": categories!.map((e) => e).toList(),
    if (tags != null) "tags": tags!.map((e) => e).toList(),
    if (options != null) "options": options!.map((e) => e.toJson()).toList(),
    if (variants != null) "variants": variants!.map((e) => e).toList(),
    if (salesChannels != null) "sales_channels": salesChannels!.map((e) => e).toList(),
    if (weight != null) "weight": weight!,
    if (length != null) "length": length!,
    if (height != null) "height": height!,
    if (width != null) "width": width!,
    if (hsCode != null) "hs_code": hsCode!,
    if (midCode != null) "mid_code": midCode!,
    if (originCountry != null) "origin_country": originCountry!,
    if (material != null) "material": material!,
    if (metadata != null) "metadata": metadata!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The properties to update in the product category.
class AdminUpdateProductCategory {
  AdminUpdateProductCategory({
    this.name,
    this.description,
    this.handle,
    this.isInternal,
    this.isActive,
    this.parentCategoryId,
    this.metadata,
    this.rank,
    this.externalId,
  });

  /// The product category's name.
  final String? name;
  /// The product category's description.
  final String? description;
  /// The product category's handle. Must be a unique value.
  final String? handle;
  /// Whether the product category is only used for internal purposes and shouldn't be shown the customer.
  final bool? isInternal;
  /// Whether the product category is active.
  final bool? isActive;
  /// The ID of a parent category.
  final String? parentCategoryId;
  /// The product category's metadata. Can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The product category's rank among other categories.
  final num? rank;
  /// The product category's external ID used to link it with external systems.
  final String? externalId;

  factory AdminUpdateProductCategory.fromJson(Map<String, dynamic> json) => AdminUpdateProductCategory(
    name: json["name"] as String?,
    description: json["description"] as String?,
    handle: json["handle"] as String?,
    isInternal: json["is_internal"] as bool?,
    isActive: json["is_active"] as bool?,
    parentCategoryId: json["parent_category_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    rank: json["rank"] as num?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (description != null) "description": description!,
    if (handle != null) "handle": handle!,
    if (isInternal != null) "is_internal": isInternal!,
    if (isActive != null) "is_active": isActive!,
    if (parentCategoryId != null) "parent_category_id": parentCategoryId!,
    if (metadata != null) "metadata": metadata!,
    if (rank != null) "rank": rank!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The details to update in a product option.
class AdminUpdateProductOption {
  AdminUpdateProductOption({
    this.title,
    this.values,
    this.id,
    this.ranks,
    this.isExclusive,
    this.metadata,
  });

  /// The option's title.
  final String? title;
  /// The option's values.
  final List<String>? values;
  /// The option's ID.
  final String? id;
  /// The product option's ranks.
  final Map<String, dynamic>? ranks;
  /// Whether the product option is exclusive to the product. If disabled, the product option can be used by other products.
  final bool? isExclusive;
  /// Key-value pairs that hold additional information about the product option.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateProductOption.fromJson(Map<String, dynamic> json) => AdminUpdateProductOption(
    title: json["title"] as String?,
    values: (json["values"] as List?)?.map((e) => e as String?).toList().cast<String>(),
    id: json["id"] as String?,
    ranks: json["ranks"] as Map<String, dynamic>?,
    isExclusive: json["is_exclusive"] as bool?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (values != null) "values": values!.map((e) => e).toList(),
    if (id != null) "id": id!,
    if (ranks != null) "ranks": ranks!,
    if (isExclusive != null) "is_exclusive": isExclusive!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details of updating a product option value.
class AdminUpdateProductOptionValue {
  AdminUpdateProductOptionValue({
    this.value,
    this.metadata,
  });

  /// The product option's value.
  final String? value;
  /// Key-value pairs that hold additional information about the product option value.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateProductOptionValue.fromJson(Map<String, dynamic> json) => AdminUpdateProductOptionValue(
    value: json["value"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (value != null) "value": value!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details to update a product option's values.
class AdminUpdateProductOptionValues {
  AdminUpdateProductOptionValues({
    this.productOptionId,
    this.add,
    this.remove,
  });

  /// The ID of the product option to update.
  final String? productOptionId;
  /// The values to add to the product option.
  final List<dynamic>? add;
  /// The values to remove from the product option.
  final List<String>? remove;

  factory AdminUpdateProductOptionValues.fromJson(Map<String, dynamic> json) => AdminUpdateProductOptionValues(
    productOptionId: json["product_option_id"] as String?,
    add: (json["add"] as List?)?.map((e) => e).toList().cast<dynamic>(),
    remove: (json["remove"] as List?)?.map((e) => e as String?).toList().cast<String>(),
  );

  Map<String, dynamic> toJson() => {
    if (productOptionId != null) "product_option_id": productOptionId!,
    if (add != null) "add": add!.map((e) => e).toList(),
    if (remove != null) "remove": remove!.map((e) => e).toList(),
  };
}

/// The properties to update in the product tag.
class AdminUpdateProductTag {
  AdminUpdateProductTag({
    this.value,
    this.metadata,
    this.externalId,
  });

  /// The product tag's value.
  final String? value;
  /// The product tag's metadata. Can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The product tag's external ID used to link it with external systems.
  final String? externalId;

  factory AdminUpdateProductTag.fromJson(Map<String, dynamic> json) => AdminUpdateProductTag(
    value: json["value"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (value != null) "value": value!,
    if (metadata != null) "metadata": metadata!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The properties to update in the product type.
class AdminUpdateProductType {
  AdminUpdateProductType({
    this.value,
    this.metadata,
    this.externalId,
  });

  /// The product type's value.
  final String? value;
  /// The product type's metadata. Can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The product type's external ID used to link it with external systems.
  final String? externalId;

  factory AdminUpdateProductType.fromJson(Map<String, dynamic> json) => AdminUpdateProductType(
    value: json["value"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (value != null) "value": value!,
    if (metadata != null) "metadata": metadata!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The properties to update of a product variant.
class AdminUpdateProductVariant {
  AdminUpdateProductVariant({
    this.title,
    this.sku,
    this.ean,
    this.upc,
    this.barcode,
    this.hsCode,
    this.midCode,
    this.allowBackorder,
    this.manageInventory,
    this.variantRank,
    this.weight,
    this.length,
    this.height,
    this.width,
    this.originCountry,
    this.material,
    this.metadata,
    this.prices,
    this.options,
  });

  /// The product variant's title.
  final String? title;
  /// The product variant's SKU.
  final String? sku;
  /// The product variant's EAN.
  final String? ean;
  /// The product variant's UPC.
  final String? upc;
  /// The product variant's barcode.
  final String? barcode;
  /// The product variant's HS code.
  final String? hsCode;
  /// The product variant's MID code.
  final String? midCode;
  /// Whether customers can order the variant even if it's not in stock.
  final bool? allowBackorder;
  /// Whether the Medusa application manages the variant's inventory. If disabled, the product variant is always considered in stock.
  final bool? manageInventory;
  /// The product variant's rank among its siblings.
  final num? variantRank;
  /// The product variant's weight.
  final num? weight;
  /// The product variant's length.
  final num? length;
  /// The product variant's height.
  final num? height;
  /// The product variant's width.
  final num? width;
  /// The product variant's origin country.
  final String? originCountry;
  /// The product variant's material.
  final String? material;
  /// The product variant's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The product variant's prices.
  final List<AdminCreateProductVariantPrice>? prices;
  /// The product variant's options.
  final Map<String, dynamic>? options;

  factory AdminUpdateProductVariant.fromJson(Map<String, dynamic> json) => AdminUpdateProductVariant(
    title: json["title"] as String?,
    sku: json["sku"] as String?,
    ean: json["ean"] as String?,
    upc: json["upc"] as String?,
    barcode: json["barcode"] as String?,
    hsCode: json["hs_code"] as String?,
    midCode: json["mid_code"] as String?,
    allowBackorder: json["allow_backorder"] as bool?,
    manageInventory: json["manage_inventory"] as bool?,
    variantRank: json["variant_rank"] as num?,
    weight: json["weight"] as num?,
    length: json["length"] as num?,
    height: json["height"] as num?,
    width: json["width"] as num?,
    originCountry: json["origin_country"] as String?,
    material: json["material"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    prices: (json["prices"] as List?)?.map((e) => e == null ? null : AdminCreateProductVariantPrice.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateProductVariantPrice>(),
    options: json["options"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (title != null) "title": title!,
    if (sku != null) "sku": sku!,
    if (ean != null) "ean": ean!,
    if (upc != null) "upc": upc!,
    if (barcode != null) "barcode": barcode!,
    if (hsCode != null) "hs_code": hsCode!,
    if (midCode != null) "mid_code": midCode!,
    if (allowBackorder != null) "allow_backorder": allowBackorder!,
    if (manageInventory != null) "manage_inventory": manageInventory!,
    if (variantRank != null) "variant_rank": variantRank!,
    if (weight != null) "weight": weight!,
    if (length != null) "length": length!,
    if (height != null) "height": height!,
    if (width != null) "width": width!,
    if (originCountry != null) "origin_country": originCountry!,
    if (material != null) "material": material!,
    if (metadata != null) "metadata": metadata!,
    if (prices != null) "prices": prices!.map((e) => e.toJson()).toList(),
    if (options != null) "options": options!,
  };
}

/// The details of a variant's price.
class AdminUpdateProductVariantPrice {
  AdminUpdateProductVariantPrice({
    this.currencyCode,
    this.amount,
    this.minQuantity,
    this.maxQuantity,
    this.rules,
    this.id,
  });

  /// The price's currency code.
  final String? currencyCode;
  /// The price's amount.
  final num? amount;
  /// The minimum quantity that must be available in the cart for this price to apply.
  final num? minQuantity;
  /// The maximum quantity that must not be surpassed in the cart for this price to apply.
  final num? maxQuantity;
  /// The price's rules.
  final Map<String, dynamic>? rules;
  /// The price's ID.
  final String? id;

  factory AdminUpdateProductVariantPrice.fromJson(Map<String, dynamic> json) => AdminUpdateProductVariantPrice(
    currencyCode: json["currency_code"] as String?,
    amount: json["amount"] as num?,
    minQuantity: json["min_quantity"] as num?,
    maxQuantity: json["max_quantity"] as num?,
    rules: json["rules"] as Map<String, dynamic>?,
    id: json["id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (currencyCode != null) "currency_code": currencyCode!,
    if (amount != null) "amount": amount!,
    if (minQuantity != null) "min_quantity": minQuantity!,
    if (maxQuantity != null) "max_quantity": maxQuantity!,
    if (rules != null) "rules": rules!,
    if (id != null) "id": id!,
  };
}

/// The properties to update in a buy rule.
class AdminUpdatePromotionRule {
  AdminUpdatePromotionRule({
    this.id,
    this.operator,
    this.description,
    this.attribute,
    this.values,
  });

  /// The buy rule's ID.
  final String? id;
  /// The operator used to check whether the buy rule applies on a cart. For example, `eq` means that the cart's value for the specified attribute must match the spec
  final String? operator;
  /// The buy rule's description.
  final String? description;
  /// The attribute to compare against when checking whether a promotion can be applied on a cart.
  final String? attribute;
  final dynamic values;

  factory AdminUpdatePromotionRule.fromJson(Map<String, dynamic> json) => AdminUpdatePromotionRule(
    id: json["id"] as String?,
    operator: json["operator"] as String?,
    description: json["description"] as String?,
    attribute: json["attribute"] as String?,
    values: json["values"],
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (operator != null) "operator": operator!,
    if (description != null) "description": description!,
    if (attribute != null) "attribute": attribute!,
    if (values != null) "values": values!,
  };
}

/// The details to update in a property label.
class AdminUpdatePropertyLabel {
  AdminUpdatePropertyLabel({
    this.label,
    this.description,
  });

  /// The label of the property.
  final String? label;
  /// The property label's description.
  final String? description;

  factory AdminUpdatePropertyLabel.fromJson(Map<String, dynamic> json) => AdminUpdatePropertyLabel(
    label: json["label"] as String?,
    description: json["description"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (label != null) "label": label!,
    if (description != null) "description": description!,
  };
}

/// The properties to update in the refund reason.
class AdminUpdateRefundReason {
  AdminUpdateRefundReason({
    this.label,
    this.description,
    this.code,
  });

  /// The refund reason's label.
  final String? label;
  /// The refund reason's description.
  final String? description;
  /// The refund reason's code.
  final String? code;

  factory AdminUpdateRefundReason.fromJson(Map<String, dynamic> json) => AdminUpdateRefundReason(
    label: json["label"] as String?,
    description: json["description"] as String?,
    code: json["code"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (label != null) "label": label!,
    if (description != null) "description": description!,
    if (code != null) "code": code!,
  };
}

/// The propeties to update in the region.
class AdminUpdateRegion {
  AdminUpdateRegion({
    this.name,
    this.currencyCode,
    this.countries,
    this.automaticTaxes,
    this.paymentProviders,
    this.metadata,
    this.isTaxInclusive,
  });

  /// The region's name.
  final String? name;
  /// The region's currency code.
  final String? currencyCode;
  /// The region's countries.
  final List<String>? countries;
  /// Whether taxes are calculated automatically for carts in the region.
  final bool? automaticTaxes;
  /// The payment providers enabled in the region.
  final List<String>? paymentProviders;
  /// The region's metadata. Can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// Whether the prices in the region are tax inclusive.
  final bool? isTaxInclusive;

  factory AdminUpdateRegion.fromJson(Map<String, dynamic> json) => AdminUpdateRegion(
    name: json["name"] as String?,
    currencyCode: json["currency_code"] as String?,
    countries: (json["countries"] as List?)?.map((e) => e as String?).toList().cast<String>(),
    automaticTaxes: json["automatic_taxes"] as bool?,
    paymentProviders: (json["payment_providers"] as List?)?.map((e) => e as String?).toList().cast<String>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
    isTaxInclusive: json["is_tax_inclusive"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (countries != null) "countries": countries!.map((e) => e).toList(),
    if (automaticTaxes != null) "automatic_taxes": automaticTaxes!,
    if (paymentProviders != null) "payment_providers": paymentProviders!.map((e) => e).toList(),
    if (metadata != null) "metadata": metadata!,
    if (isTaxInclusive != null) "is_tax_inclusive": isTaxInclusive!,
  };
}

/// The properties to update in the reservation.
class AdminUpdateReservation {
  AdminUpdateReservation({
    this.locationId,
    this.quantity,
    this.description,
    this.metadata,
  });

  /// The ID of the associated location.
  final String? locationId;
  /// The reserved quantity.
  final num? quantity;
  /// The reservation's description.
  final String? description;
  /// The reservation's metadata. Can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateReservation.fromJson(Map<String, dynamic> json) => AdminUpdateReservation(
    locationId: json["location_id"] as String?,
    quantity: json["quantity"] as num?,
    description: json["description"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (locationId != null) "location_id": locationId!,
    if (quantity != null) "quantity": quantity!,
    if (description != null) "description": description!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details to update in the item.
class AdminUpdateReturnItems {
  AdminUpdateReturnItems({
    this.quantity,
    this.internalNote,
    this.reasonId,
    this.metadata,
  });

  /// The item's quantity.
  final num? quantity;
  /// A note viewed only by admin users.
  final String? internalNote;
  /// The ID of the associated return reason.
  final String? reasonId;
  /// The claim's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateReturnItems.fromJson(Map<String, dynamic> json) => AdminUpdateReturnItems(
    quantity: json["quantity"] as num?,
    internalNote: json["internal_note"] as String?,
    reasonId: json["reason_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (quantity != null) "quantity": quantity!,
    if (internalNote != null) "internal_note": internalNote!,
    if (reasonId != null) "reason_id": reasonId!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details to update in a return reason.
class AdminUpdateReturnReason {
  AdminUpdateReturnReason({
    this.label,
    this.value,
    this.description,
    this.metadata,
  });

  /// The return reason's label.
  final String? label;
  /// The return reason's value.
  final String? value;
  /// The return reason's description.
  final String? description;
  /// The return reason's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateReturnReason.fromJson(Map<String, dynamic> json) => AdminUpdateReturnReason(
    label: json["label"] as String?,
    value: json["value"] as String?,
    description: json["description"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (label != null) "label": label!,
    if (value != null) "value": value!,
    if (description != null) "description": description!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The return's details.
class AdminUpdateReturnRequest {
  AdminUpdateReturnRequest({
    this.locationId,
    this.noNotification,
    this.metadata,
  });

  /// The ID of the location to return items to.
  final String? locationId;
  /// Whether the customer should receive notifications about updates to the return.
  final bool? noNotification;
  /// The return's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateReturnRequest.fromJson(Map<String, dynamic> json) => AdminUpdateReturnRequest(
    locationId: json["location_id"] as String?,
    noNotification: json["no_notification"] as bool?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (locationId != null) "location_id": locationId!,
    if (noNotification != null) "no_notification": noNotification!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The shipping method's details.
class AdminUpdateReturnShipping {
  AdminUpdateReturnShipping({
    this.customAmount,
    this.internalNote,
    this.metadata,
  });

  /// Set a custom price for the shipping method.
  final num? customAmount;
  /// A note viewed only by admin users.
  final String? internalNote;
  /// The return's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateReturnShipping.fromJson(Map<String, dynamic> json) => AdminUpdateReturnShipping(
    customAmount: json["custom_amount"] as num?,
    internalNote: json["internal_note"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (customAmount != null) "custom_amount": customAmount!,
    if (internalNote != null) "internal_note": internalNote!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in the sales channel.
class AdminUpdateSalesChannel {
  AdminUpdateSalesChannel({
    this.name,
    this.description,
    this.isDisabled,
    this.metadata,
  });

  /// The sales channel's name.
  final String? name;
  /// The sales channel's description.
  final String? description;
  /// Whether the sales channel is disabled.
  final bool? isDisabled;
  /// The sales channel's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateSalesChannel.fromJson(Map<String, dynamic> json) => AdminUpdateSalesChannel(
    name: json["name"] as String?,
    description: json["description"] as String?,
    isDisabled: json["is_disabled"] as bool?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (description != null) "description": description!,
    if (isDisabled != null) "is_disabled": isDisabled!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in the shipping option type.
class AdminUpdateShippingOption {
  AdminUpdateShippingOption({
    this.name,
    this.data,
    this.priceType,
    this.providerId,
    this.shippingProfileId,
    this.type,
    this.typeId,
    this.prices,
    this.rules,
    this.metadata,
  });

  /// The shipping option's name.
  final String? name;
  /// The shipping option's data.
  final Map<String, dynamic>? data;
  /// The shipping option's price type.
  final String? priceType;
  /// The shipping option's provider id.
  final String? providerId;
  /// The shipping option's shipping profile id.
  final String? shippingProfileId;
  final AdminCreateShippingOptionType? type;
  /// The shipping option's type id.
  final String? typeId;
  /// The shipping option's prices. This array replaces the shipping option's existing prices - a price with a matching `id` is updated, a price without an `id` is cr
  final List<dynamic>? prices;
  /// The shipping option's rules.
  final List<dynamic>? rules;
  /// The shipping option's metadata.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateShippingOption.fromJson(Map<String, dynamic> json) => AdminUpdateShippingOption(
    name: json["name"] as String?,
    data: json["data"] as Map<String, dynamic>?,
    priceType: json["price_type"] as String?,
    providerId: json["provider_id"] as String?,
    shippingProfileId: json["shipping_profile_id"] as String?,
    type: json["type"] == null ? null : AdminCreateShippingOptionType.fromJson(json["type"] as Map<String, dynamic>),
    typeId: json["type_id"] as String?,
    prices: (json["prices"] as List?)?.map((e) => e).toList().cast<dynamic>(),
    rules: (json["rules"] as List?)?.map((e) => e).toList().cast<dynamic>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (data != null) "data": data!,
    if (priceType != null) "price_type": priceType!,
    if (providerId != null) "provider_id": providerId!,
    if (shippingProfileId != null) "shipping_profile_id": shippingProfileId!,
    if (type != null) "type": type!.toJson(),
    if (typeId != null) "type_id": typeId!,
    if (prices != null) "prices": prices!.map((e) => e).toList(),
    if (rules != null) "rules": rules!.map((e) => e).toList(),
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in a shipping option price with a currency.
class AdminUpdateShippingOptionPriceWithCurrency {
  AdminUpdateShippingOptionPriceWithCurrency({
    this.id,
    this.currencyCode,
    this.amount,
    this.rules,
  });

  /// The price's ID. If not provided, a new price is created; existing prices whose ID isn't included in the request are deleted.
  final String? id;
  /// The price's currency code.
  final String? currencyCode;
  /// The price's amount.
  final num? amount;
  /// The price's rules. These rules replace the price's existing rules, so omit a rule to remove it.
  final List<PriceRule>? rules;

  factory AdminUpdateShippingOptionPriceWithCurrency.fromJson(Map<String, dynamic> json) => AdminUpdateShippingOptionPriceWithCurrency(
    id: json["id"] as String?,
    currencyCode: json["currency_code"] as String?,
    amount: json["amount"] as num?,
    rules: (json["rules"] as List?)?.map((e) => e == null ? null : PriceRule.fromJson(e as Map<String, dynamic>)).toList().cast<PriceRule>(),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (amount != null) "amount": amount!,
    if (rules != null) "rules": rules!.map((e) => e.toJson()).toList(),
  };
}

/// The properties to update in a shipping option price with a region.
class AdminUpdateShippingOptionPriceWithRegion {
  AdminUpdateShippingOptionPriceWithRegion({
    this.id,
    this.regionId,
    this.amount,
    this.rules,
  });

  /// The price's ID. If not provided, a new price is created; existing prices whose ID isn't included in the request are deleted.
  final String? id;
  /// The ID of the region the price is associated with.
  final String? regionId;
  /// The price's amount.
  final num? amount;
  /// The price's rules. These rules replace the price's existing rules, so omit a rule to remove it.
  final List<PriceRule>? rules;

  factory AdminUpdateShippingOptionPriceWithRegion.fromJson(Map<String, dynamic> json) => AdminUpdateShippingOptionPriceWithRegion(
    id: json["id"] as String?,
    regionId: json["region_id"] as String?,
    amount: json["amount"] as num?,
    rules: (json["rules"] as List?)?.map((e) => e == null ? null : PriceRule.fromJson(e as Map<String, dynamic>)).toList().cast<PriceRule>(),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (regionId != null) "region_id": regionId!,
    if (amount != null) "amount": amount!,
    if (rules != null) "rules": rules!.map((e) => e.toJson()).toList(),
  };
}

/// The properties to update in the shipping option rule.
class AdminUpdateShippingOptionRule {
  AdminUpdateShippingOptionRule({
    this.id,
    this.operator,
    this.attribute,
    this.value,
  });

  /// The rule's ID.
  final String? id;
  /// The operator used to check whether a rule applies.
  final String? operator;
  /// The name of a property or table that the rule applies to.
  final String? attribute;
  final dynamic value;

  factory AdminUpdateShippingOptionRule.fromJson(Map<String, dynamic> json) => AdminUpdateShippingOptionRule(
    id: json["id"] as String?,
    operator: json["operator"] as String?,
    attribute: json["attribute"] as String?,
    value: json["value"],
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (operator != null) "operator": operator!,
    if (attribute != null) "attribute": attribute!,
    if (value != null) "value": value!,
  };
}

/// The properties to update in the shipping option type.
class AdminUpdateShippingOptionType {
  AdminUpdateShippingOptionType({
    this.code,
    this.description,
    this.label,
  });

  /// The shipping option type's code.
  final String? code;
  /// The shipping option type's description.
  final String? description;
  /// The shipping option type's label.
  final String? label;

  factory AdminUpdateShippingOptionType.fromJson(Map<String, dynamic> json) => AdminUpdateShippingOptionType(
    code: json["code"] as String?,
    description: json["description"] as String?,
    label: json["label"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (code != null) "code": code!,
    if (description != null) "description": description!,
    if (label != null) "label": label!,
  };
}

/// The properties to update in the shipping profile.
class AdminUpdateShippingProfile {
  AdminUpdateShippingProfile({
    this.name,
    this.type,
    this.metadata,
  });

  /// The shipping profile's name.
  final String? name;
  /// The shipping profile's type.
  final String? type;
  /// The shipping profile's metadata.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateShippingProfile.fromJson(Map<String, dynamic> json) => AdminUpdateShippingProfile(
    name: json["name"] as String?,
    type: json["type"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (type != null) "type": type!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in a stock location.
class AdminUpdateStockLocation {
  AdminUpdateStockLocation({
    this.name,
    this.address,
    this.addressId,
    this.metadata,
  });

  /// The stock location's name.
  final String? name;
  final AdminUpsertStockLocationAddress? address;
  /// The ID of an existing stock location address to associate the stock location with.
  final String? addressId;
  /// The stock location's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateStockLocation.fromJson(Map<String, dynamic> json) => AdminUpdateStockLocation(
    name: json["name"] as String?,
    address: json["address"] == null ? null : AdminUpsertStockLocationAddress.fromJson(json["address"] as Map<String, dynamic>),
    addressId: json["address_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (address != null) "address": address!.toJson(),
    if (addressId != null) "address_id": addressId!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in a store.
class AdminUpdateStore {
  AdminUpdateStore({
    this.name,
    this.supportedCurrencies,
    this.defaultSalesChannelId,
    this.defaultRegionId,
    this.defaultLocationId,
    this.metadata,
    this.supportedLocales,
  });

  /// The store's name.
  final String? name;
  /// The store's supported currencies.
  final List<AdminUpdateStoreSupportedCurrency>? supportedCurrencies;
  /// The ID of the default sales channel in the store.
  final String? defaultSalesChannelId;
  /// The ID of the default region in the store.
  final String? defaultRegionId;
  /// The ID of the default stock location in the store.
  final String? defaultLocationId;
  /// The store's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The store's supported locales.
  final List<AdminUpdateStoreSupportedLocale>? supportedLocales;

  factory AdminUpdateStore.fromJson(Map<String, dynamic> json) => AdminUpdateStore(
    name: json["name"] as String?,
    supportedCurrencies: (json["supported_currencies"] as List?)?.map((e) => e == null ? null : AdminUpdateStoreSupportedCurrency.fromJson(e as Map<String, dynamic>)).toList().cast<AdminUpdateStoreSupportedCurrency>(),
    defaultSalesChannelId: json["default_sales_channel_id"] as String?,
    defaultRegionId: json["default_region_id"] as String?,
    defaultLocationId: json["default_location_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    supportedLocales: (json["supported_locales"] as List?)?.map((e) => e == null ? null : AdminUpdateStoreSupportedLocale.fromJson(e as Map<String, dynamic>)).toList().cast<AdminUpdateStoreSupportedLocale>(),
  );

  Map<String, dynamic> toJson() => {
    if (name != null) "name": name!,
    if (supportedCurrencies != null) "supported_currencies": supportedCurrencies!.map((e) => e.toJson()).toList(),
    if (defaultSalesChannelId != null) "default_sales_channel_id": defaultSalesChannelId!,
    if (defaultRegionId != null) "default_region_id": defaultRegionId!,
    if (defaultLocationId != null) "default_location_id": defaultLocationId!,
    if (metadata != null) "metadata": metadata!,
    if (supportedLocales != null) "supported_locales": supportedLocales!.map((e) => e.toJson()).toList(),
  };
}

/// The details to update in a supported currency of the store.
class AdminUpdateStoreSupportedCurrency {
  AdminUpdateStoreSupportedCurrency({
    this.currencyCode,
    this.isDefault,
    this.isTaxInclusive,
  });

  /// The currency's code.
  final String? currencyCode;
  /// Whether the currency is the default in the store.
  final bool? isDefault;
  /// Whether prices using this currency are tax inclusive.
  final bool? isTaxInclusive;

  factory AdminUpdateStoreSupportedCurrency.fromJson(Map<String, dynamic> json) => AdminUpdateStoreSupportedCurrency(
    currencyCode: json["currency_code"] as String?,
    isDefault: json["is_default"] as bool?,
    isTaxInclusive: json["is_tax_inclusive"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (currencyCode != null) "currency_code": currencyCode!,
    if (isDefault != null) "is_default": isDefault!,
    if (isTaxInclusive != null) "is_tax_inclusive": isTaxInclusive!,
  };
}

/// The payload to update a store's supported locale.
class AdminUpdateStoreSupportedLocale {
  AdminUpdateStoreSupportedLocale({
    this.localeCode,
  });

  /// The locale's code in [BCP 47 format](https://gist.github.com/typpo/b2b828a35e683b9bf8db91b5404f1bd1).
  final String? localeCode;

  factory AdminUpdateStoreSupportedLocale.fromJson(Map<String, dynamic> json) => AdminUpdateStoreSupportedLocale(
    localeCode: json["locale_code"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (localeCode != null) "locale_code": localeCode!,
  };
}

/// The properties to update in the tax rate.
class AdminUpdateTaxRate {
  AdminUpdateTaxRate({
    this.rate,
    this.code,
    this.rules,
    this.name,
    this.isDefault,
    this.isCombinable,
    this.metadata,
  });

  /// The rate to charge.
  final num? rate;
  /// The code that the tax rate is identified by.
  final String? code;
  /// The tax rate's rules.
  final List<AdminCreateTaxRateRule>? rules;
  /// The tax rate's name.
  final String? name;
  /// Whether the tax rate is the default in the store.
  final bool? isDefault;
  /// Whether the tax rate should be combined with parent rates.
  final bool? isCombinable;
  /// The tax rate's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateTaxRate.fromJson(Map<String, dynamic> json) => AdminUpdateTaxRate(
    rate: json["rate"] as num?,
    code: json["code"] as String?,
    rules: (json["rules"] as List?)?.map((e) => e == null ? null : AdminCreateTaxRateRule.fromJson(e as Map<String, dynamic>)).toList().cast<AdminCreateTaxRateRule>(),
    name: json["name"] as String?,
    isDefault: json["is_default"] as bool?,
    isCombinable: json["is_combinable"] as bool?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (rate != null) "rate": rate!,
    if (code != null) "code": code!,
    if (rules != null) "rules": rules!.map((e) => e.toJson()).toList(),
    if (name != null) "name": name!,
    if (isDefault != null) "is_default": isDefault!,
    if (isCombinable != null) "is_combinable": isCombinable!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details to update in a tax region.
class AdminUpdateTaxRegion {
  AdminUpdateTaxRegion({
    this.provinceCode,
    this.metadata,
    this.providerId,
  });

  /// The tax region's ISO 3166-2 province code. Must be lower-case.
  final String? provinceCode;
  /// The tax region's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The ID of the tax provider to use when calculating taxes for this tax region.
  final String? providerId;

  factory AdminUpdateTaxRegion.fromJson(Map<String, dynamic> json) => AdminUpdateTaxRegion(
    provinceCode: json["province_code"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    providerId: json["provider_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (provinceCode != null) "province_code": provinceCode!,
    if (metadata != null) "metadata": metadata!,
    if (providerId != null) "provider_id": providerId!,
  };
}

/// The data for updating a translation.
class AdminUpdateTranslation {
  AdminUpdateTranslation({
    this.id,
    this.reference,
    this.referenceId,
    this.localeCode,
    this.translations,
  });

  /// The ID of the translation to update.
  final String? id;
  /// The resource that the translation belongs to.
  final String? reference;
  /// The ID of the resource that the translation belongs to. For example, the ID of a product.
  final String? referenceId;
  /// The translation's locale code in BCP 47 format.
  final String? localeCode;
  /// The translation key-value pairs. Each key is a field in the resource, and the value is the translated text.
  final Map<String, dynamic>? translations;

  factory AdminUpdateTranslation.fromJson(Map<String, dynamic> json) => AdminUpdateTranslation(
    id: json["id"] as String?,
    reference: json["reference"] as String?,
    referenceId: json["reference_id"] as String?,
    localeCode: json["locale_code"] as String?,
    translations: json["translations"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (reference != null) "reference": reference!,
    if (referenceId != null) "reference_id": referenceId!,
    if (localeCode != null) "locale_code": localeCode!,
    if (translations != null) "translations": translations!,
  };
}

/// The translation settings to update.
class AdminUpdateTranslationSettings {
  AdminUpdateTranslationSettings({
    this.id,
    this.entityType,
    this.fields,
    this.isActive,
  });

  /// The ID of the translation settings to update.
  final String? id;
  /// The entity type to update the translation settings for.
  final String? entityType;
  /// The fields to update translations for.
  final List<String>? fields;
  /// Whether translations are active for the given entity type.
  final bool? isActive;

  factory AdminUpdateTranslationSettings.fromJson(Map<String, dynamic> json) => AdminUpdateTranslationSettings(
    id: json["id"] as String?,
    entityType: json["entity_type"] as String?,
    fields: (json["fields"] as List?)?.map((e) => e as String?).toList().cast<String>(),
    isActive: json["is_active"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (entityType != null) "entity_type": entityType!,
    if (fields != null) "fields": fields!.map((e) => e).toList(),
    if (isActive != null) "is_active": isActive!,
  };
}

/// The properties to update in a user.
class AdminUpdateUser {
  AdminUpdateUser({
    this.firstName,
    this.lastName,
    this.avatarUrl,
    this.metadata,
  });

  /// The user's first name.
  final String? firstName;
  /// The user's last name.
  final String? lastName;
  /// The URL of the user's avatar.
  final String? avatarUrl;
  /// The user's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory AdminUpdateUser.fromJson(Map<String, dynamic> json) => AdminUpdateUser(
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    avatarUrl: json["avatar_url"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (avatarUrl != null) "avatar_url": avatarUrl!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update of the variant's inventory item association.
class AdminUpdateVariantInventoryItem {
  AdminUpdateVariantInventoryItem({
    this.requiredQuantity,
  });

  /// The number of units a single quantity is equivalent to. For example, if a customer orders one quantity of the variant, Medusa checks the availability of the qua
  final num? requiredQuantity;

  factory AdminUpdateVariantInventoryItem.fromJson(Map<String, dynamic> json) => AdminUpdateVariantInventoryItem(
    requiredQuantity: json["required_quantity"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (requiredQuantity != null) "required_quantity": requiredQuantity!,
  };
}

/// The details to update in a view configuration.
class AdminUpdateViewConfiguration {
  AdminUpdateViewConfiguration({
    this.setActive,
    this.name,
    this.isSystemDefault,
    this.configuration,
  });

  /// Whether the view is set as active.
  final bool? setActive;
  /// The view's name.
  final String? name;
  /// Whether the view is the system default.
  final bool? isSystemDefault;
  /// The view's configuration.
  final Map<String, dynamic>? configuration;

  factory AdminUpdateViewConfiguration.fromJson(Map<String, dynamic> json) => AdminUpdateViewConfiguration(
    setActive: json["set_active"] as bool?,
    name: json["name"] as String?,
    isSystemDefault: json["is_system_default"] as bool?,
    configuration: json["configuration"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (setActive != null) "set_active": setActive!,
    if (name != null) "name": name!,
    if (isSystemDefault != null) "is_system_default": isSystemDefault!,
    if (configuration != null) "configuration": configuration!,
  };
}

/// The details of the file to upload.
class AdminUploadPreSignedUrl {
  AdminUploadPreSignedUrl({
    this.originalname,
    this.size,
    this.mimeType,
    this.access,
  });

  /// The file's original name.
  final String? originalname;
  /// The file's size in bytes.
  final num? size;
  /// The file's mime type.
  final String? mimeType;
  /// The access level of the file. If `private`, the file will not be publicly accessible. The default value depends on the configured File Module Provider.
  final String? access;

  factory AdminUploadPreSignedUrl.fromJson(Map<String, dynamic> json) => AdminUploadPreSignedUrl(
    originalname: json["originalname"] as String?,
    size: json["size"] as num?,
    mimeType: json["mime_type"] as String?,
    access: json["access"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (originalname != null) "originalname": originalname!,
    if (size != null) "size": size!,
    if (mimeType != null) "mime_type": mimeType!,
    if (access != null) "access": access!,
  };
}

/// The result of the pre-signed URL upload request.
class AdminUploadPreSignedUrlResponse {
  AdminUploadPreSignedUrlResponse({
    this.url,
    this.filename,
    this.originalname,
    this.mimeType,
    this.extension,
    this.size,
  });

  /// The file's pre-signed upload URL.
  final String? url;
  /// The file's filename.
  final String? filename;
  /// The file's orignal name.
  final String? originalname;
  /// The file's mime type.
  final String? mimeType;
  /// The file's extension.
  final String? extension;
  /// The file's size in bytes.
  final num? size;

  factory AdminUploadPreSignedUrlResponse.fromJson(Map<String, dynamic> json) => AdminUploadPreSignedUrlResponse(
    url: json["url"] as String?,
    filename: json["filename"] as String?,
    originalname: json["originalname"] as String?,
    mimeType: json["mime_type"] as String?,
    extension: json["extension"] as String?,
    size: json["size"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (url != null) "url": url!,
    if (filename != null) "filename": filename!,
    if (originalname != null) "originalname": originalname!,
    if (mimeType != null) "mime_type": mimeType!,
    if (extension != null) "extension": extension!,
    if (size != null) "size": size!,
  };
}

/// The details of the stock location address to create.
class AdminUpsertStockLocationAddress {
  AdminUpsertStockLocationAddress({
    this.address1,
    this.address2,
    this.company,
    this.countryCode,
    this.city,
    this.phone,
    this.postalCode,
    this.province,
    this.metadata,
  });

  /// The address's first line.
  final String? address1;
  /// The address's second line.
  final String? address2;
  /// The address's company.
  final String? company;
  /// The address's country code.
  final String? countryCode;
  /// The address's city.
  final String? city;
  /// The address's phone.
  final String? phone;
  /// The address's postal code.
  final String? postalCode;
  /// The address's ISO 3166-2 province code. Must be lower-case.
  final String? province;
  /// The address's metadata.
  final Map<String, dynamic>? metadata;

  factory AdminUpsertStockLocationAddress.fromJson(Map<String, dynamic> json) => AdminUpsertStockLocationAddress(
    address1: json["address_1"] as String?,
    address2: json["address_2"] as String?,
    company: json["company"] as String?,
    countryCode: json["country_code"] as String?,
    city: json["city"] as String?,
    phone: json["phone"] as String?,
    postalCode: json["postal_code"] as String?,
    province: json["province"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (address1 != null) "address_1": address1!,
    if (address2 != null) "address_2": address2!,
    if (company != null) "company": company!,
    if (countryCode != null) "country_code": countryCode!,
    if (city != null) "city": city!,
    if (phone != null) "phone": phone!,
    if (postalCode != null) "postal_code": postalCode!,
    if (province != null) "province": province!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The user's details.
class AdminUser {
  AdminUser({
    this.id,
    this.email,
    this.firstName,
    this.lastName,
    this.avatarUrl,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The user's ID.
  final String? id;
  /// The user's email.
  final String? email;
  /// The user's first name.
  final String? firstName;
  /// The user's last name.
  final String? lastName;
  /// The URL of the user's avatar.
  final String? avatarUrl;
  /// The user's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the user was created.
  final DateTime? createdAt;
  /// The date the user was updated.
  final DateTime? updatedAt;
  /// The date the user was deleted.
  final DateTime? deletedAt;

  factory AdminUser.fromJson(Map<String, dynamic> json) => AdminUser(
    id: json["id"] as String?,
    email: json["email"] as String?,
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    avatarUrl: json["avatar_url"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (email != null) "email": email!,
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (avatarUrl != null) "avatar_url": avatarUrl!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The details of the deleted user.
class AdminUserDeleteResponse {
  AdminUserDeleteResponse({
    this.id,
    this.object,
    this.deleted,
  });

  /// The user's ID.
  final String? id;
  /// The name of the deleted object.
  final String? object;
  /// Whether the user was deleted.
  final bool? deleted;

  factory AdminUserDeleteResponse.fromJson(Map<String, dynamic> json) => AdminUserDeleteResponse(
    id: json["id"] as String?,
    object: json["object"] as String?,
    deleted: json["deleted"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (object != null) "object": object!,
    if (deleted != null) "deleted": deleted!,
  };
}

/// The paginated list of users.
class AdminUserListResponse {
  AdminUserListResponse({
    this.limit,
    this.offset,
    this.count,
    this.users,
    this.estimateCount,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The total number of items.
  final num? count;
  /// The list of users.
  final List<AdminUser>? users;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory AdminUserListResponse.fromJson(Map<String, dynamic> json) => AdminUserListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    users: (json["users"] as List?)?.map((e) => e == null ? null : AdminUser.fromJson(e as Map<String, dynamic>)).toList().cast<AdminUser>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (users != null) "users": users!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The user's details.
class AdminUserResponse {
  AdminUserResponse({
    this.user,
  });

  final AdminUser? user;

  factory AdminUserResponse.fromJson(Map<String, dynamic> json) => AdminUserResponse(
    user: json["user"] == null ? null : AdminUser.fromJson(json["user"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (user != null) "user": user!.toJson(),
  };
}

/// The details of a view configuration.
class AdminViewConfiguration {
  AdminViewConfiguration({
    this.id,
    this.entity,
    this.name,
    this.userId,
    this.isSystemDefault,
    this.configuration,
    this.createdAt,
    this.updatedAt,
  });

  /// The view configuration's ID.
  final String? id;
  /// The entity the view configuration belongs to.
  final String? entity;
  /// The view configuration's name.
  final String? name;
  /// The ID of the user the view configuration belongs to. If `null`, the view configuration is a system default.
  final String? userId;
  /// Whether the view configuration is the system default.
  final bool? isSystemDefault;
  /// The view's configuration.
  final Map<String, dynamic>? configuration;
  /// The date the view configuration was created.
  final DateTime? createdAt;
  /// The date the view configuration was updated.
  final DateTime? updatedAt;

  factory AdminViewConfiguration.fromJson(Map<String, dynamic> json) => AdminViewConfiguration(
    id: json["id"] as String?,
    entity: json["entity"] as String?,
    name: json["name"] as String?,
    userId: json["user_id"] as String?,
    isSystemDefault: json["is_system_default"] as bool?,
    configuration: json["configuration"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (entity != null) "entity": entity!,
    if (name != null) "name": name!,
    if (userId != null) "user_id": userId!,
    if (isSystemDefault != null) "is_system_default": isSystemDefault!,
    if (configuration != null) "configuration": configuration!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
  };
}

/// The details of a view configuration.
class AdminViewConfigurationResponse {
  AdminViewConfigurationResponse({
    this.viewConfiguration,
  });

  final AdminViewConfiguration? viewConfiguration;

  factory AdminViewConfigurationResponse.fromJson(Map<String, dynamic> json) => AdminViewConfigurationResponse(
    viewConfiguration: json["view_configuration"] == null ? null : AdminViewConfiguration.fromJson(json["view_configuration"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (viewConfiguration != null) "view_configuration": viewConfiguration!.toJson(),
  };
}

/// The view's columns.
class AdminViewsEntityColumnsResponse {
  AdminViewsEntityColumnsResponse({
    this.columns,
  });

  /// The view's columns.
  final List<AdminColumn>? columns;

  factory AdminViewsEntityColumnsResponse.fromJson(Map<String, dynamic> json) => AdminViewsEntityColumnsResponse(
    columns: (json["columns"] as List?)?.map((e) => e == null ? null : AdminColumn.fromJson(e as Map<String, dynamic>)).toList().cast<AdminColumn>(),
  );

  Map<String, dynamic> toJson() => {
    if (columns != null) "columns": columns!.map((e) => e.toJson()).toList(),
  };
}
