// GENERATED by tool/generate_models.mjs — do not edit.
part of '../models.dart';

/// The paginated list of products.
class StoreProductListResponse {
  StoreProductListResponse({
    this.limit,
    this.offset,
    this.count,
    this.estimateCount,
    this.products,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items skipped before retrieving the returned items.
  final num? offset;
  /// The total count of items.
  final num? count;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;
  /// The list of products.
  final List<StoreProduct>? products;

  factory StoreProductListResponse.fromJson(Map<String, dynamic> json) => StoreProductListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    estimateCount: json["estimate_count"] as num?,
    products: (json["products"] as List?)?.map((e) => e == null ? null : StoreProduct.fromJson(e as Map<String, dynamic>)).toList().cast<StoreProduct>(),
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (estimateCount != null) "estimate_count": estimateCount!,
    if (products != null) "products": products!.map((e) => e.toJson()).toList(),
  };
}

/// The product option's details.
class StoreProductOption {
  StoreProductOption({
    this.id,
    this.title,
    this.product,
    this.productId,
    this.values,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The option's ID.
  final String? id;
  /// The option's title.
  final String? title;
  final Map<String, dynamic>? product;
  /// The ID of the product this option belongs to.
  final String? productId;
  /// The option's values.
  final List<StoreProductOptionValue>? values;
  /// The option's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the product option was created.
  final DateTime? createdAt;
  /// The date the product option was updated.
  final DateTime? updatedAt;
  /// The date the product option was deleted.
  final DateTime? deletedAt;

  factory StoreProductOption.fromJson(Map<String, dynamic> json) => StoreProductOption(
    id: json["id"] as String?,
    title: json["title"] as String?,
    product: json["product"] as Map<String, dynamic>?,
    productId: json["product_id"] as String?,
    values: (json["values"] as List?)?.map((e) => e == null ? null : StoreProductOptionValue.fromJson(e as Map<String, dynamic>)).toList().cast<StoreProductOptionValue>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (title != null) "title": title!,
    if (product != null) "product": product!,
    if (productId != null) "product_id": productId!,
    if (values != null) "values": values!.map((e) => e.toJson()).toList(),
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The product option value's details.
class StoreProductOptionValue {
  StoreProductOptionValue({
    this.id,
    this.value,
    this.option,
    this.optionId,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The value's ID.
  final String? id;
  /// The value.
  final String? value;
  final Map<String, dynamic>? option;
  /// The ID of the option this value belongs to.
  final String? optionId;
  /// The value's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the value was created.
  final DateTime? createdAt;
  /// The date the value was updated.
  final DateTime? updatedAt;
  /// The date the value was deleted.
  final DateTime? deletedAt;

  factory StoreProductOptionValue.fromJson(Map<String, dynamic> json) => StoreProductOptionValue(
    id: json["id"] as String?,
    value: json["value"] as String?,
    option: json["option"] as Map<String, dynamic>?,
    optionId: json["option_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (value != null) "value": value!,
    if (option != null) "option": option!,
    if (optionId != null) "option_id": optionId!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The product's details.
class StoreProductResponse {
  StoreProductResponse({
    this.product,
  });

  final StoreProduct? product;

  factory StoreProductResponse.fromJson(Map<String, dynamic> json) => StoreProductResponse(
    product: json["product"] == null ? null : StoreProduct.fromJson(json["product"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (product != null) "product": product!.toJson(),
  };
}

/// The tag's details.
class StoreProductTag {
  StoreProductTag({
    this.id,
    this.value,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.metadata,
    this.externalId,
  });

  /// The tag's ID.
  final String? id;
  /// The tag's value.
  final String? value;
  /// The date the tag was created.
  final DateTime? createdAt;
  /// The date the tag was updated.
  final DateTime? updatedAt;
  /// The date the tag was deleted.
  final DateTime? deletedAt;
  /// The tag's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The tag's external ID used to link it with external systems.
  final String? externalId;

  factory StoreProductTag.fromJson(Map<String, dynamic> json) => StoreProductTag(
    id: json["id"] as String?,
    value: json["value"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    metadata: json["metadata"] as Map<String, dynamic>?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (value != null) "value": value!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (metadata != null) "metadata": metadata!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The paginated list of product tags.
class StoreProductTagListResponse {
  StoreProductTagListResponse({
    this.limit,
    this.offset,
    this.count,
    this.productTags,
    this.estimateCount,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items to skip before retrieving the returned items.
  final num? offset;
  /// The total number of items available.
  final num? count;
  /// The list of product tags.
  final List<StoreProductTag>? productTags;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory StoreProductTagListResponse.fromJson(Map<String, dynamic> json) => StoreProductTagListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    productTags: (json["product_tags"] as List?)?.map((e) => e == null ? null : StoreProductTag.fromJson(e as Map<String, dynamic>)).toList().cast<StoreProductTag>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (productTags != null) "product_tags": productTags!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The product tag's details.
class StoreProductTagResponse {
  StoreProductTagResponse({
    this.productTag,
  });

  final StoreProductTag? productTag;

  factory StoreProductTagResponse.fromJson(Map<String, dynamic> json) => StoreProductTagResponse(
    productTag: json["product_tag"] == null ? null : StoreProductTag.fromJson(json["product_tag"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (productTag != null) "product_tag": productTag!.toJson(),
  };
}

/// The product type's details.
class StoreProductType {
  StoreProductType({
    this.id,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.value,
    this.externalId,
  });

  /// The product type's ID.
  final String? id;
  /// The product type's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the product type was created.
  final DateTime? createdAt;
  /// The date the product type was updated.
  final DateTime? updatedAt;
  /// The date the product type was deleted.
  final DateTime? deletedAt;
  /// The type's value.
  final String? value;
  /// The type's external ID used to link it with external systems.
  final String? externalId;

  factory StoreProductType.fromJson(Map<String, dynamic> json) => StoreProductType(
    id: json["id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    value: json["value"] as String?,
    externalId: json["external_id"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (value != null) "value": value!,
    if (externalId != null) "external_id": externalId!,
  };
}

/// The paginated list of product types.
class StoreProductTypeListResponse {
  StoreProductTypeListResponse({
    this.limit,
    this.offset,
    this.count,
    this.productTypes,
    this.estimateCount,
  });

  /// The maximum number of items returned.
  final num? limit;
  /// The number of items to skip before retrieving the returned items.
  final num? offset;
  /// The total number of items available.
  final num? count;
  /// The list of product types.
  final List<StoreProductType>? productTypes;
  /// The estimated count retrieved from the PostgreSQL query planner, which may be inaccurate.
  final num? estimateCount;

  factory StoreProductTypeListResponse.fromJson(Map<String, dynamic> json) => StoreProductTypeListResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    productTypes: (json["product_types"] as List?)?.map((e) => e == null ? null : StoreProductType.fromJson(e as Map<String, dynamic>)).toList().cast<StoreProductType>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (productTypes != null) "product_types": productTypes!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The product type's details.
class StoreProductTypeResponse {
  StoreProductTypeResponse({
    this.productType,
  });

  final StoreProductType? productType;

  factory StoreProductTypeResponse.fromJson(Map<String, dynamic> json) => StoreProductTypeResponse(
    productType: json["product_type"] == null ? null : StoreProductType.fromJson(json["product_type"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (productType != null) "product_type": productType!.toJson(),
  };
}

/// The variant's details.
class StoreProductVariant {
  StoreProductVariant({
    this.options,
    this.product,
    this.length,
    this.title,
    this.metadata,
    this.id,
    this.width,
    this.weight,
    this.height,
    this.originCountry,
    this.hsCode,
    this.midCode,
    this.material,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.productId,
    this.sku,
    this.barcode,
    this.ean,
    this.upc,
    this.allowBackorder,
    this.manageInventory,
    this.inventoryQuantity,
    this.variantRank,
    this.calculatedPrice,
    this.thumbnail,
    this.images,
  });

  /// The variant's options.
  final List<StoreProductOptionValue>? options;
  final Map<String, dynamic>? product;
  /// The variant's length.
  final num? length;
  /// The variant's title.
  final String? title;
  /// The variant's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The variant's ID.
  final String? id;
  /// The variant's width.
  final num? width;
  /// The variant's weight.
  final num? weight;
  /// The variant's height.
  final num? height;
  /// The variant's origin country.
  final String? originCountry;
  /// The variant's HS code.
  final String? hsCode;
  /// The variant's MID code.
  final String? midCode;
  /// The variant's material.
  final String? material;
  /// The date the variant was created.
  final DateTime? createdAt;
  /// The date the variant was updated.
  final DateTime? updatedAt;
  /// The date the variant was deleted.
  final DateTime? deletedAt;
  /// The ID of the product this variant belongs to.
  final String? productId;
  /// The variant's SKU.
  final String? sku;
  /// The variant's barcode.
  final String? barcode;
  /// The variant's EAN.
  final String? ean;
  /// The variant's UPC.
  final String? upc;
  /// Whether the variant can be ordered even if it's not in stock.
  final bool? allowBackorder;
  /// Whether Medusa manages the variant's inventory. If disabled, the variant is always considered in stock.
  final bool? manageInventory;
  /// The variant's inventory quantity. This property is only available if you pass `+variants.inventory_quantity` in the `fields` query parameter.
  final num? inventoryQuantity;
  /// The variant's rank among its siblings.
  final num? variantRank;
  final BaseCalculatedPriceSet? calculatedPrice;
  /// The variant's thumbnail.
  final String? thumbnail;
  /// The variant's images.
  final List<BaseProductImage>? images;

  factory StoreProductVariant.fromJson(Map<String, dynamic> json) => StoreProductVariant(
    options: (json["options"] as List?)?.map((e) => e == null ? null : StoreProductOptionValue.fromJson(e as Map<String, dynamic>)).toList().cast<StoreProductOptionValue>(),
    product: json["product"] as Map<String, dynamic>?,
    length: json["length"] as num?,
    title: json["title"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    id: json["id"] as String?,
    width: json["width"] as num?,
    weight: json["weight"] as num?,
    height: json["height"] as num?,
    originCountry: json["origin_country"] as String?,
    hsCode: json["hs_code"] as String?,
    midCode: json["mid_code"] as String?,
    material: json["material"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
    productId: json["product_id"] as String?,
    sku: json["sku"] as String?,
    barcode: json["barcode"] as String?,
    ean: json["ean"] as String?,
    upc: json["upc"] as String?,
    allowBackorder: json["allow_backorder"] as bool?,
    manageInventory: json["manage_inventory"] as bool?,
    inventoryQuantity: json["inventory_quantity"] as num?,
    variantRank: json["variant_rank"] as num?,
    calculatedPrice: json["calculated_price"] == null ? null : BaseCalculatedPriceSet.fromJson(json["calculated_price"] as Map<String, dynamic>),
    thumbnail: json["thumbnail"] as String?,
    images: (json["images"] as List?)?.map((e) => e == null ? null : BaseProductImage.fromJson(e as Map<String, dynamic>)).toList().cast<BaseProductImage>(),
  );

  Map<String, dynamic> toJson() => {
    if (options != null) "options": options!.map((e) => e.toJson()).toList(),
    if (product != null) "product": product!,
    if (length != null) "length": length!,
    if (title != null) "title": title!,
    if (metadata != null) "metadata": metadata!,
    if (id != null) "id": id!,
    if (width != null) "width": width!,
    if (weight != null) "weight": weight!,
    if (height != null) "height": height!,
    if (originCountry != null) "origin_country": originCountry!,
    if (hsCode != null) "hs_code": hsCode!,
    if (midCode != null) "mid_code": midCode!,
    if (material != null) "material": material!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
    if (productId != null) "product_id": productId!,
    if (sku != null) "sku": sku!,
    if (barcode != null) "barcode": barcode!,
    if (ean != null) "ean": ean!,
    if (upc != null) "upc": upc!,
    if (allowBackorder != null) "allow_backorder": allowBackorder!,
    if (manageInventory != null) "manage_inventory": manageInventory!,
    if (inventoryQuantity != null) "inventory_quantity": inventoryQuantity!,
    if (variantRank != null) "variant_rank": variantRank!,
    if (calculatedPrice != null) "calculated_price": calculatedPrice!.toJson(),
    if (thumbnail != null) "thumbnail": thumbnail!,
    if (images != null) "images": images!.map((e) => e.toJson()).toList(),
  };
}

/// The region's details.
class StoreRegion {
  StoreRegion({
    this.id,
    this.name,
    this.currencyCode,
    this.automaticTaxes,
    this.countries,
    this.paymentProviders,
    this.metadata,
    this.createdAt,
    this.updatedAt,
  });

  /// The region's ID.
  final String? id;
  /// The region's name.
  final String? name;
  /// The region's currency code.
  final String? currencyCode;
  /// Whether taxes are calculated automatically during checkout for carts that belong to this region.
  final bool? automaticTaxes;
  /// The region's countries.
  final List<BaseRegionCountry>? countries;
  /// The region's payment providers.
  final List<AdminPaymentProvider>? paymentProviders;
  /// The region's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the region was created.
  final DateTime? createdAt;
  /// The date the region was updated.
  final DateTime? updatedAt;

  factory StoreRegion.fromJson(Map<String, dynamic> json) => StoreRegion(
    id: json["id"] as String?,
    name: json["name"] as String?,
    currencyCode: json["currency_code"] as String?,
    automaticTaxes: json["automatic_taxes"] as bool?,
    countries: (json["countries"] as List?)?.map((e) => e == null ? null : BaseRegionCountry.fromJson(e as Map<String, dynamic>)).toList().cast<BaseRegionCountry>(),
    paymentProviders: (json["payment_providers"] as List?)?.map((e) => e == null ? null : AdminPaymentProvider.fromJson(e as Map<String, dynamic>)).toList().cast<AdminPaymentProvider>(),
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (name != null) "name": name!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (automaticTaxes != null) "automatic_taxes": automaticTaxes!,
    if (countries != null) "countries": countries!.map((e) => e.toJson()).toList(),
    if (paymentProviders != null) "payment_providers": paymentProviders!.map((e) => e.toJson()).toList(),
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
  };
}

/// The country's details.
class StoreRegionCountry {
  StoreRegionCountry({
    this.id,
    this.iso2,
    this.iso3,
    this.numCode,
    this.name,
    this.displayName,
  });

  /// The country's ID.
  final String? id;
  /// The country's ISO 2.
  final String? iso2;
  /// The country's ISO 3.
  final String? iso3;
  /// The country's num code.
  final String? numCode;
  /// The country's name.
  final String? name;
  /// The country's display name.
  final String? displayName;

  factory StoreRegionCountry.fromJson(Map<String, dynamic> json) => StoreRegionCountry(
    id: json["id"] as String?,
    iso2: json["iso_2"] as String?,
    iso3: json["iso_3"] as String?,
    numCode: json["num_code"] as String?,
    name: json["name"] as String?,
    displayName: json["display_name"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (iso2 != null) "iso_2": iso2!,
    if (iso3 != null) "iso_3": iso3!,
    if (numCode != null) "num_code": numCode!,
    if (name != null) "name": name!,
    if (displayName != null) "display_name": displayName!,
  };
}

/// The details to remove a gift card from the cart.
class StoreRemoveGiftCardFromCart {
  StoreRemoveGiftCardFromCart({
    this.code,
  });

  /// The gift card code to remove from the cart.
  final String? code;

  factory StoreRemoveGiftCardFromCart.fromJson(Map<String, dynamic> json) => StoreRemoveGiftCardFromCart(
    code: json["code"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (code != null) "code": code!,
  };
}

/// The details of requesting the order transfer.
class StoreRequestOrderTransfer {
  StoreRequestOrderTransfer({
    this.description,
    this.updateOrderEmail,
  });

  /// The transfer's description, which can be shown to the other customer receiving the request.
  final String? description;
  /// Whether to update the order's email to the receiving customer's email. By default, the order's email will not be updated.
  final bool? updateOrderEmail;

  factory StoreRequestOrderTransfer.fromJson(Map<String, dynamic> json) => StoreRequestOrderTransfer(
    description: json["description"] as String?,
    updateOrderEmail: json["update_order_email"] as bool?,
  );

  Map<String, dynamic> toJson() => {
    if (description != null) "description": description!,
    if (updateOrderEmail != null) "update_order_email": updateOrderEmail!,
  };
}

/// The return's details.
class StoreReturn {
  StoreReturn({
    this.items,
    this.status,
    this.id,
    this.displayId,
    this.createdAt,
    this.orderId,
    this.locationId,
    this.canceledAt,
    this.exchangeId,
    this.claimId,
    this.refundAmount,
    this.receivedAt,
    this.createdBy,
    this.requestedAt,
  });

  /// The return's items.
  final List<StoreReturnItem>? items;
  /// The return's status.
  final String? status;
  /// The return's ID.
  final String? id;
  /// The return's display ID.
  final num? displayId;
  /// The date the return was created.
  final DateTime? createdAt;
  /// The ID of the order this return belongs to.
  final String? orderId;
  /// The ID of the location the return items are being returned to.
  final String? locationId;
  /// The date the return was canceled.
  final String? canceledAt;
  /// The ID of the associated exchange.
  final String? exchangeId;
  /// The ID of the associated claim.
  final String? claimId;
  /// The amount to be refunded.
  final num? refundAmount;
  /// The date the return items were received.
  final String? receivedAt;
  /// The ID of the user that created the return.
  final String? createdBy;
  /// The date the return was requested.
  final String? requestedAt;

  factory StoreReturn.fromJson(Map<String, dynamic> json) => StoreReturn(
    items: (json["items"] as List?)?.map((e) => e == null ? null : StoreReturnItem.fromJson(e as Map<String, dynamic>)).toList().cast<StoreReturnItem>(),
    status: json["status"] as String?,
    id: json["id"] as String?,
    displayId: json["display_id"] as num?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    orderId: json["order_id"] as String?,
    locationId: json["location_id"] as String?,
    canceledAt: json["canceled_at"] as String?,
    exchangeId: json["exchange_id"] as String?,
    claimId: json["claim_id"] as String?,
    refundAmount: json["refund_amount"] as num?,
    receivedAt: json["received_at"] as String?,
    createdBy: json["created_by"] as String?,
    requestedAt: json["requested_at"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (items != null) "items": items!.map((e) => e.toJson()).toList(),
    if (status != null) "status": status!,
    if (id != null) "id": id!,
    if (displayId != null) "display_id": displayId!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (orderId != null) "order_id": orderId!,
    if (locationId != null) "location_id": locationId!,
    if (canceledAt != null) "canceled_at": canceledAt!,
    if (exchangeId != null) "exchange_id": exchangeId!,
    if (claimId != null) "claim_id": claimId!,
    if (refundAmount != null) "refund_amount": refundAmount!,
    if (receivedAt != null) "received_at": receivedAt!,
    if (createdBy != null) "created_by": createdBy!,
    if (requestedAt != null) "requested_at": requestedAt!,
  };
}

/// The return item's details.
class StoreReturnItem {
  StoreReturnItem({
    this.id,
    this.quantity,
    this.receivedQuantity,
    this.damagedQuantity,
    this.reasonId,
    this.note,
    this.itemId,
    this.returnId,
    this.metadata,
  });

  /// The item's ID.
  final String? id;
  /// The item's quantity.
  final num? quantity;
  /// The item's received quantity.
  final num? receivedQuantity;
  /// The item's damaged quantity.
  final num? damagedQuantity;
  /// The ID of the item's reason.
  final String? reasonId;
  /// A note with more details on why the item is returned.
  final String? note;
  /// The ID of the item in the order.
  final String? itemId;
  /// The ID of the return this item belongs to.
  final String? returnId;
  /// The item's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory StoreReturnItem.fromJson(Map<String, dynamic> json) => StoreReturnItem(
    id: json["id"] as String?,
    quantity: json["quantity"] as num?,
    receivedQuantity: json["received_quantity"] as num?,
    damagedQuantity: json["damaged_quantity"] as num?,
    reasonId: json["reason_id"] as String?,
    note: json["note"] as String?,
    itemId: json["item_id"] as String?,
    returnId: json["return_id"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (quantity != null) "quantity": quantity!,
    if (receivedQuantity != null) "received_quantity": receivedQuantity!,
    if (damagedQuantity != null) "damaged_quantity": damagedQuantity!,
    if (reasonId != null) "reason_id": reasonId!,
    if (note != null) "note": note!,
    if (itemId != null) "item_id": itemId!,
    if (returnId != null) "return_id": returnId!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The return reason's details.
class StoreReturnReason {
  StoreReturnReason({
    this.id,
    this.value,
    this.label,
    this.description,
    this.metadata,
    this.createdAt,
    this.updatedAt,
  });

  /// The return reason's ID.
  final String? id;
  /// The return reason's value.
  final String? value;
  /// The return reason's label.
  final String? label;
  /// The return reason's description.
  final String? description;
  /// The return reason's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the return reason was created.
  final DateTime? createdAt;
  /// The date the return reason was updated.
  final DateTime? updatedAt;

  factory StoreReturnReason.fromJson(Map<String, dynamic> json) => StoreReturnReason(
    id: json["id"] as String?,
    value: json["value"] as String?,
    label: json["label"] as String?,
    description: json["description"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (value != null) "value": value!,
    if (label != null) "label": label!,
    if (description != null) "description": description!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
  };
}

/// The return reason's details.
class StoreReturnReasonResponse {
  StoreReturnReasonResponse({
    this.returnReason,
  });

  final StoreReturnReason? returnReason;

  factory StoreReturnReasonResponse.fromJson(Map<String, dynamic> json) => StoreReturnReasonResponse(
    returnReason: json["return_reason"] == null ? null : StoreReturnReason.fromJson(json["return_reason"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (returnReason != null) "return_reason": returnReason!.toJson(),
  };
}

/// The return's details.
class StoreReturnResponse {
  StoreReturnResponse({
    this.return_,
  });

  final StoreReturn? return_;

  factory StoreReturnResponse.fromJson(Map<String, dynamic> json) => StoreReturnResponse(
    return_: json["return"] == null ? null : StoreReturn.fromJson(json["return"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (return_ != null) "return": return_!.toJson(),
  };
}

/// The shipping option's details.
class StoreShippingOption {
  StoreShippingOption({
    this.id,
    this.name,
    this.priceType,
    this.serviceZoneId,
    this.providerId,
    this.provider,
    this.shippingOptionTypeId,
    this.type,
    this.shippingProfileId,
    this.amount,
    this.isTaxInclusive,
    this.data,
    this.metadata,
  });

  /// The shipping option's ID.
  final String? id;
  /// The shipping option's name.
  final String? name;
  /// The shipping option's price type. If it's `flat`, the price is fixed and is set in the `prices` property. If it's `calculated`, the price is calculated on check
  final String? priceType;
  /// The ID of the service zone the shipping option belongs to.
  final String? serviceZoneId;
  /// The ID of the fulfillment provider handling this option.
  final String? providerId;
  final BaseFulfillmentProvider? provider;
  /// The ID of the shipping option's type.
  final String? shippingOptionTypeId;
  final StoreShippingOptionType? type;
  /// The ID of the associated shipping profile.
  final String? shippingProfileId;
  /// The shipping option's amount.
  final num? amount;
  /// Whether the amount includes taxes.
  final bool? isTaxInclusive;
  /// The shipping option's data, useful for the provider handling fulfillment.
  final Map<String, dynamic>? data;
  /// The shipping option's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory StoreShippingOption.fromJson(Map<String, dynamic> json) => StoreShippingOption(
    id: json["id"] as String?,
    name: json["name"] as String?,
    priceType: json["price_type"] as String?,
    serviceZoneId: json["service_zone_id"] as String?,
    providerId: json["provider_id"] as String?,
    provider: json["provider"] == null ? null : BaseFulfillmentProvider.fromJson(json["provider"] as Map<String, dynamic>),
    shippingOptionTypeId: json["shipping_option_type_id"] as String?,
    type: json["type"] == null ? null : StoreShippingOptionType.fromJson(json["type"] as Map<String, dynamic>),
    shippingProfileId: json["shipping_profile_id"] as String?,
    amount: json["amount"] as num?,
    isTaxInclusive: json["is_tax_inclusive"] as bool?,
    data: json["data"] as Map<String, dynamic>?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (name != null) "name": name!,
    if (priceType != null) "price_type": priceType!,
    if (serviceZoneId != null) "service_zone_id": serviceZoneId!,
    if (providerId != null) "provider_id": providerId!,
    if (provider != null) "provider": provider!.toJson(),
    if (shippingOptionTypeId != null) "shipping_option_type_id": shippingOptionTypeId!,
    if (type != null) "type": type!.toJson(),
    if (shippingProfileId != null) "shipping_profile_id": shippingProfileId!,
    if (amount != null) "amount": amount!,
    if (isTaxInclusive != null) "is_tax_inclusive": isTaxInclusive!,
    if (data != null) "data": data!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The list of shipping options.
class StoreShippingOptionListResponse {
  StoreShippingOptionListResponse({
    this.shippingOptions,
  });

  /// The list of shipping options.
  final List<Map<String, dynamic>>? shippingOptions;

  factory StoreShippingOptionListResponse.fromJson(Map<String, dynamic> json) => StoreShippingOptionListResponse(
    shippingOptions: (json["shipping_options"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
  );

  Map<String, dynamic> toJson() => {
    if (shippingOptions != null) "shipping_options": shippingOptions!.map((e) => e).toList(),
  };
}

/// The shipping option's details.
class StoreShippingOptionResponse {
  StoreShippingOptionResponse({
    this.shippingOption,
  });

  final StoreCartShippingOption? shippingOption;

  factory StoreShippingOptionResponse.fromJson(Map<String, dynamic> json) => StoreShippingOptionResponse(
    shippingOption: json["shipping_option"] == null ? null : StoreCartShippingOption.fromJson(json["shipping_option"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (shippingOption != null) "shipping_option": shippingOption!.toJson(),
  };
}

/// The shipping option type's details.
class StoreShippingOptionType {
  StoreShippingOptionType({
    this.id,
    this.label,
    this.description,
    this.code,
    this.shippingOptionId,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });

  /// The type's ID.
  final String? id;
  /// The type's label.
  final String? label;
  /// The type's description.
  final String? description;
  /// The type's code.
  final String? code;
  /// The ID of the associated shipping option.
  final String? shippingOptionId;
  /// The date the type was created.
  final DateTime? createdAt;
  /// The date the type was updated.
  final DateTime? updatedAt;
  /// The date the type was deleted.
  final DateTime? deletedAt;

  factory StoreShippingOptionType.fromJson(Map<String, dynamic> json) => StoreShippingOptionType(
    id: json["id"] as String?,
    label: json["label"] as String?,
    description: json["description"] as String?,
    code: json["code"] as String?,
    shippingOptionId: json["shipping_option_id"] as String?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    deletedAt: json["deleted_at"] == null ? null : DateTime.parse(json["deleted_at"] as String),
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (label != null) "label": label!,
    if (description != null) "description": description!,
    if (code != null) "code": code!,
    if (shippingOptionId != null) "shipping_option_id": shippingOptionId!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (deletedAt != null) "deleted_at": deletedAt!.toIso8601String(),
  };
}

/// The store credit account's details.
class StoreStoreCreditAccount {
  StoreStoreCreditAccount({
    this.customer,
    this.id,
    this.customerId,
    this.currencyCode,
    this.credits,
    this.debits,
    this.balance,
    this.metadata,
    this.createdAt,
    this.updatedAt,
    this.code,
  });

  final StoreCustomer? customer;
  /// The store credit account's ID.
  final String? id;
  /// The ID of the customer that the store credit account belongs to.
  final String? customerId;
  /// The store credit account's currency code.
  final String? currencyCode;
  /// The account's credits.
  final num? credits;
  /// The account's debits.
  final num? debits;
  /// The store credit account's balance.
  final num? balance;
  /// The store credit account's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;
  /// The date the store credit account was created.
  final DateTime? createdAt;
  /// The date the store credit account was updated.
  final DateTime? updatedAt;
  /// The store credit account's code.
  final String? code;

  factory StoreStoreCreditAccount.fromJson(Map<String, dynamic> json) => StoreStoreCreditAccount(
    customer: json["customer"] == null ? null : StoreCustomer.fromJson(json["customer"] as Map<String, dynamic>),
    id: json["id"] as String?,
    customerId: json["customer_id"] as String?,
    currencyCode: json["currency_code"] as String?,
    credits: json["credits"] as num?,
    debits: json["debits"] as num?,
    balance: json["balance"] as num?,
    metadata: json["metadata"] as Map<String, dynamic>?,
    createdAt: json["created_at"] == null ? null : DateTime.parse(json["created_at"] as String),
    updatedAt: json["updated_at"] == null ? null : DateTime.parse(json["updated_at"] as String),
    code: json["code"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (customer != null) "customer": customer!.toJson(),
    if (id != null) "id": id!,
    if (customerId != null) "customer_id": customerId!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (credits != null) "credits": credits!,
    if (debits != null) "debits": debits!,
    if (balance != null) "balance": balance!,
    if (metadata != null) "metadata": metadata!,
    if (createdAt != null) "created_at": createdAt!.toIso8601String(),
    if (updatedAt != null) "updated_at": updatedAt!.toIso8601String(),
    if (code != null) "code": code!,
  };
}

/// The store credit account's details.
class StoreStoreCreditAccountResponse {
  StoreStoreCreditAccountResponse({
    this.storeCreditAccount,
  });

  final StoreStoreCreditAccount? storeCreditAccount;

  factory StoreStoreCreditAccountResponse.fromJson(Map<String, dynamic> json) => StoreStoreCreditAccountResponse(
    storeCreditAccount: json["store_credit_account"] == null ? null : StoreStoreCreditAccount.fromJson(json["store_credit_account"] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    if (storeCreditAccount != null) "store_credit_account": storeCreditAccount!.toJson(),
  };
}

/// The paginated list of store credit accounts.
class StoreStoreCreditAccountsResponse {
  StoreStoreCreditAccountsResponse({
    this.limit,
    this.offset,
    this.count,
    this.storeCreditAccounts,
    this.estimateCount,
  });

  /// The maximum number of store credit accounts to return.
  final num? limit;
  /// The number of store credit accounts to skip before retrieving the results.
  final num? offset;
  /// The total number of store credit accounts available.
  final num? count;
  /// The list of store credit accounts.
  final List<StoreStoreCreditAccount>? storeCreditAccounts;
  /// The store credit account's estimate count.
  final num? estimateCount;

  factory StoreStoreCreditAccountsResponse.fromJson(Map<String, dynamic> json) => StoreStoreCreditAccountsResponse(
    limit: json["limit"] as num?,
    offset: json["offset"] as num?,
    count: json["count"] as num?,
    storeCreditAccounts: (json["store_credit_accounts"] as List?)?.map((e) => e == null ? null : StoreStoreCreditAccount.fromJson(e as Map<String, dynamic>)).toList().cast<StoreStoreCreditAccount>(),
    estimateCount: json["estimate_count"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (limit != null) "limit": limit!,
    if (offset != null) "offset": offset!,
    if (count != null) "count": count!,
    if (storeCreditAccounts != null) "store_credit_accounts": storeCreditAccounts!.map((e) => e.toJson()).toList(),
    if (estimateCount != null) "estimate_count": estimateCount!,
  };
}

/// The details to update in the customer.
class StoreUpdateCustomer {
  StoreUpdateCustomer({
    this.companyName,
    this.firstName,
    this.lastName,
    this.phone,
    this.metadata,
  });

  /// The customer's company name.
  final String? companyName;
  /// The customer's first name.
  final String? firstName;
  /// The customer's last name.
  final String? lastName;
  /// The customer's phone.
  final String? phone;
  /// The customer's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory StoreUpdateCustomer.fromJson(Map<String, dynamic> json) => StoreUpdateCustomer(
    companyName: json["company_name"] as String?,
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    phone: json["phone"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (companyName != null) "company_name": companyName!,
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (phone != null) "phone": phone!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The properties to update in the address.
class StoreUpdateCustomerAddress {
  StoreUpdateCustomerAddress({
    this.firstName,
    this.lastName,
    this.phone,
    this.company,
    this.address1,
    this.address2,
    this.city,
    this.countryCode,
    this.province,
    this.postalCode,
    this.addressName,
    this.isDefaultShipping,
    this.isDefaultBilling,
    this.metadata,
  });

  /// The customer's first name.
  final String? firstName;
  /// The customer's last name.
  final String? lastName;
  /// The customer's phone.
  final String? phone;
  /// The address's company.
  final String? company;
  /// The address's first line.
  final String? address1;
  /// The address's second line.
  final String? address2;
  /// The address's city.
  final String? city;
  /// The address's country code.
  final String? countryCode;
  /// The address's ISO 3166-2 province code. Must be lower-case.
  final String? province;
  /// The address's postal code.
  final String? postalCode;
  /// The address's name.
  final String? addressName;
  /// Whether the address is used by default for shipping during checkout.
  final bool? isDefaultShipping;
  /// Whether the address is used by default for billing during checkout.
  final bool? isDefaultBilling;
  /// Holds custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory StoreUpdateCustomerAddress.fromJson(Map<String, dynamic> json) => StoreUpdateCustomerAddress(
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    phone: json["phone"] as String?,
    company: json["company"] as String?,
    address1: json["address_1"] as String?,
    address2: json["address_2"] as String?,
    city: json["city"] as String?,
    countryCode: json["country_code"] as String?,
    province: json["province"] as String?,
    postalCode: json["postal_code"] as String?,
    addressName: json["address_name"] as String?,
    isDefaultShipping: json["is_default_shipping"] as bool?,
    isDefaultBilling: json["is_default_billing"] as bool?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (phone != null) "phone": phone!,
    if (company != null) "company": company!,
    if (address1 != null) "address_1": address1!,
    if (address2 != null) "address_2": address2!,
    if (city != null) "city": city!,
    if (countryCode != null) "country_code": countryCode!,
    if (province != null) "province": province!,
    if (postalCode != null) "postal_code": postalCode!,
    if (addressName != null) "address_name": addressName!,
    if (isDefaultShipping != null) "is_default_shipping": isDefaultShipping!,
    if (isDefaultBilling != null) "is_default_billing": isDefaultBilling!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details to update in the address.
class UpdateAddress {
  UpdateAddress({
    this.id,
    this.customerId,
    this.company,
    this.firstName,
    this.lastName,
    this.address1,
    this.address2,
    this.city,
    this.countryCode,
    this.province,
    this.postalCode,
    this.phone,
    this.metadata,
  });

  /// The ID of an existing address to update.
  final String? id;
  /// The ID of the customer that this address belongs to.
  final String? customerId;
  /// The address's company.
  final String? company;
  /// The address's first name.
  final String? firstName;
  /// The address's last name.
  final String? lastName;
  /// The address's first line.
  final String? address1;
  /// The address's second line.
  final String? address2;
  /// The address's city.
  final String? city;
  /// The address's country code.
  final String? countryCode;
  /// The address's ISO 3166-2 province code. Must be lower-case.
  final String? province;
  /// The address's postal code.
  final String? postalCode;
  /// The address's phone.
  final String? phone;
  /// The address's metadata, can hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory UpdateAddress.fromJson(Map<String, dynamic> json) => UpdateAddress(
    id: json["id"] as String?,
    customerId: json["customer_id"] as String?,
    company: json["company"] as String?,
    firstName: json["first_name"] as String?,
    lastName: json["last_name"] as String?,
    address1: json["address_1"] as String?,
    address2: json["address_2"] as String?,
    city: json["city"] as String?,
    countryCode: json["country_code"] as String?,
    province: json["province"] as String?,
    postalCode: json["postal_code"] as String?,
    phone: json["phone"] as String?,
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (id != null) "id": id!,
    if (customerId != null) "customer_id": customerId!,
    if (company != null) "company": company!,
    if (firstName != null) "first_name": firstName!,
    if (lastName != null) "last_name": lastName!,
    if (address1 != null) "address_1": address1!,
    if (address2 != null) "address_2": address2!,
    if (city != null) "city": city!,
    if (countryCode != null) "country_code": countryCode!,
    if (province != null) "province": province!,
    if (postalCode != null) "postal_code": postalCode!,
    if (phone != null) "phone": phone!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The details to update in a cart.
class UpdateCartData {
  UpdateCartData({
    this.regionId,
    this.customerId,
    this.salesChannelId,
    this.email,
    this.currencyCode,
    this.shippingAddressId,
    this.billingAddressId,
    this.billingAddress,
    this.shippingAddress,
    this.metadata,
  });

  /// The ID of the associated region. This can affect the prices and currency code of the cart.
  final String? regionId;
  /// The ID of the customer that the cart belongs to.
  final String? customerId;
  /// The ID of the associated sales channel. Only products available in this channel can be added to the cart.
  final String? salesChannelId;
  /// The email of the customer that the cart belongs to.
  final String? email;
  /// The cart's currency code.
  final String? currencyCode;
  /// The ID of the cart's shipping address.
  final String? shippingAddressId;
  /// The ID of the cart's billing address.
  final String? billingAddressId;
  final dynamic billingAddress;
  final dynamic shippingAddress;
  /// The cart's metadata, ca hold custom key-value pairs.
  final Map<String, dynamic>? metadata;

  factory UpdateCartData.fromJson(Map<String, dynamic> json) => UpdateCartData(
    regionId: json["region_id"] as String?,
    customerId: json["customer_id"] as String?,
    salesChannelId: json["sales_channel_id"] as String?,
    email: json["email"] as String?,
    currencyCode: json["currency_code"] as String?,
    shippingAddressId: json["shipping_address_id"] as String?,
    billingAddressId: json["billing_address_id"] as String?,
    billingAddress: json["billing_address"],
    shippingAddress: json["shipping_address"],
    metadata: json["metadata"] as Map<String, dynamic>?,
  );

  Map<String, dynamic> toJson() => {
    if (regionId != null) "region_id": regionId!,
    if (customerId != null) "customer_id": customerId!,
    if (salesChannelId != null) "sales_channel_id": salesChannelId!,
    if (email != null) "email": email!,
    if (currencyCode != null) "currency_code": currencyCode!,
    if (shippingAddressId != null) "shipping_address_id": shippingAddressId!,
    if (billingAddressId != null) "billing_address_id": billingAddressId!,
    if (billingAddress != null) "billing_address": billingAddress!,
    if (shippingAddress != null) "shipping_address": shippingAddress!,
    if (metadata != null) "metadata": metadata!,
  };
}

/// The workflow execution's context.
class WorkflowExecutionContext {
  WorkflowExecutionContext({
    this.data,
    this.compensate,
    this.errors,
  });

  /// The context's data.
  final Map<String, dynamic>? data;
  /// The context's compensate.
  final Map<String, dynamic>? compensate;
  /// The context's errors.
  final List<Map<String, dynamic>>? errors;

  factory WorkflowExecutionContext.fromJson(Map<String, dynamic> json) => WorkflowExecutionContext(
    data: json["data"] as Map<String, dynamic>?,
    compensate: json["compensate"] as Map<String, dynamic>?,
    errors: (json["errors"] as List?)?.map((e) => e as Map<String, dynamic>?).toList().cast<Map<String, dynamic>>(),
  );

  Map<String, dynamic> toJson() => {
    if (data != null) "data": data!,
    if (compensate != null) "compensate": compensate!,
    if (errors != null) "errors": errors!.map((e) => e).toList(),
  };
}

/// The step's definition details.
class WorkflowExecutionDefinition {
  WorkflowExecutionDefinition({
    this.async,
    this.compensateAsync,
    this.noCompensation,
    this.continueOnPermanentFailure,
    this.skipOnPermanentFailure,
    this.maxRetries,
    this.noWait,
    this.retryInterval,
    this.retryIntervalAwaiting,
    this.saveResponse,
    this.timeout,
    this.autoRetry,
    this.maxAwaitingRetries,
  });

  /// Whether the step is async.
  final bool? async;
  /// Whether the compensation function of the step is async.
  final bool? compensateAsync;
  /// Whether the step doesn't have a compensation function.
  final bool? noCompensation;
  /// Whether the workflow should continue executing even if its status is changed to failed.
  final bool? continueOnPermanentFailure;
  final dynamic skipOnPermanentFailure;
  /// The maximum number of times to retry the step.
  final num? maxRetries;
  /// Whether the workflow shouldn't wait for the step to finish before moving to the next step.
  final bool? noWait;
  /// The interval in seconds between retry attempts when the step fails.
  final num? retryInterval;
  /// The interval in seconds to retry a step even if its status is `waiting_response`.
  final num? retryIntervalAwaiting;
  /// Whether the step's response is stored.
  final bool? saveResponse;
  /// The maximum time in seconds to wait for this step to complete. If the step exceeds this time, the step's state is changed to `timeout`, but the step continues e
  final num? timeout;
  /// Whether the step should be automatically retried if it fails.
  final bool? autoRetry;
  /// The maximum number of times to retry the step while it's in the `waiting_response` state.
  final num? maxAwaitingRetries;

  factory WorkflowExecutionDefinition.fromJson(Map<String, dynamic> json) => WorkflowExecutionDefinition(
    async: json["async"] as bool?,
    compensateAsync: json["compensateAsync"] as bool?,
    noCompensation: json["noCompensation"] as bool?,
    continueOnPermanentFailure: json["continueOnPermanentFailure"] as bool?,
    skipOnPermanentFailure: json["skipOnPermanentFailure"],
    maxRetries: json["maxRetries"] as num?,
    noWait: json["noWait"] as bool?,
    retryInterval: json["retryInterval"] as num?,
    retryIntervalAwaiting: json["retryIntervalAwaiting"] as num?,
    saveResponse: json["saveResponse"] as bool?,
    timeout: json["timeout"] as num?,
    autoRetry: json["autoRetry"] as bool?,
    maxAwaitingRetries: json["maxAwaitingRetries"] as num?,
  );

  Map<String, dynamic> toJson() => {
    if (async != null) "async": async!,
    if (compensateAsync != null) "compensateAsync": compensateAsync!,
    if (noCompensation != null) "noCompensation": noCompensation!,
    if (continueOnPermanentFailure != null) "continueOnPermanentFailure": continueOnPermanentFailure!,
    if (skipOnPermanentFailure != null) "skipOnPermanentFailure": skipOnPermanentFailure!,
    if (maxRetries != null) "maxRetries": maxRetries!,
    if (noWait != null) "noWait": noWait!,
    if (retryInterval != null) "retryInterval": retryInterval!,
    if (retryIntervalAwaiting != null) "retryIntervalAwaiting": retryIntervalAwaiting!,
    if (saveResponse != null) "saveResponse": saveResponse!,
    if (timeout != null) "timeout": timeout!,
    if (autoRetry != null) "autoRetry": autoRetry!,
    if (maxAwaitingRetries != null) "maxAwaitingRetries": maxAwaitingRetries!,
  };
}

/// The state of the step's invokation function.
class WorkflowExecutionFn {
  WorkflowExecutionFn({
    this.state,
    this.status,
  });

  /// The invokation step's state.
  final String? state;
  /// The invokation step's state.
  final String? status;

  factory WorkflowExecutionFn.fromJson(Map<String, dynamic> json) => WorkflowExecutionFn(
    state: json["state"] as String?,
    status: json["status"] as String?,
  );

  Map<String, dynamic> toJson() => {
    if (state != null) "state": state!,
    if (status != null) "status": status!,
  };
}
